import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { fileURLToPath } from "node:url";
import { FALLBACK_CONTROLS, fillSlots, slots, outsideSlots, validateHtml } from "./policy-slots.mjs";

const repo = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../.."), out = path.join(repo, "worker/src/policy-content.ts");
const pages = [{ file: "index.html", self: "/policies", heading: "Olympus Verify" }, { file: "privacy.html", self: "/privacy", heading: "Privacy Policy" }, { file: "terms.html", self: "/terms", heading: "Terms of Service" }];
const sha = value => crypto.createHash("sha256").update(value).digest("hex");
export function build() {
  const docs = pages.map(page => {
    const input = fs.readFileSync(path.join(repo, "policies", page.file), "utf8");
    const source = fillSlots(input, { ACCOUNT_CONTROLS: FALLBACK_CONTROLS, BNET_LOGIN: "" });
    if (source !== input) throw Error("canonical_fallback_slots_not_current:" + page.file);
    slots(source); validateHtml(source, { mirror: true });
    const title = /<title>([^<]*)<\/title>/.exec(source)?.[1], main = /<main>\n([\s\S]*?)\n<\/main>/.exec(source)?.[1];
    if (!title || !main) throw Error("missing_policy_shell");
    const body = main.replace('<p class="meta" style="margin-top:2.5rem">See also the <a href="./terms.html">', '<p class="meta related">See also the <a href="/terms">').replace('<p class="meta" style="margin-top:2.5rem">See also the <a href="./privacy.html">', '<p class="meta related">See also the <a href="/privacy">').replaceAll('href="./privacy.html"', 'href="/privacy"').replaceAll('href="./terms.html"', 'href="/terms"');
    if (/style=|\.\/(privacy|terms)\.html/.test(body)) throw Error("unconverted_policy_link");
    const nav = pages.slice(1).map(p => `<a href="${p.self}"${p === page ? ' aria-current="page"' : ""}>${p.heading}</a>`).join("");
    const html = `<!doctype html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n<meta name="viewport" content="width=device-width,initial-scale=1">\n<title>${title}</title>\n<meta name="color-scheme" content="dark">\n<link rel="stylesheet" href="/static/policies.css">\n</head>\n<body class="olympus-policy">\n<a class="skip-link" href="#policy-content">Skip to policy</a>\n<header class="policy-header">\n<a class="brand" href="/"><img src="/static/olympus-icon.png" alt="" width="40" height="40">Olympus</a>\n<nav aria-label="Policies">${nav}</nav>\n</header>\n<main id="policy-content" tabindex="-1">\n${body}\n</main>\n</body>\n</html>\n`;
    validateHtml(html); return { page, source, html, sourceHash: sha(source), outsideHash: sha(outsideSlots(source)) };
  });
  const version = sha(docs.map(d => d.page.file + "\n" + d.sourceHash).join("\n"));
  const generated = `// GENERATED by worker/scripts/build-policy-content.mjs (.116 anonymous policy/contact successor).\n// Operational serving privacy controls are described; Battle.net login remains separately OFF.\nconst INDEX = ${JSON.stringify(docs[0].html)};\nconst PRIVACY = ${JSON.stringify(docs[1].html)};\nconst TERMS = ${JSON.stringify(docs[2].html)};\nexport const POLICY_SOURCE_DIGEST = ${JSON.stringify(version)};\n/** A marker alone cannot activate collection; policy-release.ts stays immutable OFF. */\nexport const PRIVACY_DESCRIBES_BNET_LOGIN = false;\nexport function policyDocument(path: string): string | null {\n  if (["/policies", "/policies/index.html"].includes(path)) return INDEX;\n  if (["/privacy", "/privacy-policy", "/privacy.html"].includes(path)) return PRIVACY;\n  if (["/terms", "/tos", "/terms-of-service", "/terms.html"].includes(path)) return TERMS;\n  return null;\n}\n`;
  return { docs, version, generated };
}
export function run(check = false) {
  const result = build();
  for (const d of result.docs) {
    const mirror = path.join(repo, d.page.file);
    if (check) { if (!fs.existsSync(mirror) || fs.readFileSync(mirror, "utf8") !== d.source) throw Error("root_mirror_stale:" + d.page.file); }
    else fs.writeFileSync(mirror, d.source);
  }
  if (check) { if (!fs.existsSync(out) || fs.readFileSync(out, "utf8") !== result.generated) throw Error("policy_content_stale"); }
  else fs.writeFileSync(out, result.generated);
  return { policyVersion: result.version, mirrors: result.docs.length, bnetLogin: "OFF", publication: false };
}
