// .128: exact reviewed public text, original request labels and structural/access boundaries.
// Frontend interaction and Worker admission regressions are in frontend_check.cjs.
const fs = require("fs"), path = require("path"), crypto = require("crypto");
const root = path.join(__dirname, ".."), dir = path.join(root, "public/static/governance");
const bytes = fs.readFileSync(path.join(dir, "reconciled-book.md"));
const text = bytes.toString("utf8"), data = JSON.parse(fs.readFileSync(path.join(dir, "organization.json"), "utf8"));
let n = 0, ok = 0;
function check(label, value) { n++; if (value) ok++; console.log((value ? "PASS " : "FAIL ") + label); }
const requested = [
  "Academy Lead (Training Lead)", "Addon Developer", "Addon / Discord Architect", "Alt (Verified Alt)", "Alt / Social Member", "Ambassador", "Artisan", "Bank Auditor", "Bank Manager", "Bank Steward", "Bench", "Broadcaster", "Casual", "Chief of Intake (Gatekeeper, Intake Gatekeeper)", "Chief of Staff", "Chief Strategist (Head of Research)", "Class Head", "Class Lead", "Co-GM", "Coalition Lead (Foreign Affairs Lead)", "Community & Events Lead", "Community Officer (Social Officer)", "Content Creator", "Content Rep (Stream Rep)", "Core Raider", "Council of Justice", "Crafter", "Department Head", "Deputy", "Diplomat", "Diplomatic Envoy", "Discord Engineer", "Discord Moderator", "Emissary", "Emissary of Artisanry", "Emissary of Finance", "Emissary of Heraldry", "Emissary of War (War Emissary)", "Event Coordinator", "Event Officer", "Final Authority", "Founder", "Guild Master (GM)", "Guild Recruiter", "High Council", "Honorary / Emeritus", "Inactive", "Initiate", "Intelligence / Scouting Lead", "Lead Correspondent", "Loot Council", "Marshall", "Media & Communications Lead", "Media Lead", "Member (Roster Member)", "Mentor", "Minister", "Minister of Artisanry", "Minister of Heraldry", "Moderator", "Muted", "Officer", "Officer Alt", "Penal / Sentry Hold (Timeout)", "Per-Guild Correspondent", "Pledge", "Privy Council", "Probation", "Profession Coordinator", "PvP Captain", "PvP Lead (PvP Leader)", "Quartermaster", "Raid Assist", "Raid Leader (Raid Lead)", "Raider", "Recruit", "Recruiter", "Recruitment Lead", "Recruitment Officer", "Social", "Sovereign (The King)", "Tech / Tools Officer", "Technical Envoy", "The Court", "Tithe Payer (Treasury Tiers)", "Treasurer (Guild Bank)", "Trial (Trial Member, Trialist, Trial/Recruit)", "Trial Officer", "Trial Raider", "Veteran", "Veteran Officer", "Vice Guild Master", "VIP", "War Head", "Welfare / Community Support Lead"
];
const rankNames = ["Guild Master", "High Council", "Officer", "Officer Alt", "Raid Leader", "Veteran", "Raider", "Member", "Alt", "Initiate"];
const ids = new Map(data.nodes.map((node) => [node.id, node]));
check("public book is byte-identical to independently reviewed R6, including line endings", bytes.length === 116006 && crypto.createHash("sha256").update(bytes).digest("hex") === "dc250be085cd89c9ddb0e4dd6029d7392898e73a7df893657670e44c65d367ca");
check("model binds exact R6, not the old builder R5 banner", data.revision === "R6" && data.book.bytes === bytes.length && data.book.sha256 === crypto.createHash("sha256").update(bytes).digest("hex") && data.book.path === "/static/governance/reconciled-book.md");
check("publication preserves unratified/no-issued-appointment status", data.draft === true && data.ratified === false && data.appointmentsIssued === false && text.includes("Successor draft R6 (distinct revision of R5)") && text.includes("The authoring date is not an adoption or effective date"));
check("entire book has all13 chapters,20 ordinances and required adoption/template anchors", (text.match(/^# /gm) || []).length === 13 && (text.match(/^## ORD \d\d /gm) || []).length === 20 && ["# Reading and Adopting This Book", "# 3 Letters Patent and Warrants", "# Adoption and Office Registers", "# Daily News Template", "# Source and Decision Register"].every((s) => text.includes(s)));
check("every95 original label is exact, once, in owner order", requested.length === 95 && data.terms.length === 95 && data.terms.every((term, i) => term.label === requested[i] && term.ordinal === i + 1) && new Set(data.terms.map((term) => term.label)).size === 95);
check("all labels have an explicit classification, related structural node and limits", data.terms.every((term) => data.termGroups.some((group) => group.id === term.classification) && ids.has(term.nodeId) && term.note.length > 20 && ids.get(term.nodeId).limits.length > 20));
check("ten native rank slots remain separate and complete", JSON.stringify(data.nativeRanks.map((r) => r.name)) === JSON.stringify(rankNames) && data.nativeRanks.every((r, i) => r.order === i + 1) && data.terms.filter((t) => t.classification === "native").length === 10);
check("Veteran draft accurately includes Invite Member plus repairs without applying permissions", data.nativeRanks[5].meaning.includes("Invite Member and Guild Bank Repairs") && text.includes("Invite Member") && !data.nativeRanks[5].meaning.includes("Withdraw Gold"));
check("Founder->Council and local GM->Officers are accountability links", ids.get("council").parent === "founder" && ids.get("council").relation === "accountability" && ids.get("guilds").parent === "council" && ids.get("officers").parent === "guilds");
check("four portfolios and shared Systems have distinct meanings", ["war", "treasury", "artisanry", "heraldry"].every((id) => ids.get(id).parent === "council" && ids.get(id).kind === "core portfolio") && data.nodes.filter((node) => node.kind === "core portfolio").length === 4 && ids.get("systems").kind === "shared support division" && ids.get("systems").limits.includes("not a fifth"));
check("Justice and auditor retain independent conflict-exclusion boundaries", ids.get("justice").relation === "independence" && ids.get("auditor").relation === "independence" && ids.get("auditor").limits.includes("Cannot audit their own custody"));
const emissaries = data.nodes.filter((node) => node.parent === "emissaries");
check("five local emissaries coordinate to the exact portfolios without command lines", emissaries.length === 5 && emissaries.every((node) => node.relation === "coordination") && JSON.stringify(emissaries.flatMap((node) => node.coordinates)) === JSON.stringify(["war-pvp", "war-raiding", "treasury", "artisanry", "heraldry"]));
check("local tactical, custody and support remits remain below delegated local officers", ["tactical", "custody", "local-intake", "local-events", "class-support", "welfare"].every((id) => ids.get(id).parent === "officers"));
check("courtesy/review vocabulary does not create native powers", ["Privy Council", "The Court", "Sovereign (The King)"].every((label) => data.terms.find((t) => t.label === label).note.includes("creates no further governing body")) && data.terms.find((t) => t.label === "Muted").note.includes("applies no sanction") && ids.get("honorary").limits.includes("No automatic"));
check("I-X placeholders are exact and expressly unappointed", JSON.stringify(data.guildPlaceholders.map((g) => g.name)) === JSON.stringify(["I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X"].map((s) => "Olympus " + s)) && data.guildPlaceholders.every((g) => g.state === "Unappointed placeholder"));
const serialized = JSON.stringify(data);
check("generic organization has no actual-name directory payload or unissued holders", !/richwcampbell|Fernmelder|Maxran|Akafoxslayer|discord_id|discordId|163042307090808833|602457634276376589/.test(serialized) && data.directoryRoute === "#/community/leadership");
check("public draft does not expose held release ruleset details or private local artifacts", !/\bPVE\b|name.reservation|C:\\Users\\|\.dev\.vars|AppData|OlympusRecovery/.test(text + serialized));
check("hierarchy has unique ids, valid references and no cycles", data.nodes.every((node) => {
  const visited = new Set(); let cursor = node;
  while (cursor) { if (visited.has(cursor.id)) return false; visited.add(cursor.id); if (cursor.parent !== null && !ids.has(cursor.parent)) return false; cursor = ids.get(cursor.parent); }
  return node.coordinates.every((id) => ids.has(id));
}) && ids.size === data.nodes.length);
// R6 download contract executes only stdlib asset checks and the exact public h/add quicklink slice.
for (const result of require("./governance_download_contract.cjs").runChecks(root)) check(result.name, result.passed);
console.log(`\n${ok}/${n} passed`);
process.exit(ok === n ? 0 : 1);
