// Real TypeScript over the separate test-local paused-P schema fixture. This
// successor preserves the original fault suite; it does not qualify live schema.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),ts=require(process.env.PRIVACY129_TYPESCRIPT || 'typescript');
const {DatabaseSync}=require('node:sqlite');const crypto=require('node:crypto');const root=path.join(__dirname,'..'),cache=new Map();let checks=0;
function load(name){if(cache.has(name))return cache.get(name).exports;const module={exports:{}};cache.set(name,module);const src=fs.readFileSync(path.join(root,'src',name+'.ts'),'utf8');const js=ts.transpileModule(src,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;vm.runInNewContext('(function(require,module,exports){'+js+'\n})',{crypto:crypto.webcrypto,TextEncoder,TextDecoder,Uint8Array,console}, {filename:name})(q=>{if(!q.startsWith('./'))throw Error('external module refused');return load(q.slice(2));},module,module.exports);return module.exports;}
const core=load('account-lifecycle'),erase=load('privacy-erasure'),catalog=load('privacy-store-catalog'),contracts=load('account-generation-contracts');
function ok(name,test){assert.ok(test,name);checks++;}
function eq(name,actual,expected){assert.deepEqual(JSON.parse(JSON.stringify(actual)),JSON.parse(JSON.stringify(expected)),name);checks++;}
function adapter(db,hooks={}){
 const exec=(sql,params)=>{if(sql.startsWith('SELECT CASE'))return {success:true,results:db.prepare(sql).all(...params),meta:{changes:0}};const r=db.prepare(sql).run(...params);return {success:true,results:[],meta:{changes:Number(r.changes)}};};
 const statement=sql=>{if(Buffer.byteLength(sql,'utf8')>=100000)throw Error('native-size fixture bound');hooks.prepare?.(sql);let values=[];const api={bind(...v){const max=Math.max(0,...[...sql.matchAll(/\?(\d+)/g)].map(x=>Number(x[1])));if(max!==v.length)throw Error('bind count '+max+' vs '+v.length);if(v.length>100||v.some(x=>x===undefined))throw Error('binding budget');values=v;return api;},async first(){hooks.read?.(sql);const row=db.prepare(sql).get(...values)??null;return hooks.readReply?hooks.readReply(sql,row):row;},async all(){hooks.read?.(sql);return {success:true,meta:{changes:0},results:db.prepare(sql).all(...values)};},async run(){return exec(sql,values);},_exec(index){return hooks.omit?.(index,sql)?exec('UPDATE site_users SET session_version=session_version WHERE 0',[]):exec(sql,values);}};return api;};
 return {prepare:statement,async batch(stmts){hooks.before?.(stmts);if(hooks.skipBatch)return hooks.reply?.([])??[];db.exec('BEGIN');let out;try{out=stmts.map((s,i)=>{hooks.step?.(i);return s._exec(i);});db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}hooks.after?.();return hooks.reply?hooks.reply(out):out;}};
}
const A='123456789012345678',B='987654321098765432',G='1'.repeat(32),P='2'.repeat(32),E='3'.repeat(32),D='4'.repeat(64);
function fixture(){const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON');db.exec(fs.readFileSync(path.join(root,'tests/fixtures/privacy-foundation129/paused-P-schema.sql'),'utf8'));const now=db.prepare("SELECT CAST(strftime('%s','now') AS INTEGER) AS t").get().t;
 // Fixture clock only: the TTL negative must not depend on crossing a wall-clock
 // second between setup and the consuming INSERT. Boundary tests override this.
 db.function('strftime',(format,value)=>{assert.equal(format,'%s');assert.equal(value,'now');return String(now);});
 db.prepare('INSERT INTO generation_control VALUES(1,?,0,0)').run(E);for(const id of [A,B]){db.prepare("INSERT INTO account_generations VALUES(?,?,'active',0,'reviewed-legacy',?)").run(id,G,D);for(const purpose of ['erasure','role_grant','account_write','privacy_identity','privacy_export'])db.prepare('INSERT INTO account_purpose_generations(account_id,account_generation,purpose,generation,updated_at) VALUES(?,?,?,?,?)').run(id,G,purpose,P,now);db.prepare('INSERT INTO members(discord_id,banned) VALUES(?,0)').run(id);db.prepare('INSERT INTO site_users(discord_id,first_login,last_login,session_version) VALUES(?,?,?,7)').run(id,now,now);}
 db.prepare("INSERT INTO invite_queue(name_key,name,discord_id,status,created_at,claimed_by,claimed_at) VALUES('fixture','Fixture',?,'queued',?,'officer',?)").run(A,now,now);
 db.prepare("INSERT INTO roster_effects(run_id,seq,kind,name_key,name,discord_id) VALUES(1,1,'note','fixture','Fixture',?)").run(A);
 const operation={subject:A,accountGeneration:G,purposeGeneration:P,epoch:E,operationId:'5'.repeat(32),requestDigest:'6'.repeat(64),accountRevision:0,controlRevision:0,provenanceDigest:D,expiresAt:now+3600};return {db,now,operation};}
const count=(db,table,where='',params=[])=>db.prepare('SELECT COUNT(*) AS n FROM '+table+(where?' WHERE '+where:'')).get(...params).n;
function pending(f,id=A,n=1){const s=f.db.prepare('INSERT INTO pending(discord_id,name_key,name,created_at,expires_at) VALUES(?,?,?,?,?)');for(let i=0;i<n;i++)s.run(id,'fixture'+i,'Fixture '+i,f.now,f.now+3600);}
(async()=>{
eq('composition closed',Object.values(core.LIFECYCLE_COMPOSITION),[false,false,false,false,false,false]);eq('54 logical catalog stores are distinct from raw schema count',new Set(catalog.STORE_CATALOG.map(x=>x.table)).size,54);ok('catalog immutable',Object.isFrozen(catalog.STORE_CATALOG)&&catalog.STORE_CATALOG.every(x=>Object.isFrozen(x)&&(!x.plan||Object.isFrozen(x.plan))));ok('all reference coverage explicitly unqualified',catalog.STORE_CATALOG.every(x=>x.referenceCoverage==='unqualified'));
eq('seven test-local dormant foundation/login table definitions',core.ACCOUNT_LIFECYCLE_DDL.filter(x=>x.startsWith('CREATE TABLE')).length,7);
let f=fixture();pending(f,A,250);pending(f,B,3);ok('catalog actual schema match',await catalog.catalogMatchesSchema(adapter(f.db)));const original={...f.operation};let r=await core.retireExistingAccount(adapter(f.db),f.operation);eq('retirement remains held',r.status,'held');ok('retirement at most24 attempts',r.attempts<=24);eq('retired active state CAS to retiring',f.db.prepare('SELECT state,revision FROM account_generations WHERE account_id=?').get(A),{state:'retiring',revision:1});eq('ordinary session revoked',f.db.prepare('SELECT session_version FROM site_users WHERE discord_id=?').get(A).session_version,8);eq('other account unchanged',f.db.prepare('SELECT session_version FROM site_users WHERE discord_id=?').get(B).session_version,7);eq('ordinary and privacy purposes revoked',count(f.db,'account_purpose_generations','account_id=? AND purpose<>?', [A,'erasure']),0);ok('cleanup purpose fresh',f.db.prepare("SELECT generation FROM account_purpose_generations WHERE account_id=? AND purpose='erasure'").get(A).generation!==P);eq('queue cancelled and claim released',f.db.prepare('SELECT status,claimed_by,claimed_at FROM invite_queue WHERE discord_id=?').get(A),{status:'cancelled',claimed_by:null,claimed_at:null});eq('raw roster effects cancelled',count(f.db,'roster_effects','discord_id=?',[A]),0);eq('held outbox single row',count(f.db,'privacy_external_outbox'),1);eq('54 durable per-store steps',count(f.db,'privacy_erasure_progress'),54);eq('policy records held',count(f.db,'privacy_erasure_progress',"state='held' AND store_key IN('members','site_users','roster_members','audit')"),4);
const ref=core.reference(original);r=await core.retireExistingAccount(adapter(f.db),original);eq('same operation replay one job',count(f.db,'privacy_erasure_jobs'),1);eq('replay does not revoke session twice',f.db.prepare('SELECT session_version FROM site_users WHERE discord_id=?').get(A).session_version,8);ok('mismatched replay refused',(await core.retireExistingAccount(adapter(f.db),{...original,requestDigest:'7'.repeat(64)})).status==='refused');
r=await erase.runErasureSlice(adapter(f.db),ref);eq('first cursor slice100rows',count(f.db,'pending','discord_id=?',[A]),150);r=await erase.runErasureSlice(adapter(f.db),ref);eq('second cursor slice100rows',count(f.db,'pending','discord_id=?',[A]),50);r=await erase.runErasureSlice(adapter(f.db),ref);eq('last cursor slice50rows',count(f.db,'pending','discord_id=?',[A]),0);eq('counterparty rows intact',count(f.db,'pending','discord_id=?',[B]),3);eq('durable progress count250',f.db.prepare("SELECT purged_rows FROM privacy_erasure_progress WHERE store_key='pending'").get().purged_rows,250);ok('every slice within24',r.attempts<=24);for(let i=0;i<25&&r.pendingPlans;i++)r=await erase.runErasureSlice(adapter(f.db),ref);eq('finite subset finishes',r.status,'local_plans_finished');ok('never full erasure',r.allStoresErased===false&&r.externalEffects==='held'&&r.authorityAdopted===false&&r.heldPlans>0);eq('held member row retained pending policy',count(f.db,'members','discord_id=?',[A]),1);eq('account not falsely terminal retired',f.db.prepare('SELECT state FROM account_generations WHERE account_id=?').get(A).state,'retiring');eq('outbox cannot advance without adoption',f.db.prepare('SELECT state FROM privacy_external_outbox').get().state,'held');assert.throws(()=>f.db.prepare("UPDATE privacy_external_outbox SET state='done'").run());checks++;f.db.close();
for(const [name,mutate] of [['missing-account',x=>x.db.prepare('DELETE FROM account_purpose_generations WHERE account_id=?').run(A)&&x.db.prepare('DELETE FROM account_generations WHERE account_id=?').run(A)],['stale-generation',x=>x.operation.accountGeneration='8'.repeat(32)],['stale-purpose',x=>x.operation.purposeGeneration='8'.repeat(32)],['wrong-provenance',x=>x.operation.provenanceDigest='8'.repeat(64)],['restore-hold',x=>x.db.prepare('UPDATE generation_control SET restore_hold=1').run()],['wrong-epoch',x=>x.operation.epoch='8'.repeat(32)],['expired',x=>x.operation.expiresAt=x.now-1],['too-long-ttl',x=>x.operation.expiresAt=x.now+86401],['unknown-table',x=>x.db.exec('CREATE TABLE unclassified_private_rows(id TEXT)')]]){const x=fixture();pending(x);mutate(x);r=await core.retireExistingAccount(adapter(x.db),x.operation);ok(name+' refused/held',r.status!=='local_plans_finished');eq(name+' no job',count(x.db,'privacy_erasure_jobs'),0);eq(name+' no deletion',count(x.db,'pending'),1);eq(name+' no role intent',count(x.db,'privacy_external_outbox'),0);x.db.close();}
f=fixture();pending(f);r=await core.retireExistingAccount(adapter(f.db,{step(i){if(i===6)throw Error('injected failure')}}),f.operation);eq('constraint/fault rollback restores active',f.db.prepare('SELECT state FROM account_generations WHERE account_id=?').get(A).state,'active');eq('rollback restores site session',f.db.prepare('SELECT session_version FROM site_users WHERE discord_id=?').get(A).session_version,7);eq('rollback no partial job',count(f.db,'privacy_erasure_jobs'),0);eq('thrown failure does not assert rollback',r.reason,'commit_outcome_unknown');f.db.close();
f=fixture();pending(f);r=await core.retireExistingAccount(adapter(f.db,{after(){throw Error('lost response after commit')}}),f.operation);eq('lost retirement reply resolved from durable status',r.status,'held');eq('lost reply one retirement',f.db.prepare('SELECT revision FROM account_generations WHERE account_id=?').get(A).revision,1);r=await erase.runErasureSlice(adapter(f.db,{after(){throw Error('lost progress reply')}}),core.reference(f.operation));ok('lost progress reply resolved without false rollback',r.reason!=='commit_outcome_unknown');eq('lost progress only once',f.db.prepare("SELECT purged_rows FROM privacy_erasure_progress WHERE store_key='pending'").get().purged_rows,1);f.db.close();
f=fixture();pending(f);let reads=0;r=await core.retireExistingAccount(adapter(f.db,{after(){throw Error('lost reply')},read(sql){if(++reads>1)throw Error('readback unavailable')}}),f.operation);eq('lost commit and unreadable status held unknown',r.reason,'commit_outcome_unknown');eq('unknown reply may have committed',count(f.db,'privacy_erasure_jobs'),1);f.db.close();
f=fixture();pending(f,A,2);await core.retireExistingAccount(adapter(f.db),f.operation);r=await erase.runErasureSlice(adapter(f.db,{before(){f.db.prepare("UPDATE privacy_erasure_progress SET revision=revision+1 WHERE store_key='pending'").run()}}),core.reference(f.operation));eq('stale progress CAS checked rollback held',r.reason,'commit_outcome_unknown');eq('zero claim cannot delete dependents',count(f.db,'pending'),2);f.db.close();
for(const [name,sql] of [['restore','UPDATE generation_control SET restore_hold=1'],['epoch',"UPDATE generation_control SET epoch='99999999999999999999999999999999'"],['new generation',"UPDATE account_generations SET generation='99999999999999999999999999999999'"],['catalog mutation',"UPDATE privacy_erasure_jobs SET catalog_digest='9999999999999999999999999999999999999999999999999999999999999999'"],['new table','CREATE TABLE new_private_data(id TEXT)']]){f=fixture();pending(f);await core.retireExistingAccount(adapter(f.db),f.operation);f.db.exec(sql);r=await erase.runErasureSlice(adapter(f.db),core.reference(f.operation));ok(name+' suspends progress',r.status==='held');eq(name+' no purge',count(f.db,'pending'),1);f.db.close();}
f=fixture();pending(f);await core.retireExistingAccount(adapter(f.db),f.operation);f.db.prepare('UPDATE privacy_erasure_jobs SET expires_at=created_at-99,created_at=created_at-100 WHERE operation_id=?').run(f.operation.operationId);r=await erase.runErasureSlice(adapter(f.db),core.reference(f.operation));eq('expired job holds',r.reason,'operation_expired_policy_pending');eq('expired job no purge',count(f.db,'pending'),1);f.db.close();
f=fixture();pending(f);await core.retireExistingAccount(adapter(f.db),f.operation);f.db.prepare('UPDATE pending SET id=-1').run();r=await erase.runErasureSlice(adapter(f.db),core.reference(f.operation));eq('negative legacy cursor held',r.reason,'unsupported_legacy_rowid');eq('negative legacy row untouched',count(f.db,'pending'),1);f.db.close();
f=fixture();let getter=0;assert.throws(()=>core.snapshotOperation({...f.operation,get subject(){getter++;return A;}}));eq('accessors refused without execution',getter,0);const snap=core.snapshotOperation(f.operation);f.operation.subject=B;eq('snapshot detached subject',snap.subject,A);ok('snapshot frozen',Object.isFrozen(snap));f.db.close();
f=fixture();pending(f);f.db.exec("CREATE TRIGGER reject_outbox BEFORE INSERT ON privacy_external_outbox BEGIN SELECT RAISE(ABORT,'constraint fixture'); END");r=await core.retireExistingAccount(adapter(f.db),f.operation);eq('actual SQLite abort rolls back retirement',f.db.prepare('SELECT state FROM account_generations WHERE account_id=?').get(A).state,'active');eq('actual abort leaves no job',count(f.db,'privacy_erasure_jobs'),0);eq('actual abort preserves pending proof',f.db.prepare('SELECT consumed_at FROM pending').get().consumed_at,null);f.db.close();
f=fixture();pending(f);const mutable={...f.operation},wanted=core.reference(f.operation);const promise=core.retireExistingAccount(adapter(f.db),mutable);mutable.subject=B;await promise;eq('mutation across await cannot target another subject',f.db.prepare('SELECT state FROM account_generations WHERE account_id=?').get(B).state,'active');eq('original captured subject retired',f.db.prepare('SELECT state FROM account_generations WHERE account_id=?').get(A).state,'retiring');f.db.close();
f=fixture();pending(f,A,100);await core.retireExistingAccount(adapter(f.db),f.operation);r=await erase.runErasureSlice(adapter(f.db,{before(){pending(f,A,100)}}),core.reference(f.operation));eq('delete bounded to100 selected rows despite an unadopted writer',count(f.db,'pending'),100);ok('later inserts not falsely all-store erased',r.allStoresErased===false);f.db.close();
f=fixture();f.db.exec('DELETE FROM generation_control');assert.throws(()=>f.db.prepare('INSERT INTO generation_control VALUES(NULL,?,0,0)').run(E));checks++;eq('NULL singleton cannot mint restore control',count(f.db,'generation_control'),0);assert.throws(()=>f.db.prepare("INSERT INTO account_generations VALUES(NULL,?,'active',0,'reviewed-legacy',?)").run(G,D));checks++;eq('NULL account cannot mint provenance',count(f.db,'account_generations'),2);f.db.close();
f=fixture();await core.retireExistingAccount(adapter(f.db),f.operation);assert.throws(()=>f.db.exec('INSERT INTO privacy_erasure_jobs SELECT NULL,subject,account_generation,epoch,request_digest,catalog_version,catalog_digest,cleanup_generation,claim_nonce,created_at,expires_at,control_revision,original_session_version,completion_admitted FROM privacy_erasure_jobs'));checks++;eq('NULL operation cannot create unreachable job',count(f.db,'privacy_erasure_jobs'),1);assert.throws(()=>f.db.exec("INSERT INTO account_purpose_generations SELECT NULL,account_generation,purpose,generation,revision,updated_at FROM account_purpose_generations LIMIT 1"));checks++;assert.throws(()=>f.db.exec('INSERT INTO privacy_erasure_progress SELECT NULL,ordinal,store_key,state,held_reason,cursor,high_water,revision,claim_nonce,purged_rows FROM privacy_erasure_progress LIMIT 1'));checks++;assert.throws(()=>f.db.exec('INSERT INTO privacy_external_outbox SELECT NULL,effect_key,subject,account_generation,epoch,state,held_reason,expires_at FROM privacy_external_outbox'));checks++;eq('NULL identifiers leave progress and outbox unchanged',[count(f.db,'privacy_erasure_progress'),count(f.db,'privacy_external_outbox')],[54,1]);f.db.close();
for(const [name,change]of [['catalog',x=>x.db.prepare("UPDATE privacy_erasure_jobs SET catalog_digest=?").run('9'.repeat(64))],['schema',x=>x.db.exec('CREATE TABLE newly_unclassified_store(id TEXT)')]]){f=fixture();pending(f,A,2);await core.retireExistingAccount(adapter(f.db),f.operation);r=await erase.runErasureSlice(adapter(f.db,{before(){change(f)}}),core.reference(f.operation));eq(name+' change after selection does not purge',count(f.db,'pending'),2);eq(name+' change after selection cannot advance cursor',f.db.prepare("SELECT revision,cursor,purged_rows FROM privacy_erasure_progress WHERE store_key='pending'").get(),{revision:0,cursor:0,purged_rows:0});eq(name+' zero consuming claim checked rollback held',r.reason,'commit_outcome_unknown');ok(name+' changed metadata does not claim full erasure',r.allStoresErased===false);f.db.close();}
for(const table of ['newly_unclassified_store','sqliteX_private']){f=fixture();pending(f);r=await core.retireExistingAccount(adapter(f.db,{before(){f.db.exec('CREATE TABLE '+table+'(id TEXT)')}}),f.operation);eq(table+' in-flight schema cannot mint job',count(f.db,'privacy_erasure_jobs'),0);eq(table+' in-flight schema cannot retire subject',f.db.prepare('SELECT state FROM account_generations WHERE account_id=?').get(A).state,'active');eq(table+' in-flight schema preserves session',f.db.prepare('SELECT session_version FROM site_users WHERE discord_id=?').get(A).session_version,7);f.db.close();}
f=fixture();pending(f);r=await core.retireExistingAccount(adapter(f.db,{step(i){if(i===1)f.db.prepare("UPDATE privacy_erasure_jobs SET catalog_digest=?").run('9'.repeat(64));}}),f.operation);eq('catalog altered during retirement cannot change account',f.db.prepare('SELECT state FROM account_generations WHERE account_id=?').get(A).state,'active');eq('catalog altered during retirement cannot emit external intent',count(f.db,'privacy_external_outbox'),0);eq('catalog altered during retirement preserves session',f.db.prepare('SELECT session_version FROM site_users WHERE discord_id=?').get(A).session_version,7);f.db.close();

f=fixture();pending(f,A,250);let retirementCounts=[];r=await core.retireExistingAccount(adapter(f.db,{after(){retirementCounts=f.db.prepare('SELECT changes() AS n').get().n;}}),f.operation);
eq('fresh retirement increments global control exactly once',f.db.prepare('SELECT revision FROM generation_control').get().revision,1);
eq('fresh retirement completion admits exact own job',f.db.prepare('SELECT completion_admitted,original_session_version,control_revision FROM privacy_erasure_jobs').get(),{completion_admitted:1,original_session_version:7,control_revision:0});
eq('retirement immediate pending cancellation bounded100',count(f.db,'pending','consumed_source=?',['lifecycle-retiring']),100);
eq('retirement account immediately not in server for qualified readers',f.db.prepare('SELECT in_server FROM site_users WHERE discord_id=?').get(A).in_server,0);
await core.retireExistingAccount(adapter(f.db),f.operation);eq('same operation does not advance global twice',f.db.prepare('SELECT revision FROM generation_control').get().revision,1);f.db.close();
f=fixture();pending(f);const oldRandom=contracts.randomGeneration,cleanup='a'.repeat(32),nonce='b'.repeat(32);let randomCalls=0;contracts.randomGeneration=()=>randomCalls++%2===0?cleanup:nonce;
const catHash=await catalog.catalogDigest();f.db.prepare(`INSERT INTO privacy_erasure_jobs(operation_id,subject,account_generation,epoch,request_digest,catalog_version,catalog_digest,cleanup_generation,claim_nonce,created_at,expires_at,control_revision,original_session_version,completion_admitted) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,0)`).run(f.operation.operationId,A,G,E,f.operation.requestDigest,catalog.CATALOG_VERSION,catHash,cleanup,nonce,f.now,f.operation.expiresAt,0,7);
f.db.exec("UPDATE account_generations SET state='retiring',revision=1; UPDATE generation_control SET revision=1");
try{r=await core.retireExistingAccount(adapter(f.db),f.operation);}finally{contracts.randomGeneration=oldRandom;}
eq('preexisting incomplete job cannot represent fresh INSERT',f.db.prepare('SELECT completion_admitted FROM privacy_erasure_jobs').get().completion_admitted,0);
eq('refused initial claim cannot rotate cleanup purpose',f.db.prepare("SELECT generation FROM account_purpose_generations WHERE account_id=? AND purpose='erasure'").get(A).generation,P);
eq('refused initial claim cannot increment session',f.db.prepare('SELECT session_version FROM site_users WHERE discord_id=?').get(A).session_version,7);
eq('refused initial claim emits no progress or outbox',[count(f.db,'privacy_erasure_progress'),count(f.db,'privacy_external_outbox')],[0,0]);
eq('refused initial claim global unchanged',f.db.prepare('SELECT revision FROM generation_control').get().revision,1);f.db.close();
// Claude N2 (2026-10-08): a real zero-change UPDATE sets SQLite changes() to0;
// it adds no TEMP object and cannot impersonate a schema refusal. Every point asserts an outcome.
for(let point=0;point<14;point++){
 f=fixture();pending(f);let replaced=0;
 const fixturePort=adapter(f.db,{omit(i){if(i===point){replaced++;return true;}return false;}});
 r=await core.retireExistingAccount(fixturePort,f.operation);
 eq('genuine zero-change omission reached point'+point,replaced,1);
 eq('omission point'+point+' leaves temp schema empty',f.db.prepare('SELECT count(*) AS n FROM temp.sqlite_master').get().n,0);
 ok('omission point'+point+' never claims full erasure/authority',r.allStoresErased===false&&r.authorityAdopted===false&&r.externalEffects==='held');
 if(point===0||[1,2,3,4,5,6,10,11,12].includes(point)){
  eq('critical omission'+point+' account remains active',f.db.prepare('SELECT state FROM account_generations WHERE account_id=?').get(A).state,'active');
  eq('critical omission'+point+' global unchanged',f.db.prepare('SELECT revision FROM generation_control').get().revision,0);
  eq('critical omission'+point+' session unchanged',f.db.prepare('SELECT session_version FROM site_users WHERE discord_id=?').get(A).session_version,7);
  eq('critical omission'+point+' no job/progress/outbox',[count(f.db,'privacy_erasure_jobs'),count(f.db,'privacy_erasure_progress'),count(f.db,'privacy_external_outbox')],[0,0,0]);
  eq('critical omission'+point+' pending proof remains',f.db.prepare('SELECT consumed_at FROM pending').get().consumed_at,null);
 }else if(point===13){
  eq('omitted guard with exact completed job has only held status',r.status,'held');
  eq('omitted guard readback confirms existing exact terminal job',f.db.prepare('SELECT completion_admitted FROM privacy_erasure_jobs').get().completion_admitted,1);
  eq('omitted guard never asserts rollback',f.db.prepare('SELECT state FROM account_generations WHERE account_id=?').get(A).state,'retiring');
 }else{
  eq('bounded cancellation omission'+point+' still only held local work',r.status,'held');
  eq('bounded cancellation omission'+point+' exact final job admitted',f.db.prepare('SELECT completion_admitted FROM privacy_erasure_jobs').get().completion_admitted,1);
  if(point===7)eq('omitted pending cancellation remains for local cleanup',f.db.prepare('SELECT consumed_at FROM pending').get().consumed_at,null);
  if(point===8)eq('omitted queue cancellation remains queued',f.db.prepare('SELECT status FROM invite_queue').get().status,'queued');
  if(point===9)eq('omitted roster cancellation remains present',count(f.db,'roster_effects'),1);
 }
 f.db.close();
}
for(const [name,change,expected]of [['schema',x=>x.db.exec('CREATE TABLE status_after_initial_read(id TEXT)'),'unclassified_schema'],['catalog',x=>x.db.prepare('UPDATE privacy_erasure_jobs SET catalog_digest=?').run('9'.repeat(64)),'catalog_changed'],['restore',x=>x.db.prepare('UPDATE generation_control SET restore_hold=1').run(),'generation_or_restore_changed']]){
 f=fixture();pending(f);await core.retireExistingAccount(adapter(f.db),f.operation);let reached=0;
 r=await core.readErasureStatus(adapter(f.db,{read(sql){if(sql.includes('AS pendingPlans')){reached++;change(f);}}}),core.reference(f.operation));
 eq(name+' mutation occurs after initial profile read',reached,1);eq(name+' current status statement refuses',r.reason,expected);eq(name+' refused status returns no progress counts',r.pendingPlans+r.heldPlans+r.finishedPlans,0);f.db.close();
}
for(const offset of [-1,0,1]){
 f=fixture();pending(f);await core.retireExistingAccount(adapter(f.db),f.operation);let reached=0,clockReads=0;
 r=await core.readErasureStatus(adapter(f.db,{read(sql){if(sql.includes('AS pendingPlans')){reached++;f.db.function('strftime',(format,value)=>{assert.equal(format,'%s');assert.equal(value,'now');clockReads++;return String(f.operation.expiresAt+offset);});}}}),core.reference(f.operation));
 eq('status original expiry clock offset'+offset+' reached consuming SELECT',reached,1);
 ok('status original expiry offset'+offset+' consumes actual installed DB clock',clockReads>0);
 eq('status original strict expiry offset'+offset,r.reason,offset<0?'local_work_pending':'operation_expired_policy_pending');f.db.close();
}
// V3 original absolute deadline: expiry at advance/final guard aborts the WHOLE
// actual transaction. V2's committed delete/progress gap is preserved privately.
for(const point of [0,1,2,3])for(const offset of [-1,0,1]){
 f=fixture();pending(f,A,3);await core.retireExistingAccount(adapter(f.db),f.operation);let reached=0,clockReads=0;
 r=await erase.runErasureSlice(adapter(f.db,{step(i){if(i===point){reached++;f.db.function('strftime',(format,value)=>{assert.equal(format,'%s');assert.equal(value,'now');clockReads++;return String(f.operation.expiresAt+offset);});}}}),core.reference(f.operation));
 eq('slice deadline point'+point+' offset'+offset+' reached',reached,1);
 ok('slice deadline point'+point+' offset'+offset+' consumes installed two-argument clock',clockReads>0);
 eq('slice deadline point'+point+' offset'+offset+' exact pending outcome',count(f.db,'pending'),offset<0?0:3);
 const p=f.db.prepare("SELECT revision,cursor,purged_rows,state FROM privacy_erasure_progress WHERE store_key='pending'").get();
 eq('slice deadline point'+point+' offset'+offset+' records all or rolls back',offset<0?{revision:p.revision,purged_rows:p.purged_rows,state:p.state}:p,offset<0?{revision:1,purged_rows:3,state:'done'}:{revision:0,cursor:0,purged_rows:0,state:'pending'});
 ok('slice deadline point'+point+' offset'+offset+' never claims full/authority',r.allStoresErased===false&&r.authorityAdopted===false&&r.attempts<=24);f.db.close();
}
for(const offset of [-1,0,1]){
 f=fixture();pending(f,A,3);let reached=0,clockReads=0;r=await core.retireExistingAccount(adapter(f.db,{step(i){if(i===13){reached++;f.db.function('strftime',(format,value)=>{assert.equal(format,'%s');assert.equal(value,'now');clockReads++;return String(f.operation.expiresAt+offset);});}}}),f.operation);
 eq('terminal original deadline offset'+offset+' final guard reached',reached,1);ok('terminal original deadline offset'+offset+' consumes installed two-argument clock',clockReads>0);eq('terminal original deadline offset'+offset+' job commit or rollback',count(f.db,'privacy_erasure_jobs'),offset<0?1:0);eq('terminal original deadline offset'+offset+' session exact',f.db.prepare('SELECT session_version FROM site_users WHERE discord_id=?').get(A).session_version,offset<0?8:7);eq('terminal original deadline offset'+offset+' original pending retained',count(f.db,'pending'),3);ok('terminal original deadline offset'+offset+' remains dormant',r.allStoresErased===false&&r.authorityAdopted===false);f.db.close();
}
for(const [name,sql]of [['nonce',"UPDATE privacy_erasure_progress SET claim_nonce='aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' WHERE store_key='pending'"],['revision',"UPDATE privacy_erasure_progress SET revision=2 WHERE store_key='pending'"],['cursor',"UPDATE privacy_erasure_progress SET cursor=1 WHERE store_key='pending'"],['state',"UPDATE privacy_erasure_progress SET state='held' WHERE store_key='pending'"],['missing',"DELETE FROM privacy_erasure_progress WHERE store_key='pending'"],['job nonce',"UPDATE privacy_erasure_jobs SET claim_nonce='aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'"],['cleanup',"UPDATE privacy_erasure_jobs SET cleanup_generation='aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'"],['deadline','UPDATE privacy_erasure_jobs SET expires_at=expires_at-1'],['control revision','UPDATE privacy_erasure_jobs SET control_revision=control_revision+1'],['original session','UPDATE privacy_erasure_jobs SET original_session_version=original_session_version+1']]){
 f=fixture();pending(f,A,1);await core.retireExistingAccount(adapter(f.db),f.operation);let reached=0;r=await erase.runErasureSlice(adapter(f.db,{step(i){if(i===2){reached++;f.db.exec(sql);}}}),core.reference(f.operation));
 eq('advance wrong '+name+' reached after DELETE changes1',reached,1);eq('advance wrong '+name+' rolls DELETE back',count(f.db,'pending'),1);eq('advance wrong '+name+' original cursor/count/revision restored',f.db.prepare("SELECT revision,cursor,purged_rows FROM privacy_erasure_progress WHERE store_key='pending'").get(),{revision:0,cursor:0,purged_rows:0});ok('advance wrong '+name+' remains held',r.status==='held'&&r.allStoresErased===false);f.db.close();
}
for(const expired of [false,true]){
 f=fixture();pending(f,A,3);await core.retireExistingAccount(adapter(f.db),f.operation);f.db.exec('UPDATE privacy_erasure_jobs SET completion_admitted=0');if(expired)f.db.function('strftime',(format,value)=>{assert.equal(format,'%s');assert.equal(value,'now');return String(f.operation.expiresAt);});
 const want=expired?'operation_incomplete_completion_expired':'operation_incomplete_completion';r=await core.readErasureStatus(adapter(f.db),core.reference(f.operation));eq('existing incomplete '+expired+' explicit diagnostic',r.reason,want);eq('existing incomplete '+expired+' no progress disclosure',r.pendingPlans+r.heldPlans+r.finishedPlans,0);r=await erase.runErasureSlice(adapter(f.db),core.reference(f.operation));eq('existing incomplete '+expired+' cannot purge',count(f.db,'pending'),3);eq('existing incomplete '+expired+' slice stays diagnostic',r.reason,want);await core.retireExistingAccount(adapter(f.db),f.operation);eq('existing incomplete '+expired+' no automatic completion',f.db.prepare('SELECT completion_admitted FROM privacy_erasure_jobs').get().completion_admitted,0);eq('existing incomplete '+expired+' no extra session/control rotation',[f.db.prepare('SELECT session_version FROM site_users WHERE discord_id=?').get(A).session_version,f.db.prepare('SELECT revision FROM generation_control').get().revision],[8,1]);f.db.close();
}
// Strict native shape cases are actual consuming calls; readable malformed reply
// after COMMIT can only resolve through the exact own post-state readback.
const malformed=[['false success',out=>{out.at(-1).success=false;return out;}],['wrong checked',out=>{out.at(-1).results=[{checked:0}];return out;}],['string checked',out=>{out.at(-1).results=[{checked:'1'}];return out;}],['null results',out=>{out.at(-1).results=null;return out;}],['extra row',out=>{out.at(-1).results=[{checked:1},{checked:1}];return out;}],['string changes',out=>{out[0].meta.changes='1';return out;}],['boolean changes',out=>{out[0].meta.changes=true;return out;}],['nonenumerable changes',out=>{Object.defineProperty(out[0].meta,'changes',{value:1,enumerable:false});return out;}],['missing entry',out=>out.slice(0,-1)],['inherited success',out=>{out[out.length-1]=Object.assign(Object.create({success:true}),{meta:{changes:0},results:[{checked:1}]});return out;}]];
for(const [name,mutate]of malformed)for(const committed of [false,true]){
 f=fixture();pending(f,A,3);await core.retireExistingAccount(adapter(f.db),f.operation);let intercepted=0;
 r=await erase.runErasureSlice(adapter(f.db,{skipBatch:!committed,reply(out){intercepted++;const shape=committed?out:[{success:true,meta:{changes:1},results:[]},{success:true,meta:{changes:3},results:[]},{success:true,meta:{changes:1},results:[]},{success:true,meta:{changes:0},results:[{checked:1}]}];return mutate(shape);}}),core.reference(f.operation));
 eq('malformed '+name+' committed'+committed+' consumes actual path',intercepted,1);eq('malformed '+name+' committed'+committed+' exact durable rows',count(f.db,'pending'),committed?0:3);eq('malformed '+name+' committed'+committed+' exact progress',f.db.prepare("SELECT revision,purged_rows FROM privacy_erasure_progress WHERE store_key='pending'").get(),committed?{revision:1,purged_rows:3}:{revision:0,purged_rows:0});ok('malformed '+name+' committed'+committed+' held/no false authority',r.status==='held'&&r.allStoresErased===false&&r.authorityAdopted===false&&r.attempts<=24);f.db.close();
}
for(const [name,sql]of [['nonce',"UPDATE privacy_erasure_progress SET claim_nonce='aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' WHERE store_key='pending'"],['cursor',"UPDATE privacy_erasure_progress SET cursor=0 WHERE store_key='pending'"],['state',"UPDATE privacy_erasure_progress SET state='pending' WHERE store_key='pending'"],['job nonce',"UPDATE privacy_erasure_jobs SET claim_nonce='aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'"],['deadline','UPDATE privacy_erasure_jobs SET expires_at=expires_at-1']]){
 f=fixture();pending(f,A,3);await core.retireExistingAccount(adapter(f.db),f.operation);r=await erase.runErasureSlice(adapter(f.db,{after(){f.db.exec(sql);throw Error('lost reply after actual COMMIT and malformed restored row');}}),core.reference(f.operation));eq('lost reply altered '+name+' never confirms advancement',r.reason,'commit_outcome_unknown');eq('lost reply altered '+name+' does not infer rollback',count(f.db,'pending'),0);eq('lost reply altered '+name+' returns no progress counts',r.pendingPlans+r.heldPlans+r.finishedPlans,0);f.db.close();
}
f=fixture();pending(f,A,3);await core.retireExistingAccount(adapter(f.db),f.operation);let getters=0;r=await erase.runErasureSlice(adapter(f.db,{reply(out){Object.defineProperty(out.at(-1),'results',{get(){getters++;throw Error('getter');},enumerable:true});return out;}}),core.reference(f.operation));eq('native guard accessor never invoked',getters,0);eq('native guard accessor may resolve exact durable commit only',f.db.prepare("SELECT purged_rows FROM privacy_erasure_progress WHERE store_key='pending'").get().purged_rows,3);ok('native guard accessor has no full success',r.allStoresErased===false);f.db.close();
for(const malformed of [2,'1',null,{},Infinity]){
 f=fixture();await core.retireExistingAccount(adapter(f.db),f.operation);r=await core.readErasureStatus(adapter(f.db,{readReply(sql,row){return sql.includes('AS pendingPlans')?{...row,ownCommitCurrent:malformed}:row;}}),core.reference(f.operation));eq('finite status rejects malformed own confirmation '+String(malformed),r.reason,'readback_unavailable');eq('finite status malformed count withheld '+String(malformed),r.pendingPlans+r.heldPlans+r.finishedPlans,0);f.db.close();
}
// Claude LCD2N2: malformed projected native data must not become a fabricated
// finished/pending diagnosis. The actual SQLite SELECT runs before this explicit
// test-only malformed-reply injection; no returned controls replace SQL.
for(const [name,change]of [['null DB time',row=>({...row,at:null})],['string DB time',row=>({...row,at:String(row.at)})],['string original expiry',row=>({...row,expires_at:String(row.expires_at)})],['negative plan count',row=>({...row,pendingPlans:-1,heldPlans:34,finishedPlans:19})],['fractional plan counts',row=>({...row,pendingPlans:0.5,heldPlans:32.5,finishedPlans:19})]]){
 f=fixture();await core.retireExistingAccount(adapter(f.db),f.operation);let reached=0;r=await core.readErasureStatus(adapter(f.db,{readReply(sql,row){if(!sql.includes('AS pendingPlans'))return row;reached++;return change(row);}}),core.reference(f.operation));eq('native malformed status '+name+' actual consuming SELECT reached',reached,1);eq('native malformed status '+name+' held',r.reason,'readback_unavailable');eq('native malformed status '+name+' no invented counts',r.pendingPlans+r.heldPlans+r.finishedPlans,0);ok('native malformed status '+name+' no false finished',r.status==='held'&&r.localPlansFinished===false&&r.allStoresErased===false);f.db.close();
}
const budget={used:23},bounded=core.boundedDatabase({prepare(){return {bind(){return this},run:async()=>({meta:{}}),first:async()=>null,all:async()=>({results:[]})}},batch:async()=>[]},budget);await bounded.prepare('one').first();assert.throws(()=>bounded.prepare('two').first());eq('budget refuses25th statement',budget.used,24);
console.log(JSON.stringify({suite:'privacy-lifecycle-foundation',passed:checks,total:checks,sql:'real in-memory SQLite; actual source and schema',providerCalls:0,composition:'closed'}));
})().catch(e=>{console.error(e);process.exitCode=1;});
