// Real entry + explicit native installation; memory SQLite and synthetic vars only.
const fs=require('node:fs'),path=require('node:path'),cryptoNode=require('node:crypto'),ts=require('typescript'),{DatabaseSync}=require('node:sqlite');
const root=path.join(__dirname,'..'),pins=new Map();
if(!globalThis.crypto)Object.defineProperty(globalThis,'crypto',{value:cryptoNode.webcrypto});
let checks=0,passed=0,providerCalls=0;const check=(name,value,data)=>{checks++;if(value)passed++;else console.error('FAIL',name,data??'');};
globalThis.fetch=async()=>{providerCalls++;throw Error('no provider permitted in entry/installation fixture');};
function graph(){const cache={};const load=name=>{if(cache[name])return cache[name].exports;const f=path.join(root,'src',name.replace('./','')+'.ts'),b=fs.readFileSync(f);pins.set(f,cryptoNode.createHash('sha256').update(b).digest('hex'));const m={exports:{}};cache[name]=m;new Function('require','module','exports',ts.transpileModule(b.toString('utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(p=>load(p),m,m.exports);return m.exports;};load('./index');return load;}
function fixture(layout='canonical'){
 const L=graph(),a=L('./privacy-write-admission'),m=L('./privacy-write-admission-catalogue'),db=new DatabaseSync(':memory:'),manifest=JSON.parse(layout==='canonical'?m.ADMISSION_EXPECTED_JSON:m.ADMISSION_PHYSICAL_EXPECTED_JSON);
 for(const t of manifest.tables)db.exec(t.sql);for(const i of manifest.indexes)db.exec(i.sql);db.exec(manifest.slotSQL);db.prepare(`INSERT INTO ${m.ADMISSION_CONTROL_TABLE} VALUES(1,?,0,'','',0,0)`).run(m.ADMISSION_PROTOCOL);
 db.prepare("INSERT INTO site_settings(key,value,updated_at)VALUES('auditTypedNames','115',1)").run();
 const trace={statements:0,batches:[],failAt:null,loseReply:false};
 const execute=(sql,values)=>{const s=db.prepare(sql);if(/^\s*(SELECT|WITH)\b/i.test(sql)||/\bRETURNING\b/i.test(sql))return {success:true,results:s.all(...values),meta:{changes:Number(db.prepare('SELECT changes() n').get().n)}};const r=s.run(...values);return {success:true,results:[],meta:{changes:Number(r.changes),last_row_id:Number(r.lastInsertRowid)}};};
 const statement=(sql,values=[])=>({sql,values,bind(...v){return statement(sql,v);},async first(column){trace.statements++;const r=execute(sql,values).results[0]??null;return column&&r?r[column]:r;},async all(){trace.statements++;return execute(sql,values);},async run(){trace.statements++;return execute(sql,values);},async raw(){trace.statements++;return db.prepare(sql).all(...values).map(Object.values);}});
 const native={prepare:statement,async batch(ss){trace.statements+=ss.length;trace.batches.push(ss.map(s=>s.sql));db.exec('BEGIN');let out;try{out=ss.map((s,i)=>{if(i===trace.failAt)throw Error('fixture installation fault');return execute(s.sql,s.values);});db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}if(trace.loseReply)throw Error('committed installation response lost');return out;}};
 const env={DB:native,PUBLIC_BASE_URL:'https://bot.example',SITE_HOST:'guild.example',COOKIE_SECRET:'synthetic-cookie-fixture',ASSETS:{fetch:async()=>new Response('synthetic-static')},PRIVACY_ERASURE_ENABLED:'false',PRIVACY_RETENTION_ENABLED:'false',QR_PHASE1_ENABLED:'false'};
 const neutral=()=>{const r=db.prepare('SELECT * FROM privacy_write_admission').get();return r?.active===0&&r.nonce===''&&r.purpose==='';};
 const schemaSnapshot=()=>JSON.stringify(db.prepare("SELECT type,name,sql FROM sqlite_master WHERE name NOT LIKE 'sqlite_%' ORDER BY type,name").all());
 return {L,a,m,db,native,trace,env,neutral,schemaSnapshot};
}
async function refusal(name,fn){let e;try{await fn();}catch(error){e=error;}check(name,!!e,String(e));}
async function fetchEntry(f,url='/health',flag){f.env.PRIVACY_WRITE_ADMISSION_ENABLED=arguments.length<3?'true':flag;const pending=[];const old=console.error;console.error=()=>{};try{return await f.L('./index').default.fetch(new Request('https://bot.example'+url),f.env,{waitUntil:p=>pending.push(p)});}finally{console.error=old;await Promise.allSettled(pending);}}
(async()=>{
 for(const layout of['canonical','recorded-live-20261010']){
  const f=fixture(layout);f.env.PRIVACY_WRITE_ADMISSION_LAYOUT=layout;
  const plan=await f.a.installCurrentPrivacyWriteAdmission(f.native,layout);check(layout+' explicit installer exactly202/67/198',plan.statements===202&&plan.tables===67&&plan.triggers===198&&f.trace.statements===202,plan);
  check(layout+' native actual exact198 triggers installed',f.db.prepare("SELECT COUNT(*) n FROM sqlite_master WHERE type='trigger'").get().n===198&&f.neutral());
  const bound=f.a.createPrivacyWriteAdmissionDatabase(f.native,'writer',layout);check(layout+' exact whole layout recognized',await f.a.admissionCatalogueCurrent(bound));
  const before=f.trace.statements,r=await fetchEntry(f);check(layout+' real index ON plain native health positive',r.status===200&&(await r.json()).d1==='ok'&&f.trace.statements-before===2);
  const site=await f.L('./index').default.fetch(new Request('https://guild.example/'),f.env,{waitUntil(){}});check(layout+' real anonymous site BOOT serves through installed entry',site.status===200&&(await site.text()).includes('id="boot"'));
  const calls=f.trace.batches.length;await refusal(layout+' second installation refused; no automatic reinstall',()=>f.a.installCurrentPrivacyWriteAdmission(f.native,layout));check(layout+' attempted reinstall preserves exact catalogue',await f.a.admissionCatalogueCurrent(bound)&&f.trace.batches.length===calls+1);
  await refusal(layout+' installed but selector OFF refuses unwrapped ordinary audit writer',()=>f.native.prepare("INSERT INTO audit(ts,actor,action,subject,details)VALUES(1,'system','test',NULL,'{}')").run());check(layout+' old writer produces no rows',f.db.prepare('SELECT COUNT(*) n FROM audit').get().n===0&&f.neutral());
  f.db.close();
 }
 for(const slot of[0,2,3,100,201]){const f=fixture(),before=f.schemaSnapshot();f.trace.failAt=slot;await refusal('installer fault'+slot+' rolls back native batch',()=>f.a.installCurrentPrivacyWriteAdmission(f.native));check('installer fault'+slot+' no trigger/slot/business drift',f.schemaSnapshot()===before&&f.neutral()&&f.trace.batches.length===1);f.db.close();}
 for(const [name,mutate]of[
  ['extra-store',f=>f.db.exec('CREATE TABLE ordinary_extra(id TEXT)')],['extra-index',f=>f.db.exec('CREATE INDEX ordinary_extra ON members(discord_id)')],
  ['extra-trigger',f=>f.db.exec('CREATE TRIGGER ordinary_extra AFTER INSERT ON members BEGIN SELECT 1;END')],
  ['changed-physical-DDL',f=>f.db.exec('ALTER TABLE members RENAME COLUMN activity_at TO different_field')],
  ['unapplied-legacy-rewrite',f=>f.db.prepare("INSERT INTO audit(ts,actor,action,details)VALUES(1,'system','site.settings','malformed')").run()],
 ]){const f=fixture();mutate(f);const before=f.schemaSnapshot();await refusal('installer refuses '+name,()=>f.a.installCurrentPrivacyWriteAdmission(f.native));check(name+' preserves actual schema and neutral state',f.schemaSnapshot()===before&&f.neutral());f.db.close();}
 const mixed=fixture('recorded-live-20261010');await refusal('canonical installer refuses whole recorded layout',()=>mixed.a.installCurrentPrivacyWriteAdmission(mixed.native,'canonical'));check('mismatched layout creates no triggers',mixed.db.prepare("SELECT COUNT(*) n FROM sqlite_master WHERE type='trigger'").get().n===0);mixed.db.close();
 const hybrid=fixture(),canonical=JSON.parse(hybrid.m.ADMISSION_EXPECTED_JSON),historical=JSON.parse(hybrid.m.ADMISSION_PHYSICAL_EXPECTED_JSON),different=historical.tables.find(t=>canonical.tables.find(c=>c.name===t.name).sql!==t.sql);check('two reviewed layouts have actual different table text',!!different);hybrid.db.exec('PRAGMA writable_schema=ON');hybrid.db.prepare("UPDATE sqlite_master SET sql=? WHERE type='table' AND name=?").run(different.sql,different.name);hybrid.db.exec('PRAGMA writable_schema=OFF');await refusal('mixed whole layout refuses canonical mode',()=>hybrid.a.installCurrentPrivacyWriteAdmission(hybrid.native));await refusal('mixed whole layout refuses recorded mode',()=>hybrid.a.installCurrentPrivacyWriteAdmission(hybrid.native,'recorded-live-20261010'));hybrid.db.close();
 const lost=fixture();lost.trace.loseReply=true;await refusal('lost installed commit reply is uncertain, no retry',()=>lost.a.installCurrentPrivacyWriteAdmission(lost.native));check('actual lost commit retains198 triggers/neutral once',lost.db.prepare("SELECT COUNT(*) n FROM sqlite_master WHERE type='trigger'").get().n===198&&lost.neutral()&&lost.trace.batches.length===1);lost.trace.loseReply=false;check('read-only installation proof can recognize preserved exact commit',await lost.a.admissionCatalogueCurrent(lost.a.createPrivacyWriteAdmissionDatabase(lost.native)));lost.db.close();
 for(const value of[undefined,'false','TRUE']){const f=fixture(),r=await fetchEntry(f,'/health',value);check('absent/nontrue flag keeps ordinary health '+String(value),r.status===200&&(await r.json()).d1==='ok'&&f.db.prepare("SELECT COUNT(*) n FROM sqlite_master WHERE type='trigger'").get().n===0);check('OFF canonical67 own-copy catalogue recognizes exact new control',await f.L('./privacy-business-catalog').servingPrivacyCatalogCurrent(f.env));f.db.close();}
 for(const state of['neutral-only','missing-control','wrong-layout','extra-store']){const f=fixture();if(state==='missing-control')f.db.exec('DROP TABLE privacy_write_admission');if(state==='wrong-layout')f.env.PRIVACY_WRITE_ADMISSION_LAYOUT='unknown';if(state==='extra-store')f.db.exec('CREATE TABLE ordinary_extra(id TEXT)');const before=f.schemaSnapshot(),r=await fetchEntry(f);check('real entry ON '+state+' refuses503',r.status===503&&(await r.json()).error==='write_admission_held');check(state+' entry performs no mutation/installer',f.schemaSnapshot()===before&&f.trace.batches.length===0);const pending=[],old=console.error;console.error=()=>{};try{await f.L('./index').default.scheduled({},f.env,{waitUntil:p=>pending.push(p)});}finally{console.error=old;}check(state+' real scheduled ON starts zero jobs',pending.length===0&&f.trace.batches.length===0);f.db.close();}
 const installed=fixture();await installed.a.installCurrentPrivacyWriteAdmission(installed.native);const before=installed.trace.statements;const unknown=await installed.L('./index').default.fetch(new Request('https://unknown.example/health'),{...installed.env,PRIVACY_WRITE_ADMISSION_ENABLED:'true'},{waitUntil(){}});check('host refusal precedes schema/protocol reads',unknown.status===404&&installed.trace.statements===before);const staticResponse=await installed.L('./index').default.fetch(new Request('https://guild.example/static/app.js'),{...installed.env,PRIVACY_WRITE_ADMISSION_ENABLED:'true'},{waitUntil(){}});check('finite static remains database-free',staticResponse.status===200&&installed.trace.statements===before);installed.db.close();
 check('all native tests use zero outbound provider calls',providerCalls===0,providerCalls);for(const[f,p]of pins)check('actual source stable '+path.basename(f),cryptoNode.createHash('sha256').update(fs.readFileSync(f)).digest('hex')===p);
 console.log(`${passed}/${checks} actual admission entry/installation checks passed`);if(passed!==checks)process.exitCode=1;
})().catch(e=>{console.error(e.stack);process.exitCode=1;});
