/** Actual TypeScript + native SQLite. Synthetic accounts only; no production/provider network. */
const fs=require('fs'),path=require('path'),ts=require('typescript'),{DatabaseSync}=require('node:sqlite');
const root=path.join(__dirname,'..'),cache={};let checks=0,passes=0;const check=(label,value)=>{checks++;if(value)passes++;console.log((value?'PASS ':'FAIL ')+label);};
globalThis.fetch=async()=>{throw Error('network forbidden in privacy lifecycle fixture');};
function load(name){const file=path.resolve(root,'src',name+'.ts');if(cache[file])return cache[file].exports;const mod={exports:{}};cache[file]=mod;let text=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText;if(name==='privacy-serving-erase')text+='\nmodule.exports.testOnlyLocalCompletion=completeServingAccount;';new Function('module','exports','require',text)(mod,mod.exports,p=>load(path.relative(path.join(root,'src'),path.resolve(path.dirname(file),p)).replace(/\\/g,'/')));return mod.exports;}
let db,hooks={},attempts=0;
function adapter(){function prepared(sql){let values=[];const s={bind(...v){if(v.length>100||v.some(x=>x===undefined))throw Error('invalid native binding');values=v;return s;},exec(){attempts++;hooks.beforeStatement?.(sql);const st=db.prepare(sql);if(/^\s*(SELECT|WITH)\b/i.test(sql)||/\bRETURNING\b/i.test(sql)){const rows=st.all(...values);return{success:true,results:rows,meta:{changes:0}};}const r=st.run(...values);return{success:true,results:[],meta:{changes:Number(r.changes),last_row_id:Number(r.lastInsertRowid)}};},async first(column){const r=s.exec().results[0]??null;return column&&r?r[column]??null:r;},async all(){return s.exec();},async run(){return s.exec();}};return s;}return{prepare:prepared,async batch(stmts){hooks.beforeBatch?.();db.exec('BEGIN');let out;try{out=stmts.map(s=>s.exec());db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}if(hooks.loseResponse)throw Error('synthetic committed response loss');return out;}};}
const ID='300000000000000003',OTHER='300000000000000004',OP='a'.repeat(32),COOKIE='privacy-fixture-cookie-secret-0123456789';
const environment=()=>({DB:adapter(),COOKIE_SECRET:COOKIE,PRIVACY_ERASURE_ENABLED:'true',SITE_HOST:'guild.example',SITE_GUILD_ID:'236932545793490944',GUILD_ID:'236932545793490944',SITE_ADMINS:OTHER,ROLE_GUILD_MEMBER:'1551234567890123456',COMMUNITY_FEATURES:''});
const authority=load('privacy-serving-authority'),core=load('site-core'),context=load('community-context'),catalog=load('privacy-business-catalog');load('community-routes');load('qr-phase1-data');load('privacy-access-data');
function reset(){db?.close();db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON');db.exec(fs.readFileSync(path.join(root,'schema.sql'),'utf8'));hooks={};attempts=0;const now=Number(db.prepare("SELECT CAST(strftime('%s','now') AS INTEGER) n").get().n);db.prepare('INSERT INTO site_users(discord_id,username,first_login,last_login,session_version)VALUES(?,?,?,?,7)').run(ID,'Fixture',now,now);return now;}
const raw=(sql,...p)=>db.prepare(sql).get(...p);
async function cookie(){return(await core.sessionCookie(environment(),ID,7)).split(';')[0];}
const request=(c,path='/api/me/erasure')=>new Request('https://guild.example'+path,{method:'POST',headers:{Cookie:c,Origin:'https://guild.example','X-Olympus':'2'}});
const snap=()=>JSON.stringify(db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name").all().map(t=>[t.name,db.prepare(`SELECT * FROM ${t.name}`).all()]));
(async()=>{
reset();let c=await cookie();let res=await authority.requestServingErasure({...environment(),PRIVACY_ERASURE_ENABLED:'false'},request(c),OP);check('OFF request changes no authority or site version',res.status===503&&!raw('SELECT * FROM privacy_subjects')&&raw('SELECT session_version v FROM site_users').v===7);
check('exact joined business and privacy credential catalog qualifies current schema',await catalog.servingPrivacyCatalogCurrent(environment()));db.exec('CREATE TABLE _cf_KV(provider_key TEXT,provider_value BLOB)');check('only exact protected Cloudflare internal name is excluded before column census',await catalog.servingPrivacyCatalogCurrent(environment()));db.exec('CREATE TABLE _cf_unrecognized(secret TEXT)');check('another provider-looking store closes catalog',!await catalog.servingPrivacyCatalogCurrent(environment()));db.exec('DROP TABLE _cf_unrecognized');db.exec('ALTER TABLE privacy_subjects ADD COLUMN hidden_identity TEXT');check('an unclassified control column closes completion',!await catalog.servingPrivacyCatalogCurrent(environment()));
for(const phase of ['admission','subject','terminal']){reset();c=await cookie();const before=snap();hooks.beforeStatement=sql=>{if(phase==='admission'&&sql.includes('privacy_admission_refused')||phase==='subject'&&sql.startsWith('INSERT INTO privacy_subjects')||phase==='terminal'&&sql.includes('privacy_admission_unconfirmed'))throw Error('synthetic fault');};res=await authority.requestServingErasure(environment(),request(c),OP);check('actual '+phase+' fault rolls all tables/session back',res.status===503&&snap()===before);}
reset();c=await cookie();const oldCapture=await authority.readPrivacySubject(environment(),ID);res=await authority.requestServingErasure(environment(),request(c),OP);const body=await res.json();check('genuine original-session request admitted durably',res.status===202&&body.state==='waiting_role'&&raw('SELECT session_version v FROM site_users').v===8&&raw('SELECT state FROM privacy_subjects').state==='retiring');
check('original cookie loses ordinary site standing',await core.currentUser(environment(),request(c))===null);
const tokenStatus=await authority.erasureRequestStatus(environment(),request(''),OP,body.statusToken);check('purpose-only status credential reads admitted job without ordinary cookie',tokenStatus?.state==='waiting_role'&&tokenStatus.statusExpires===body.statusExpires&&!atob(body.statusToken.split('.')[0].replace(/-/g,'+').replace(/_/g,'/')).includes(ID));
check('modified status credential and operation substitution are refused',await authority.erasureRequestStatus(environment(),request(''),OP,body.statusToken.slice(0,-1)+'!')===null&&await authority.erasureRequestStatus(environment(),request(''),'b'.repeat(32),body.statusToken)===null);
check('status token cannot authenticate ordinary site access',await core.currentUser(environment(),request(body.statusToken))===null);
check('status remains scoped to original cookie', (await authority.erasureRequestStatus(environment(),request(c),OP))?.state==='waiting_role');const otherBody=core.b64u(new TextEncoder().encode(JSON.stringify({u:OTHER,v:7,e:Math.floor(Date.now()/1000)+3600,g:null})));const otherCookie=core.SESSION_COOKIE+'='+otherBody+'.'+await core.sign(COOKIE,'session',otherBody);check('another signed account cannot read job',await authority.erasureRequestStatus(environment(),request(otherCookie),OP)===null);
const proof=await authority.readErasureProof(environment(),OP);check('role proof consumes exact durable request/gen',await authority.currentAccountErasureProof(environment(),proof));let refused=false;try{await authority.admittedPrivacySubjectWrite(environment(),ID,oldCapture,[environment().DB.prepare('INSERT INTO members(discord_id)VALUES(?1)').bind(ID)]);}catch{refused=true;}check('paused accountless captured-absence write refused after request',refused&&!raw('SELECT * FROM members'));
const replay=await authority.requestServingErasure(environment(),request(c),OP);check('same original operation replays without renewal',replay.status===202&&(await replay.json()).replay===true&&raw('SELECT COUNT(*) n FROM privacy_serving_jobs').n===1);
reset();c=await cookie();hooks.loseResponse=true;res=await authority.requestServingErasure(environment(),request(c),OP);check('committed lost result reads durable receipt, no inferred rollback',res.status===202&&(await res.json()).responseRecovered===true&&raw('SELECT COUNT(*) n FROM privacy_serving_jobs').n===1);hooks={};
reset();const now=Number(raw("SELECT CAST(strftime('%s','now') AS INTEGER) n").n);const payload=core.b64u(new TextEncoder().encode(JSON.stringify({u:ID,v:7,e:now-1,g:null})));c=core.SESSION_COOKIE+'='+payload+'.'+await core.sign(COOKIE,'session',payload);res=await authority.requestServingErasure(environment(),request(c),OP);check('expired original cookie cannot admit deletion',res.status===401&&!raw('SELECT * FROM privacy_subjects'));
// Native consuming proof rejects old generation even when a replacement account deliberately reuses version7.
reset();c=await cookie();const session=await core.readSession(environment(),request(c));const bound=authority.privacyBoundSiteEnv(environment(),session);db.prepare("INSERT INTO privacy_subjects(subject_id,generation,state,revision,created_at,updated_at)VALUES(?,'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb','active',1,?,?)").run(ID,now,now);refused=false;const before=snap();try{await bound.DB.prepare('UPDATE site_users SET username=?1 WHERE discord_id=?2').bind('Late stale edit',ID).run();}catch{refused=true;}check('legacy site write refuses original captured absence after same-version recreation',refused&&before===snap());
let original={subject:{discordId:ID,sessionVersion:7,expiresAt:now+3600,privacyGeneration:null}};refused=false;try{await context.admitted(environment(),original,[environment().DB.prepare('UPDATE site_users SET username=?1 WHERE discord_id=?2').bind('Stale community',ID)]);}catch{refused=true;}check('opaque community first/middle writes consume original generation, not current active',refused&&raw('SELECT username FROM site_users').username==='Fixture');
const retiredGeneration='c'.repeat(32);db.prepare("UPDATE privacy_subjects SET generation=?,state='retired',erased_at=?,retain_until=?+31622400,revision=2 WHERE subject_id=?").run(retiredGeneration,now,now,ID);let captured=await authority.readPrivacySubject(environment(),ID);const write=()=>environment().DB.prepare("INSERT INTO site_users(discord_id,first_login,last_login,session_version)VALUES(?1,?2,?2,7)ON CONFLICT(discord_id)DO UPDATE SET username='Fresh',session_version=7 RETURNING session_version").bind(ID,now);refused=false;try{await authority.admittedPrivacyOAuthWrite(environment(),ID,captured,now,write());}catch{refused=true;}check('OAuth state begun before/equal erase cannot recreate',refused&&raw('SELECT state FROM privacy_subjects').state==='retired');
await authority.admittedPrivacyOAuthWrite(environment(),ID,captured,now+1,write());const fresh=await authority.readPrivacySubject(environment(),ID);check('genuine later OAuth rotates generation, retains old replay separation',fresh.state==='active'&&fresh.subjectGeneration!==retiredGeneration);refused=false;try{await authority.admittedPrivacySubjectWrite(environment(),ID,captured,[environment().DB.prepare('INSERT INTO members(discord_id)VALUES(?1)').bind(ID)]);}catch{refused=true;}check('late old-generation watcher cannot write after genuine reentry',refused&&!raw('SELECT * FROM members'));
db.prepare('INSERT INTO members(discord_id,username)VALUES(?,?)').run(ID,'Unchanged');await load('names').recordNames(environment(),{id:ID,username:'Late old login'},false,captured);check('late OAuth names cannot rewrite a replacement generation',raw('SELECT username FROM members').username==='Unchanged');
// Direct erasure has its own original-cookie admission. A refreshed target is never that proof.
for(const initiallyPresent of [false,true]){const fixtureNow=reset();if(initiallyPresent)db.prepare("INSERT INTO privacy_subjects(subject_id,generation,state,revision,created_at,updated_at)VALUES(?,?,'active',1,?,?)").run(ID,'b'.repeat(32),fixtureNow,fixtureNow);const historicalCookie=await cookie();db.prepare("INSERT INTO privacy_subjects(subject_id,generation,state,revision,created_at,updated_at,erased_at,retain_until)VALUES(?,?,'retired',2,?,?,?,?+31622400)ON CONFLICT(subject_id)DO UPDATE SET state='retired',revision=2,erased_at=excluded.erased_at,retain_until=excluded.retain_until").run(ID,'b'.repeat(32),fixtureNow,fixtureNow,fixtureNow,fixtureNow);const retired=await authority.readPrivacySubject(environment(),ID);await authority.admittedPrivacyOAuthWrite(environment(),ID,retired,fixtureNow+1,environment().DB.prepare('UPDATE site_users SET session_version=7 WHERE discord_id=?1 RETURNING session_version').bind(ID));const currentBefore=snap();res=await authority.requestServingErasure(environment(),request(historicalCookie),OP);check('original signed '+(initiallyPresent?'OLD generation':'NULL absence')+' cannot erase genuine recreated same-version account',res.status===401&&snap()===currentBefore&&!raw('SELECT * FROM privacy_serving_jobs'));}
reset();const markerKey=await authority.privacySubjectKey(environment(),ID);db.prepare("INSERT INTO privacy_denial_markers VALUES(?,?,?,'rejected_guild_application_or_membership')").run(markerKey,now-10,now-10+authority.PRIVACY_YEAR);refused=false;try{await authority.admittedPrivacyOAuthWrite(environment(),ID,null,now+1,write());}catch{refused=true;}check('fixed denied marker blocks fresh signup without any ordinary session authority',refused&&!raw('SELECT * FROM privacy_subjects'));
check('denial marker stores no raw ID, name or free-text reason',!JSON.stringify(raw('SELECT * FROM privacy_denial_markers')).includes(ID));
const migration=fs.readFileSync(path.join(root,'migrations/2026-10-10-privacy-serving.sql'),'utf8');db.exec(migration);db.exec(migration);check('same dated DDL is idempotent twice against cold canonical schema',db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'").all().length===65);
// Real finite sweeper: original beta clocks stay intact, cutoff aging remains held until the attended reset.
reset();const retention=load('privacy-retention'),year=authority.PRIVACY_YEAR,clock=Number(raw("SELECT CAST(strftime('%s','now') AS INTEGER)n").n);db.prepare('INSERT INTO pending(discord_id,name_key,name,created_at,expires_at)VALUES(?,?,?,?,?)').run(ID,'old name','Old Name',clock-year-20,clock-year-10);db.prepare('INSERT INTO roster_first_seen VALUES(?,?)').run('old name',clock-year-20);let frozen=snap();check('retention OFF performs no statements or writes',await retention.sweepServingRetention(environment())===0&&snap()===frozen);
await retention.sweepServingRetention({...environment(),PRIVACY_RETENTION_ENABLED:'true'});check('unannounced or unconfirmed beta cutoff does not expire request/first-seen clocks',!!raw('SELECT * FROM pending')&&!!raw('SELECT * FROM roster_first_seen'));
db.prepare('INSERT INTO site_settings(key,value,updated_at)VALUES(?,?,?)').run('betaClosedAt',String(clock-10),clock);db.prepare('INSERT INTO site_settings(key,value,updated_at)VALUES(?,?,?)').run('betaResetFor',JSON.stringify({closedAt:clock-10,nonce:'fixture'}),clock);await retention.sweepServingRetention({...environment(),PRIVACY_RETENTION_ENABLED:'true'});check('confirmed recent beta cutoff keeps original old records without changing dates',raw('SELECT created_at FROM pending').created_at===clock-year-20&&raw('SELECT first_seen FROM roster_first_seen').first_seen===clock-year-20);
db.prepare('UPDATE site_settings SET value=? WHERE key=?').run(String(clock-year-30),'betaClosedAt');db.prepare('UPDATE site_settings SET value=? WHERE key=?').run(JSON.stringify({closedAt:clock-year-30,nonce:'fixture'}),'betaResetFor');await retention.sweepServingRetention({...environment(),PRIVACY_RETENTION_ENABLED:'true'});check('old confirmed cutoff expires beta records after fixed year',!raw('SELECT * FROM pending')&&!raw('SELECT * FROM roster_first_seen'));
db.prepare("INSERT INTO site_reserved(owner_id,name,name_key,status,created_at,released_at)VALUES(?,?,?,'released',?,?)").run(ID,'Released Name','released name',clock-year-40,clock-year-30);db.prepare("INSERT INTO relays(officer_id,character,online,seen_at,changed_at)VALUES(?,?,0,?,?)").run('inactive relay','Inactive Relay',clock-year-30,clock-year-30);db.prepare('INSERT INTO audit(ts,actor,action)VALUES(?,?,?)').run(clock-year-20,ID,'synthetic.old');const prior=snap();hooks.beforeStatement=sql=>{if(sql.startsWith('DELETE FROM relays'))throw Error('middle retention fault');};let aborted=false;try{await retention.sweepServingRetention({...environment(),PRIVACY_RETENTION_ENABLED:'true'});}catch{aborted=true;}check('middle retention failure rolls the entire native batch back',aborted&&snap()===prior);hooks={};const seenAttempts=attempts;await retention.sweepServingRetention({...environment(),PRIVACY_RETENTION_ENABLED:'true'});check('released names, inactive relays and dated logs expire in exact20 statement page',!raw('SELECT * FROM site_reserved')&&!raw('SELECT * FROM relays')&&!raw('SELECT * FROM audit')&&attempts-seenAttempts===retention.SERVING_RETENTION_STATEMENTS);
for(const state of ['removed','refused','unknown','known'])db.prepare("INSERT INTO privacy_provider_messages(operation_id,purpose,subjects,channel_id,state,created_at,updated_at,retain_until)VALUES(?,'review',?,?, ?,?,?,?)").run(state.padEnd(32,'a'),JSON.stringify([{id:ID,g:null}]),'1551234567890123458',state,clock-authority.PRIVACY_REPLAY-1,clock-1,clock-1);await retention.sweepServingRetention({...environment(),PRIVACY_RETENTION_ENABLED:'true'});check('terminal provider pointers expire at fixed366d while unresolved custody is explicitly preserved',!raw("SELECT * FROM privacy_provider_messages WHERE state IN('removed','refused')")&&db.prepare('SELECT COUNT(*)n FROM privacy_provider_messages').get().n===2);
reset();const forms=load('policy-forms'),formCore=load('policy-form-core');c=await cookie();const pageReq=new Request('https://guild.example/privacy/account',{headers:{Cookie:c}});let page=await forms.handlePolicyForms(pageReq,environment(),'/privacy/account',true),html=await page.text();const nonceCookie=page.headers.get('Set-Cookie').split(';')[0],eraseForm=html.match(/<form method="post" action="\/privacy\/account\/full-erase">([\s\S]*?)<\/form>/)[1],formCsrf=eraseForm.match(/name="csrf" value="([^"]+)"/)[1],formOp=eraseForm.match(/name="operationId" value="([^"]+)"/)[1];check('actual account page exposes explicit serving-erasure confirmation and no private code in URL',html.includes('Guild Member access ends')&&/^[0-9a-f]{32}$/.test(formOp)&&!html.includes('?statusToken='));
const submit=(body,cookies=c+'; '+nonceCookie,path='/privacy/account/full-erase')=>new Request('https://guild.example'+path,{method:'POST',headers:{Cookie:cookies,Origin:'https://guild.example','Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(body)});
let formResponse=await forms.handlePolicyForms(submit({csrf:formCsrf,operationId:formOp}),environment(),'/privacy/account/full-erase',true);check('missing explicit confirmation creates no erasure request or session revocation',formResponse.status===400&&!raw('SELECT * FROM privacy_serving_jobs')&&raw('SELECT session_version FROM site_users').session_version===7);
formResponse=await forms.handlePolicyForms(submit({csrf:formCsrf,operationId:formOp,confirm:'erase'}),environment(),'/privacy/account/full-erase',true);html=await formResponse.text();check('actual script-free form admits durable closure and displays truthful queued status/recovery exclusions',formResponse.status===200&&raw('SELECT state FROM privacy_serving_jobs').state==='waiting_role'&&html.includes('account erasure is not complete')&&html.includes('does not mean every copy was erased'));
const privateCode=html.match(/<pre>([^<]+)<\/pre>/)[1],statusCsrf=html.match(/name="csrf" value="([^"]+)"/)[1];formResponse=await forms.handlePolicyForms(submit({csrf:statusCsrf,operationId:formOp,statusToken:privateCode},nonceCookie,'/privacy/account/erasure-status'),environment(),'/privacy/account/erasure-status',true);check('saved purpose-only status form works without ordinary site cookie and never changes jobs',formResponse.status===200&&(await formResponse.text()).includes('waiting_role')&&raw('SELECT COUNT(*) n FROM privacy_serving_jobs').n===1);
console.log(`${passes}/${checks} privacy serving lifecycle checks passed; no network or real-account effects`);db.close();if(passes!==checks)process.exitCode=1;
})().catch(e=>{console.error('privacy fixture stopped:',e.stack);process.exitCode=1;});
