/** Actual serving sources + actual central QR role writer + native SQLite. No production data/network.
 * During source composition PRIVACY134_QR_SOURCE may point at the QR author's isolated working source.
 * This is provisional integration evidence until both exact source sets are frozen and composed.
 */
const fs=require('fs'),path=require('path'),ts=require('typescript'),{DatabaseSync}=require('node:sqlite');
const root=path.join(__dirname,'..'),external=process.env.PRIVACY134_QR_SOURCE||null,cache=new Map(),pins=new Map();
const prefer=new Set(['roles','role-settlements','qr-phase1','qr-phase1-data','qr-phase1-schema','native-rank-adapter']);
function load(name){name=name.replace(/^\.\//,'');let file=path.join(root,'src',name+'.ts');if(external&&(prefer.has(name)||!fs.existsSync(file)))file=path.join(external,name+'.ts');if(cache.has(file))return cache.get(file).exports;
 const bytes=fs.readFileSync(file);pins.set(file,bytes);const mod={exports:{}};cache.set(file,mod);let code=ts.transpileModule(bytes.toString('utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
 if(name==='privacy-serving-erase')code+='\nmodule.exports.testOnlyLocalCompletion=completeServingAccount;';if(name==='roster')code+='\nmodule.exports.testOnlyApplyEffect=applyEffect;';
 new Function('module','exports','require',code)(mod,mod.exports,p=>load(p));return mod.exports;}
const authority=load('privacy-serving-authority'),core=load('site-core'),catalog=load('privacy-business-catalog'),qr=load('qr-phase1-schema');load('qr-phase1-data');
const roles=load('roles'),eraser=load('privacy-serving-erase'),messages=load('privacy-provider-messages');
let db,hooks={},attempts=0,calls=[],hasRole=false,loseDelete=false,afterPost=null,deletedMessage=false,loseMessageDelete=false;
let checks=0,passes=0;function check(s,v){checks++;if(v)passes++;console.log((v?'PASS ':'FAIL ')+s);}
function adapter(){function prepare(sql){let values=[];const s={_sql:sql,bind(...v){if(v.some(x=>x===undefined)||v.length>100)throw Error('invalid binding');values=v;return s;},exec(){attempts++;hooks.beforeStatement?.(sql);const st=db.prepare(sql);if(/^\s*(SELECT|WITH)\b/i.test(sql)||/\bRETURNING\b/i.test(sql))return{success:true,results:st.all(...values),meta:{changes:0}};const r=st.run(...values);return{success:true,results:[],meta:{changes:Number(r.changes),last_row_id:Number(r.lastInsertRowid)}};},async first(c){const r=s.exec().results[0]??null;await hooks.afterRead?.(sql);return c&&r?r[c]??null:r;},async all(){const r=s.exec();await hooks.afterRead?.(sql);return r;},async run(){return s.exec();}};return s;}return{prepare,async batch(stmts){await hooks.beforeBatch?.(stmts);db.exec('BEGIN');let out;try{out=stmts.map(s=>s.exec());db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}if(hooks.loseResponse)throw Error('synthetic lost committed result');return out;}};}
const ID='300000000000000003',OTHER='300000000000000004',BOT='300000000000000099',GUILD='236932545793490944',MEMBER='1551234567890123456',BOTROLE='1551234567890123457',CHANNEL='1551234567890123458',MSG='1551234567890123459',OP='a'.repeat(32),SECRET='privacy-fixture-cookie-secret-0123456789';
const env=()=>({DB:adapter(),COOKIE_SECRET:SECRET,PRIVACY_ERASURE_ENABLED:'true',SITE_HOST:'guild.example',SITE_GUILD_ID:GUILD,GUILD_ID:GUILD,DISCORD_APP_ID:BOT,SITE_ADMINS:OTHER,ROLE_GUILD_MEMBER:MEMBER,DISCORD_BOT_TOKEN:'synthetic-unused-token',COMMUNITY_FEATURES:'',CHANNEL_NOTICES:CHANNEL});
const raw=(q,...v)=>db.prepare(q).get(...v),rows=(q,...v)=>db.prepare(q).all(...v);
function reset(oldActivitySchema=false){db?.close();db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON');let schema=fs.readFileSync(path.join(root,'schema.sql'),'utf8');if(oldActivitySchema){const current='names_at       INTEGER,         --   when those two were last read (names.ts: interactions, site sign-ins, the cron)\n  activity_at    INTEGER          -- genuine account activity time; no provider identifier; never refreshed by cron';if(schema.split(current).length!==2)throw Error('old-schema fixture source boundary changed');schema=schema.replace(current,'names_at       INTEGER');}db.exec(schema);qr.QR_PHASE1_DDL.forEach(x=>db.exec(x));hooks={};calls=[];hasRole=false;loseDelete=false;afterPost=null;deletedMessage=false;loseMessageDelete=false;attempts=0;const t=raw("SELECT CAST(strftime('%s','now')AS INTEGER)n").n;db.prepare('INSERT INTO site_users(discord_id,username,first_login,last_login,session_version)VALUES(?,?,?,?,7)').run(ID,'Synthetic Member',t,t);return t;}
const snapshot=()=>JSON.stringify(rows("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name").map(t=>[t.name,rows(`SELECT * FROM ${t.name}`)]));
globalThis.fetch=async(url,init={})=>{const method=init.method||'GET',p=new URL(url).pathname;calls.push(method+' '+p);if(!String(url).startsWith('https://discord.com/api/v10/'))throw Error('unexpected target');let data;
 if(method==='GET'&&p.endsWith('/users/@me'))data={id:BOT};
 else if(method==='GET'&&p===`/api/v10/guilds/${GUILD}/roles`)data=[{id:GUILD,position:0,permissions:'0',managed:false},{id:MEMBER,position:1,permissions:'0',managed:false},{id:BOTROLE,position:10,permissions:'268435456',managed:false}];
 else if(method==='GET'&&p===`/api/v10/guilds/${GUILD}/members/${BOT}`)data={roles:[BOTROLE],user:{id:BOT}};
 else if(method==='GET'&&p===`/api/v10/guilds/${GUILD}/members/${ID}`)data={roles:hasRole?[MEMBER]:[],user:{id:ID}};
 else if(method==='DELETE'&&p===`/api/v10/guilds/${GUILD}/members/${ID}/roles/${MEMBER}`){hasRole=false;if(loseDelete){loseDelete=false;throw Error('synthetic lost landed role DELETE');}return new Response(null,{status:204});}
 else if(method==='POST'&&p===`/api/v10/channels/${CHANNEL}/messages`){await afterPost?.();data={id:MSG};}
 else if(method==='DELETE'&&p===`/api/v10/channels/${CHANNEL}/messages/${MSG}`){deletedMessage=true;if(loseMessageDelete){loseMessageDelete=false;throw Error('synthetic lost landed message DELETE');}return new Response(null,{status:204});}
 else if(method==='GET'&&p===`/api/v10/channels/${CHANNEL}/messages/${MSG}`){if(deletedMessage)return new Response(JSON.stringify({code:10008}),{status:404});data={id:MSG,channel_id:CHANNEL,author:{id:BOT}};}
 else throw Error('unexpected Discord target '+method+' '+p);return new Response(JSON.stringify(data),{status:200,headers:{'Content-Type':'application/json'}});};
const req=c=>new Request('https://guild.example/api/me/erasure',{method:'POST',headers:{Cookie:c,Origin:'https://guild.example','X-Olympus':'2'}});
async function admission(){const cookie=(await core.sessionCookie(env(),ID,7)).split(';')[0],response=await authority.requestServingErasure(env(),req(cookie),OP);if(response.status!==202)throw Error('genuine request not admitted');return authority.readErasureProof(env(),OP);}
(async()=>{
 let t=reset();check('all52 business + five controls + real five QR registered hooks qualify current shape',await catalog.servingPrivacyCatalogCurrent(env()));
 db.prepare('UPDATE site_users SET denied=1,denied_at=?,denied_reason=? WHERE discord_id=?').run(t-30,'Synthetic denial reason',ID);db.prepare("INSERT INTO members(discord_id,username)VALUES(?,?)").run(ID,'Sensitive synthetic name');db.prepare("INSERT INTO characters(name_key,name,discord_id,status,bound_at,source,guid)VALUES(?,?,?,'member',?,'fixture',?)").run('fixture name','Fixture Name',ID,t-40,'Player-0-00000001');
 let proof=await admission(),started=attempts,out=await eraser.continueServingErasure(env(),proof);console.log('Actual successful continuation SQL attempts:',attempts-started);if(out.state!=='complete')console.log('Synthetic completion hold:',JSON.stringify(out));check('actual original-cookie→central confirmed role absence→registered local serving erase completes',out.state==='complete'&&out.servingAccountErased&&!raw('SELECT * FROM site_users')&&!raw('SELECT * FROM members')&&!raw('SELECT * FROM characters'));
 let marker=raw('SELECT * FROM privacy_denial_markers');check('denial marker keeps original denial+365d, no name/raw account ID, replay separate366d',marker.denied_at===t-30&&marker.retain_until===t-30+365*86400&&!JSON.stringify(marker).includes(ID)&&raw('SELECT retain_until-erased_at d FROM privacy_restore_replay').d===366*86400);
 check('completion never claims all copies erased; recovery custody remains explicit',out.allCopiesErased===false&&out.recoveryCopies==='operator-held'&&out.providerMessages==='unqualified');
 for(const phase of ['early','middle','audit','terminal']){reset();proof=await admission();const receipt=await roles.settleAccountErasureMemberRole(env(),proof),before=snapshot();hooks.beforeStatement=sql=>{if(phase==='early'&&sql.includes('privacy_completion_refused')||phase==='middle'&&sql.startsWith('DELETE FROM characters')||phase==='audit'&&sql.startsWith('DELETE FROM audit')||phase==='terminal'&&sql.includes('privacy_terminal_unconfirmed'))throw Error('synthetic native fault');};out=await eraser.testOnlyLocalCompletion(env(),proof,receipt,roles.accountErasureRoleSettledSql);check('actual '+phase+' local-erasure failure rolls every registered table/control back',out.state==='unknown'&&snapshot()===before);}
 reset();hasRole=true;loseDelete=true;proof=await admission();out=await eraser.continueServingErasure(env(),proof);check('lost landed member-role DELETE holds local erase with durable unknown dispatch',out.state==='unknown'&&!!raw('SELECT * FROM site_users')&&raw('SELECT attempts,state FROM role_settlements').attempts===1);out=await eraser.continueServingErasure(env(),proof);check('GET proves absence on retry, full local erase follows without a second DELETE',out.state==='complete'&&calls.filter(x=>x===`DELETE /api/v10/guilds/${GUILD}/members/${ID}/roles/${MEMBER}`).length===1);
 reset();proof=await admission();let receipt=await roles.settleAccountErasureMemberRole(env(),proof);db.prepare("INSERT INTO role_settlements(id,subject,purpose,guild_id,role_id,desired,state,reason,attempts,created_at,expires_at)VALUES(?,?,'verified_membership',?,?,1,'unknown','fixture unknown',1,?,?)").run('b'.repeat(32),ID,GUILD,MEMBER,t,t+300);let before=snapshot();out=await eraser.testOnlyLocalCompletion(env(),proof,receipt,roles.accountErasureRoleSettledSql);check('actual QR eraser preserves sole unknown external dispatch and atomically holds local completion',out.state==='unknown'&&snapshot()===before);
 reset();db.prepare("INSERT INTO privacy_subjects(subject_id,generation,state,revision,created_at,updated_at)VALUES(?,?,'active',1,?,?)").run(ID,'c'.repeat(32),t,t);const capture=await authority.readPrivacySubject(env(),ID),bound=authority.privacyBoundSubjectEnv(env(),ID,capture);afterPost=async()=>{proof=await admission();};const posted=await messages.postPrivacyMessage(bound,'review',CHANNEL,{content:'Synthetic review'},[{subject:ID,capture}],OP);check('POST completing after request closure preserves known pointer and cleanup debt in purpose custody',posted.id===MSG&&raw('SELECT state,cleanup_requested FROM privacy_provider_messages').state==='known'&&raw('SELECT cleanup_requested FROM privacy_provider_messages').cleanup_requested===1);
 before=calls.length;const noReplay=await messages.postPrivacyMessage(env(),'review',CHANNEL,{content:'Must never send'},[{subject:ID,capture}],OP);check('same original message operation or retired capture never sends again',noReplay===null&&calls.length===before);
 loseMessageDelete=true;await messages.cleanupPrivacyMessages(env(),ID);check('lost landed message DELETE retains pointer/cleaning state',raw('SELECT state FROM privacy_provider_messages').state==='cleaning');await messages.cleanupPrivacyMessages(env(),ID);check('known pointer cleanup reconciles by GET absence, no second DELETE and no retained subject references',raw('SELECT state,subjects FROM privacy_provider_messages').state==='removed'&&raw('SELECT subjects FROM privacy_provider_messages').subjects==='[]'&&calls.filter(x=>x===`DELETE /api/v10/channels/${CHANNEL}/messages/${MSG}`).length===1);
 check('all provider targets are fixed intended guild/member/role and bot message routes',calls.every(x=>x.includes(`/guilds/${GUILD}/`)||x.endsWith('/users/@me')||x.includes(`/channels/${CHANNEL}/messages`)));
 const jobs=load('privacy-serving-jobs');reset();started=attempts;let result=await jobs.runServingErasureJob({...env(),PRIVACY_ERASURE_ENABLED:'false'});check('automatic erasure OFF has zero database/provider work',result.attempted===0&&attempts===started&&calls.length===0);
 started=attempts;await messages.postPrivacyMessage({...env(),PRIVACY_ERASURE_ENABLED:'false'},'review',CHANNEL,{content:'Synthetic ordinary OFF notice'},[{subject:ID,capture:null}],OP);check('ordinary OFF message path creates no dormant provider ledger or database work',attempts===started&&!raw('SELECT * FROM privacy_provider_messages')&&calls.filter(x=>x==='POST /api/v10/channels/'+CHANNEL+'/messages').length===1);
 t=reset();db.prepare('UPDATE site_users SET last_login=? WHERE discord_id=?').run(t-authority.PRIVACY_YEAR-1,ID);started=attempts;result=await jobs.runServingErasureJob({...env(),PRIVACY_RETENTION_ENABLED:'true'});console.log('Actual inactive admission+automatic completion SQL:',attempts-started);check('actual source derives inactive purpose and automatically completes without a synthesized cookie',result.completed===1&&!raw('SELECT * FROM site_users')&&raw('SELECT original_session_expires FROM privacy_serving_jobs').original_session_expires===0);
 t=reset();db.prepare('UPDATE site_users SET last_login=? WHERE discord_id=?').run(t-authority.PRIVACY_YEAR-1,ID);hooks.afterRead=async sql=>{if(sql.includes('ORDER BY u.last_login')){hooks.afterRead=null;db.prepare('UPDATE site_users SET last_login=? WHERE discord_id=?').run(t,ID);}};before=snapshot();result=await jobs.runServingErasureJob({...env(),PRIVACY_RETENTION_ENABLED:'true'});check('activity during paused inactive selection refuses closure in the consuming batch',result.attempted===0&&!raw('SELECT * FROM privacy_serving_jobs')&&!raw('SELECT * FROM privacy_subjects')&&raw('SELECT last_login FROM site_users').last_login===t);
 t=reset();proof=await admission();for(let i=0;i<5;i++){db.prepare("INSERT INTO privacy_provider_messages(operation_id,purpose,subjects,channel_id,message_id,state,cleanup_requested,created_at,updated_at,retain_until)VALUES(?,'review',?, ?,?,'known',1,?,?,?)").run(i.toString(16).repeat(32),JSON.stringify([{id:ID,g:proof.subjectGeneration}]),CHANNEL,MSG,t,t,t+authority.PRIVACY_REPLAY);const event=i.toString().repeat(22),op=(i+5).toString().repeat(22);db.prepare("INSERT INTO community_events(id,op_id,title,starts_at,duration_min,ends_at,created_by,created_at,updated_at,retain_until)VALUES(?,?,'Synthetic event',?,60,?,?,?,?,?)").run(event,op,t+3600,t+7200,ID,t,t,t+authority.PRIVACY_REPLAY);db.prepare("INSERT INTO community_event_deliveries(event_id,purpose,event_revision,starts_at,guild_id,channel_id,message_id,op_id,claim_nonce,state,actor,created_at,updated_at,retain_until)VALUES(?,'publication',1,?,?,?,?,?,?,'posted',?,?,?,?)").run(event,t+3600,GUILD,CHANNEL,MSG,op,'n'.repeat(22),ID,t,t,t+authority.PRIVACY_REPLAY);}
 for(const key of ['b','c'])db.prepare("INSERT INTO role_settlements(id,subject,purpose,guild_id,role_id,desired,state,reason,attempts,created_at,expires_at)VALUES(?,?,'verified_membership',?,?,1,'unknown','expired fixture',1,?,?)").run(key.repeat(32),ID,GUILD,MEMBER,t-400,t-100);
 started=attempts;result=await jobs.runServingErasureJob(env());const maxAttempts=attempts-started;console.log('Actual one-job/two-five-pointer/two-expired-role-debt SQL:',maxAttempts);check('bounded automatic job reconciles two expired role debts GET-only, adopts creator pointers before anonymizing and cleans two finite pages',result.completed===1&&maxAttempts<=140&&rows("SELECT * FROM privacy_provider_messages WHERE state NOT IN('removed','refused')").length===0&&calls.every(c=>!c.startsWith('PUT ')&&!c.includes('/roles/'+MEMBER)||c.startsWith('GET ')));
 t=reset();db.prepare('DELETE FROM site_users').run();db.prepare('INSERT INTO members(discord_id,linked_at)VALUES(?,?)').run(ID,t-authority.PRIVACY_YEAR-1);started=attempts;result=await jobs.runServingErasureJob({...env(),PRIVACY_RETENTION_ENABLED:'true'});console.log('Actual accountless inactive job SQL:',attempts-started);check('dated accountless bot account uses native purpose admission and confirmed role absence before local erase',result.completed===1&&!raw('SELECT * FROM members')&&raw('SELECT original_session_expires FROM privacy_serving_jobs').original_session_expires===0);
 t=reset();db.prepare('DELETE FROM site_users').run();db.prepare('INSERT INTO members(discord_id)VALUES(?)').run(ID);result=await jobs.runServingErasureJob({...env(),PRIVACY_RETENTION_ENABLED:'true'});check('undated legacy accountless data is held rather than inventing historical activity',result.attempted===0&&!!raw('SELECT * FROM members')&&!raw('SELECT * FROM privacy_serving_jobs'));
 t=reset();db.prepare('DELETE FROM site_users').run();db.prepare('INSERT INTO members(discord_id,linked_at)VALUES(?,?)').run(ID,t-authority.PRIVACY_YEAR-1);hooks.afterRead=async sql=>{if(sql.includes('ORDER BY activity_clock')){hooks.afterRead=null;db.prepare('UPDATE members SET linked_at=? WHERE discord_id=?').run(t,ID);}};result=await jobs.runServingErasureJob({...env(),PRIVACY_RETENTION_ENABLED:'true'});check('changed original accountless activity clock after selection atomically refuses retirement and job creation',result.attempted===0&&!raw('SELECT * FROM privacy_subjects')&&!raw('SELECT * FROM privacy_serving_jobs')&&!!raw('SELECT * FROM members'));
 t=reset();db.prepare("INSERT INTO privacy_provider_messages(operation_id,purpose,subjects,channel_id,message_id,state,cleanup_requested,created_at,updated_at,retain_until)VALUES(?,'review',?, ?,?,'known',1,?,?,?)").run(OP,JSON.stringify([{id:ID,g:null}]),CHANNEL,MSG,t,t,t+authority.PRIVACY_REPLAY);result=await jobs.runServingErasureJob(env());check('completed-account provider cleanup continues independently even without an open erasure job',result.attempted===0&&raw('SELECT state FROM privacy_provider_messages').state==='removed');
 // An accountless link's valid operational time survives the existing provider-specific purge.
 t=reset();db.prepare('DELETE FROM site_users').run();const originalActivity=t-authority.PRIVACY_YEAR-1;db.prepare('INSERT INTO members(discord_id,battletag,linked_at)VALUES(?,?,?)').run(ID,'Synthetic#0000',originalActivity);await load('bnet-retention').purgeBattleNetData(env(),t);check('Blizzard purge clears raw link/tag within29d and preserves only original non-provider activity time',raw('SELECT battletag,linked_at,activity_at FROM members').battletag===null&&raw('SELECT linked_at,activity_at FROM members').linked_at===null&&raw('SELECT activity_at FROM members').activity_at===originalActivity);result=await jobs.runServingErasureJob({...env(),PRIVACY_RETENTION_ENABLED:'true'});check('BNet-only accountless account still reaches genuine365d automatic erasure after raw provider purge',result.completed===1&&!raw('SELECT * FROM members'));
 // Both automatic admissions consume the beta retention guard, not only a pre-read.
 for(const accountless of [false,true]){t=reset();if(accountless){db.prepare('DELETE FROM site_users').run();db.prepare('INSERT INTO members(discord_id,activity_at)VALUES(?,?)').run(ID,t-authority.PRIVACY_YEAR-1);}else db.prepare('UPDATE site_users SET last_login=? WHERE discord_id=?').run(t-authority.PRIVACY_YEAR-1,ID);db.prepare('INSERT INTO pending(discord_id,name_key,name,created_at,expires_at)VALUES(?,?,?,?,?)').run(ID,'beta fixture','Beta Fixture',t-authority.PRIVACY_YEAR-30,t-100);result=await jobs.runServingErasureJob({...env(),PRIVACY_RETENTION_ENABLED:'true'});check((accountless?'accountless':'site')+' automatic inactivity cannot bypass unknown beta cutoff',result.attempted===0&&!raw('SELECT * FROM privacy_serving_jobs')&&!!raw('SELECT * FROM pending'));db.prepare('INSERT INTO site_settings(key,value,updated_at)VALUES(?,?,?)').run('betaClosedAt',String(t-10),t);db.prepare('INSERT INTO site_settings(key,value,updated_at)VALUES(?,?,?)').run('betaResetFor',JSON.stringify({closedAt:t-10}),t);result=await jobs.runServingErasureJob({...env(),PRIVACY_RETENTION_ENABLED:'true'});check((accountless?'accountless':'site')+' recent confirmed beta cutoff keeps original records through fixed12-month minimum',result.attempted===0&&raw('SELECT created_at FROM pending').created_at===t-authority.PRIVACY_YEAR-30);}
 t=reset();db.prepare('UPDATE site_users SET last_login=? WHERE discord_id=?').run(t-authority.PRIVACY_YEAR-1,ID);hooks.afterRead=async sql=>{if(sql.includes('ORDER BY u.last_login')){hooks.afterRead=null;db.prepare('INSERT INTO pending(discord_id,name_key,name,created_at,expires_at)VALUES(?,?,?,?,?)').run(ID,'raced beta','Raced Beta',t-authority.PRIVACY_YEAR-20,t-10);}};result=await jobs.runServingErasureJob({...env(),PRIVACY_RETENTION_ENABLED:'true'});check('beta record created after inactive selection refuses the atomic retirement/job claim',result.attempted===0&&!raw('SELECT * FROM privacy_subjects')&&!raw('SELECT * FROM privacy_serving_jobs')&&!!raw('SELECT * FROM site_users'));
 // A genuinely later rejection replaces an expired slot; a live original clock is never renewed.
 for(const expiredMarker of [true,false]){t=reset();const key=await authority.privacySubjectKey(env(),ID),originalDenied=expiredMarker?t-authority.PRIVACY_YEAR-10:t-100;db.prepare("INSERT INTO privacy_denial_markers VALUES(?,?,?,'rejected_guild_application_or_membership')").run(key,originalDenied,originalDenied+authority.PRIVACY_YEAR);db.prepare('UPDATE site_users SET denied=1,denied_at=? WHERE discord_id=?').run(t-20,ID);proof=await admission();out=await eraser.continueServingErasure(env(),proof);const fixed=raw('SELECT denied_at,retain_until FROM privacy_denial_markers');check(expiredMarker?'expired marker slot consumes genuinely later rejection before cron without immediate bypass':'same-live rejection branch retains original deadline without retry renewal',out.state==='complete'&&fixed.denied_at===(expiredMarker?t-20:originalDenied)&&fixed.retain_until===fixed.denied_at+authority.PRIVACY_YEAR);}
 // Two consumers of one original job selection may not both enter its continuation.
 t=reset();proof=await admission();let competing=null;hooks.afterRead=async sql=>{if(sql.startsWith('SELECT operation_id AS operationId')&&sql.includes('last_attempt_at')){hooks.afterRead=null;competing=await jobs.runServingErasureJob(env());}};result=await jobs.runServingErasureJob(env());check('concurrent original selections admit at most one continuation and one terminal completion',competing?.completed===1&&result.attempted===0&&raw('SELECT COUNT(*)n FROM privacy_restore_replay').n===1);
 t=reset();proof=await admission();db.prepare('UPDATE privacy_serving_jobs SET created_at=?,retain_until=? WHERE operation_id=?').run(t-authority.PRIVACY_REPLAY,t,OP);started=calls.length;result=await jobs.runServingErasureJob(env());check('exact expired purpose deadline causes zero provider effect; unresolved job remains openly held',result.attempted===0&&calls.length===started&&!!raw('SELECT * FROM site_users')&&raw('SELECT state FROM privacy_subjects').state==='retiring');
 // Actual own-data exporter includes the minimized lifecycle controls in its admitted capture.
 t=reset();db.prepare("INSERT INTO privacy_serving_jobs(operation_id,subject_id,subject_generation,request_digest,original_session_version,original_session_expires,state,created_at,completed_at,retain_until)VALUES(?,?,?, ?,7,0,'complete',?,?,?)").run(OP,ID,'b'.repeat(32),'c'.repeat(64),t,t,t+authority.PRIVACY_REPLAY);for(const [id,op]of[[ID,'d'.repeat(32)],[OTHER,'e'.repeat(32)]])db.prepare("INSERT INTO privacy_provider_messages(operation_id,purpose,subjects,channel_id,message_id,state,cleanup_requested,created_at,updated_at,retain_until)VALUES(?,'review',?,?,?,'known',1,?,?,?)").run(op,JSON.stringify([{id,g:null}]),CHANNEL,MSG,t,t,t+authority.PRIVACY_REPLAY);const ownCookie=(await core.sessionCookie(env(),ID,7)).split(';')[0],exportResponse=await load('site-export').exportMyData(new Request('https://guild.example/api/me/export',{headers:{Cookie:ownCookie}}),env(),raw('SELECT * FROM site_users')),exportBody=await exportResponse.json(),wire=JSON.stringify(exportBody);check('actual own-data copy includes lifecycle control coverage without other accounts/provider pointers/proof digests',exportResponse.status===200&&exportBody.privacyLifecycle?.erasureRequests.rows.length===1&&exportBody.privacyLifecycle?.providerCleanup.rows.length===1&&!wire.includes(OTHER)&&!wire.includes(MSG)&&!wire.includes(CHANNEL)&&!wire.includes('c'.repeat(64))&&exportBody.privacyLifecycle.allCopiesErased===false);
 const roster=load('roster'),roleBudget=load('roles').callBudget;
 for(const replacePhysical of [false,true]){t=reset();const old='d'.repeat(32);db.prepare('INSERT INTO members(discord_id)VALUES(?)').run(ID);db.prepare("INSERT INTO privacy_subjects(subject_id,generation,state,revision,created_at,updated_at)VALUES(?,?,'active',1,?,?)").run(ID,old,t,t);db.prepare("INSERT INTO roster_snapshots(id,exported_at,received_at,source,member_count,trusted,complete,first_received_at)VALUES(1,?,?,'fixture',1,1,1,?)").run(t,t,t);db.prepare("INSERT INTO roster_members(snapshot_id,name_key,name,guid)VALUES(1,'fixture name','Fixture Name','Player-0-00000001')").run();db.prepare("INSERT INTO roster_effect_runs(id,snapshot_id,removals,created_at,derived_at,items)VALUES(1,1,0,?,?,1)").run(t,t);db.prepare("INSERT INTO roster_effects(run_id,seq,kind,name_key,name,discord_id,guid,subject_generation)VALUES(1,0,'promote','fixture name','Fixture Name',?,'Player-0-00000001',?)").run(ID,old);const selected=raw('SELECT 1 AS run,* FROM roster_effects');db.prepare("INSERT INTO characters(name_key,name,discord_id,status,bound_at,source,guid)VALUES('fixture name','Fixture Name',?,'verified',?,'fixture','Player-0-00000001')").run(ID,t);
 // Actual signed request closes OLD. The explicit fixture retirement boundary models completed local
 // disposal before actual admitted OAuth creates NEW; no provider/removal completion is inferred here.
 await admission();db.prepare("UPDATE privacy_subjects SET state='retired',erased_at=?,retain_until=?+31622400 WHERE subject_id=?").run(t,t,ID);db.prepare("UPDATE privacy_serving_jobs SET state='complete',completed_at=? WHERE subject_id=?").run(t,ID);const retired=await authority.readPrivacySubject(env(),ID);await authority.admittedPrivacyOAuthWrite(env(),ID,retired,t+1,env().DB.prepare('UPDATE site_users SET session_version=7 WHERE discord_id=?1 RETURNING session_version').bind(ID));if(replacePhysical)db.prepare('UPDATE roster_effects SET subject_generation=? WHERE run_id=1 AND seq=0').run(raw('SELECT generation FROM privacy_subjects').generation);before=snapshot();const response=await roster.testOnlyApplyEffect(env(),1,selected,'fixture-nonce',roleBudget(env()),{items:[]});check('selected roster generation '+(replacePhysical?'cannot adopt reused fresh physical item':'cannot consume after retired→new OAuth')+'; no local/provider effects',response==='refused'&&before===snapshot()&&calls.length===0);}
 // Current source's old-schema runtime upgrade, including additive physical column order.
 reset(true);db.exec('DROP INDEX community_restriction_cases_retain');db.exec('ALTER TABLE community_restriction_cases DROP COLUMN retain_until');db.exec('ALTER TABLE roster_effects DROP COLUMN subject_generation');const schema=load('schema');schema.forgetSchemaCheck();await schema.ensureSchema(env());schema.forgetSchemaCheck();await schema.ensureSchema(env());check('actual runtime old-schema restriction/roster-generation/member-activity upgrades are safe twice',rows('PRAGMA table_info(community_restriction_cases)').some(c=>c.name==='retain_until')&&rows('PRAGMA table_info(roster_effects)').some(c=>c.name==='subject_generation')&&rows('PRAGMA table_info(members)').some(c=>c.name==='activity_at')&&await catalog.servingPrivacyCatalogCurrent(env()));
 check('all actually loaded source bytes stayed unchanged during qualification',Array.from(pins).every(([file,b])=>fs.readFileSync(file).equals(b)));
 console.log(`${passes}/${checks} actual privacy/role/message integration checks passed; no real accounts/provider effects`);db.close();if(passes!==checks)process.exitCode=1;
})().catch(e=>{console.error('privacy integration stopped:',e.stack);process.exitCode=1;});
