// Execute the real browser module with real Ed25519 keys and a DOM/media/storage boundary shim.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const {webcrypto}=require('node:crypto');let n=0;const check=(s,v)=>{assert.ok(v,s);n++;console.log('PASS '+s);};
class Element{constructor(){this.value='';this.textContent='';this.children=[];this.disabled=false;this.videoWidth=640;this.videoHeight=480;this.listeners={};}append(...x){this.children.push(...x);}replaceChildren(...x){this.children=x;}addEventListener(n,f){this.listeners[n]=f;}async play(){}getContext(){return{drawImage(){},getImageData:()=>({data:new Uint8ClampedArray(this.width*this.height*4)})};}}
const ids=['status','request','check','enroll','revoke','challenge','automatic-lease','stop','scan','sign','submit','rank-sync','wire','guid','request-code','game-command','video','canvas','review','operations','recover','receipts'];
async function fixture(){const el=Object.fromEntries(ids.map(i=>[i,new Element()])),data=new Map(),calls=[],events={},timers=[];let worker,stops=0,hold=false,expires=Date.now()/1000|0;
 const pair=await webcrypto.subtle.generateKey('Ed25519',false,['sign','verify']),keyId='a'.repeat(32),nonce='b'.repeat(32),code='c'.repeat(32),signer='400000000000000001',requester='400000000000000002',guid='Player-1234-00000001',operation='d'.repeat(32),revision='forever-beta-pvp2-v1';data.set('current',{id:keyId,privateKey:pair.privateKey});
 const lease={nonce,expiresAt:expires+300,mode:'automatic',maxProofs:10,signerGuid:guid};const wire=['OLG1',nonce,code,'Player-1234-00000002',guid,expires,'70205','16001','Other Member','OLYMPUS','Classic Beta PvP 2',7,1,'Member'].join('|');
 const indexedDB={open(){const r={};queueMicrotask(()=>{r.result={close(){},transaction(){const t={};t.objectStore=()=>({get(k){const q={};queueMicrotask(()=>{q.result=data.get(k);q.onsuccess?.();t.oncomplete?.();});return q;},put(v,k){const q={};queueMicrotask(()=>{data.set(k,v);q.onsuccess?.();t.oncomplete?.();});return q;},delete(k){const q={};queueMicrotask(()=>{data.delete(k);q.onsuccess?.();t.oncomplete?.();});return q;}});return t;}};r.onsuccess();});return r;}};
 const media={getTracks:()=>[{stop(){stops++;}}]};const fetch=async(url,init={})=>{const p=String(url).split('/api/qr/')[1],body=init.body?JSON.parse(init.body):null;calls.push({p,body});let value;
 if(p==='profile')value={phase:1,requires:'Native High Council only'};
 else if(p==='automatic-lease')value=lease;
 else if(p==='prepare')value={requester,signer,keyId,mode:'automatic',remaining:10,expiresAt:lease.expiresAt,signerGuid:guid,profile:{revision,guild:'OLYMPUS',realm:'Classic Beta PvP 2'}};
 else if(p==='proof'){const canonical=new TextEncoder().encode(JSON.stringify(['OLY-P1',keyId,requester,signer,revision,body.wire]));assert.ok(await webcrypto.subtle.verify('Ed25519',pair.publicKey,Buffer.from(body.signature,'base64url'),canonical));value={operations:[operation],remaining:[],leaseRemaining:9,outcomes:[{operationId:operation,state:hold?'unknown':'settled',reason:hold?'provider_outcome_unknown':'confirmed'}]};}
 else if(p==='settle')value={operationId:operation,state:'settled',reason:'fresh_server_confirmed'};
 else if(p==='receipts')value={receipts:[{proofId:'f'.repeat(32),code,operations:[{operationId:operation,state:'unknown',reason:'provider_outcome_unknown'}]}]};
 else if(p==='cancel-challenge')value={cancelled:true};else throw Error('unexpected browser request '+p);
 return new Response(JSON.stringify(value),{headers:{'Content-Type':'application/json'}});};
 const context={document:{getElementById:i=>el[i],createElement:()=>new Element()},window:{addEventListener:(n,f)=>events[n]=f},indexedDB,crypto:webcrypto,CryptoKey:globalThis.CryptoKey,navigator:{mediaDevices:{getDisplayMedia:async()=>media}},Worker:class{constructor(url){assert.equal(url,'/static/qr-phase1-decoder.js');worker=this;}terminate(){this.terminated=true;}postMessage(){}},fetch,TextEncoder,Uint8Array,Uint8ClampedArray,Map,Set,Date,performance:{now:()=>0},setTimeout:f=>{timers.push(f);},btoa:x=>Buffer.from(x,'binary').toString('base64'),console};vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(__dirname,'../public/static/qr-phase1.mjs'),'utf8'),context);
 const wait=async()=>{for(let i=0;i<25;i++)await new Promise(r=>setTimeout(r,2));};await wait();return{el,calls,data,events,lease,wire,wait,worker:()=>worker,stops:()=>stops,hold:()=>{hold=true;}};}
(async()=>{
 let f=await fixture();check('availability is shown through real status DOM',f.el.status.textContent.includes('High Council'));f.el.wire.value=f.wire;await f.el.sign.onclick();check('attended path visibly reviews distinct actors and enables submit',f.el.review.textContent.includes('400000000000000002')&&!f.el.submit.disabled&&!f.calls.some(c=>c.p==='proof'));f.el.wire.listeners.input();check('editing observation clears reviewed signature',f.el.submit.disabled);
 f=await fixture();await f.el['automatic-lease'].onclick();check('automatic mode requires explicit opt-in endpoint and shows exact command',f.calls.some(c=>c.p==='automatic-lease'&&c.body.optIn===true)&&f.el['game-command'].textContent.includes(f.lease.nonce));await f.el.scan.onclick();f.worker().onmessage({data:{text:f.wire}});await f.wait();check('matching captured observation signs real Ed25519 and submits without per-proof click',f.calls.filter(c=>c.p==='proof').length===1&&f.el.status.textContent.includes('9 codes remain'));f.worker().onmessage({data:{text:f.wire}});await f.wait();check('duplicate on-screen observation is locally suppressed',f.calls.filter(c=>c.p==='proof').length===1);
 const wrong=f.wire.replace(f.lease.nonce,'e'.repeat(32));f.worker().onmessage({data:{text:wrong}});await f.wait();check('other challenge is never automatically signed',f.calls.filter(c=>c.p==='prepare').length===1);
 await f.el.stop.onclick();check('stop closes media and cancels server challenge',f.stops()>0&&f.calls.some(c=>c.p==='cancel-challenge'&&c.body.nonce===f.lease.nonce));
 f=await fixture();f.hold();await f.el['automatic-lease'].onclick();await f.el.scan.onclick();f.worker().onmessage({data:{text:f.wire}});await f.wait();check('unknown outcome stops automatic scanner instead of reposting',f.calls.filter(c=>c.p==='proof').length===1&&f.worker().terminated&&f.el.status.textContent.includes('held'));const button=f.el.operations.children[0].children[1];await button.onclick();check('visible reconcile control sends GET-only settlement mode',f.calls.find(c=>c.p==='settle').body.reconcileOnly===true);
 f=await fixture();await f.el['automatic-lease'].onclick();await f.el.scan.onclick();f.events.pagehide();check('pagehide clears local signing and camera track',f.stops()>0&&f.el.wire.value==='');
 check('real browser private key remains nonextractable',f.data.get('current').privateKey.extractable===false);
 f=await fixture();await f.el.recover.onclick();check('reload recovery reads own receipts without proof replay or role write',f.calls.some(c=>c.p==='receipts')&&!f.calls.some(c=>c.p==='proof'||c.p==='settle-batch')&&f.el.receipts.children.length===1);await f.el.receipts.children[0].children[1].children[1].onclick();check('recovered unknown operation uses deliberate GET-only reconciliation',f.calls.find(c=>c.p==='settle').body.reconcileOnly===true);
 console.log(`${n}/${n} browser QR checks passed`);
})().catch(e=>{console.error(e);process.exitCode=1;});
