// Real TypeScript, serving authority and real SQLite. Only Discord network is simulated.
const fs=require('fs'),path=require('path'),ts=require('typescript'),assert=require('node:assert/strict');
const {DatabaseSync}=require('node:sqlite');globalThis.crypto=require('node:crypto').webcrypto;
const root=path.join(__dirname,'..'),peer=process.env.OLYMPUS_PRIVACY_SOURCE;
const cache={};function load(name){name=name.replace(/^\.\//,'');if(cache[name])return cache[name].exports;let file=path.join(root,'src',name+'.ts');if(peer&&(name==='site-core'||!fs.existsSync(file)))file=path.join(peer,name+'.ts');const m={exports:{}};cache[name]=m;const source=fs.readFileSync(file);m.sourcePin={path:file,bytes:source.length,sha256:require('node:crypto').createHash('sha256').update(source).digest('hex')};const code=ts.transpileModule(source.toString('utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;new Function('module','exports','require',code)(m,m.exports,p=>load(p));return m.exports;}
const qr=load('qr-phase1'),role=load('role-settlements'),ranks=load('native-rank-adapter'),ddl=load('qr-phase1-schema').QR_PHASE1_DDL,privacy=load('privacy-serving-schema').PRIVACY_SERVING_SCHEMA;
const signer='400000000000000001',requester='400000000000000002',bot='400000000000000003',guild='400000000000000004',memberRole='400000000000000005';
// Use one original session deadline throughout a fixture; recapturing it across a wall-clock second is a different cookie.
const sg='Player-1234-00000001',rg='Player-1234-00000002',fixtureTime=Math.floor(Date.now()/1000),T=()=>fixtureTime;
let db,env,members,fetches,failWrite,afterLookup,afterWrite,sqlCalls=0;const leader='600000000000000001',officer='600000000000000002',raidLeader='600000000000000003';const roles=[{id:guild,position:0,permissions:'0',managed:false},{id:memberRole,position:1,permissions:'0',managed:false},{id:'400000000000000006',position:17,permissions:'268435456',managed:false},{id:leader,position:18,permissions:'1024',managed:false},{id:officer,position:16,permissions:'1024',managed:false},{id:raidLeader,position:15,permissions:'1024',managed:false},...Array.from({length:10},(_,i)=>({id:String(500000000000000000n+BigInt(i)),position:2+i,permissions:'0',managed:false}))];
// Discord MANAGE_ROLES is bit28, not MANAGE_CHANNELS bit5. The central writer must check this actual bit.
const D1=()=>{const prep=sql=>{let p=[];const x={bind(...v){p=v;return x;},first:async()=>{sqlCalls++;return db.prepare(sql).get(...p)||null;},all:async()=>{sqlCalls++;return {results:db.prepare(sql).all(...p)};},run:async()=>x.exec(),exec(){sqlCalls++;const s=db.prepare(sql);if(/^\s*(SELECT|WITH)/.test(sql)||/RETURNING/.test(sql))return {results:s.all(...p),meta:{changes:0}};const r=s.run(...p);return {results:[],meta:{changes:Number(r.changes)}};}};return x;};return {prepare:prep,batch:async(stmts)=>{db.exec('BEGIN');try{const out=stmts.map(s=>s.exec());db.exec('COMMIT');return out;}catch(e){db.exec('ROLLBACK');throw e;}}};};
function reset(){sqlCalls=0;db=new DatabaseSync(':memory:');db.exec(fs.readFileSync(path.join(root,'schema.sql'),'utf8'));for(const sql of [...privacy,...ddl])db.exec(sql);env={DB:D1(),GUILD_ID:guild,SITE_GUILD_ID:guild,ROLE_GUILD_MEMBER:memberRole,ROLE_GUILD_LEADER:leader,ROLE_OFFICER:officer,ROLE_RAID_LEADER:raidLeader,DISCORD_BOT_TOKEN:'test-only',DISCORD_APP_ID:bot,QR_PHASE1_ENABLED:'true'};members={[signer]:[],[requester]:[],[bot]:['400000000000000006']};fetches=[];failWrite=false;afterLookup=null;afterWrite=null;
 for(const [id,guid,name] of [[signer,sg,'Fern Melder'],[requester,rg,'Other Member']]){db.prepare('INSERT INTO members(discord_id)VALUES(?)').run(id);db.prepare("INSERT INTO privacy_subjects(subject_id,generation,state,revision,created_at,updated_at)VALUES(?,?,'active',1,?,?)").run(id,id===signer?'a'.repeat(32):'b'.repeat(32),T(),T());db.prepare('INSERT INTO site_users(discord_id,first_login,last_login,session_version,in_server)VALUES(?,?,?,1,1)').run(id,T(),T());}
 db.prepare("INSERT INTO characters(name_key,name,discord_id,status,bound_at,guid)VALUES('fern melder','Fern Melder',?,'member',?,?)").run(signer,T(),sg);
 db.prepare("INSERT INTO roster_snapshots(id,exported_at,received_at,source,member_count,content_hash,complete,trusted)VALUES(1,?,?,'test',2,?,1,1)").run(T(),T(),'test');
 db.prepare("INSERT INTO roster_members(snapshot_id,name_key,name,rank,rank_index,guid)VALUES(1,'fern melder','Fern Melder','High Council',1,?)").run(sg);
 db.prepare("INSERT INTO roster_members(snapshot_id,name_key,name,rank,rank_index,guid)VALUES(1,'other member','Other Member','Member',7,?)").run(rg);
}
globalThis.fetch=async(url,init={})=>{const u=new URL(String(url)),method=init.method||'GET';fetches.push(method+' '+u.pathname);let v;
 if(u.pathname.endsWith('/users/@me'))v={id:bot};else if(u.pathname.endsWith('/roles')&&method==='GET')v=roles;else{const m=u.pathname.match(/\/members\/(\d+)(?:\/roles\/(\d+))?$/);if(!m)throw Error('unexpected network');if(m[2]){if(failWrite)throw Error('lost response');members[m[1]]=method==='PUT'?[...members[m[1]],m[2]]:members[m[1]].filter(r=>r!==m[2]);if(afterWrite){const f=afterWrite;afterWrite=null;await f();}return new Response(null,{status:204});}if(members[m[1]]===undefined)return new Response('{}',{status:404});v={roles:members[m[1]],user:{id:m[1]}};if(afterLookup){const f=afterLookup;afterLookup=null;f();}}
 return new Response(JSON.stringify(v),{headers:{'Content-Type':'application/json'}});};
let n=0;function check(name,fn){assert.ok(fn,name);n++;console.log('PASS '+name);}async function rejects(name,fn,match){let e;try{await fn();}catch(x){e=x;}check(name,e&&(!match||String(e).includes(match)));}
async function setup(){reset();const pair=await crypto.subtle.generateKey({name:'Ed25519'},false,['sign','verify']),pub=qr.base64url(new Uint8Array(await crypto.subtle.exportKey('raw',pair.publicKey)));const k=await qr.enrollKey(env,signer,sg,pub,{v:1,e:T()+600,g:'a'.repeat(32)}),c=await qr.issueChallenge(env,signer,k.id,1,T()+600),v=await qr.createWebsiteRequest(env,requester,{v:1,e:T()+600,g:'b'.repeat(32)});const wire=['OLG1',c.nonce,v.code,rg,sg,T(),'70205','16001','Other Member','OLYMPUS','Classic Beta PvP 2','7','1','Member'].join('|');const sig=qr.base64url(new Uint8Array(await crypto.subtle.sign('Ed25519',pair.privateKey,qr.attestationBytes(k.id,requester,signer,wire))));return {pair,k,c,v,wire,input:{keyId:k.id,signature:sig,wire}};}
(async()=>{
 let x=await setup();const p=await qr.ingestAttestation(env,signer,{v:1,e:T()+600,g:'a'.repeat(32)},x.input);check('real Ed25519 proof consumes both code/challenge and links exact GUID',p.state==='proved'&&db.prepare('SELECT used_at FROM verification_requests').get().used_at>0&&db.prepare('SELECT discord_id FROM characters WHERE guid=?').get(rg).discord_id===requester);
 await rejects('replay cannot consume code twice',()=>qr.ingestAttestation(env,signer,{v:1,e:T()+600,g:'a'.repeat(32)},x.input));
 x=await setup();await rejects('other Discord actor cannot submit',()=>qr.ingestAttestation(env,requester,{v:1,e:T()+600,g:'a'.repeat(32)},x.input));
 x=await setup();await rejects('mutated observed realm rejected',()=>qr.ingestAttestation(env,signer,{v:1,e:T()+600,g:'a'.repeat(32)},{...x.input,wire:x.wire.replace('Classic Beta PvP 2','Classic Beta PvP2')}));
 x=await setup();await rejects('unbound rank/name signature rejected',()=>qr.ingestAttestation(env,signer,{v:1,e:T()+600,g:'a'.repeat(32)},{...x.input,wire:x.wire.replace('Other Member','Forged Name')}));
 x=await setup();await qr.revokeKey(env,signer,x.k.id,{v:1,e:T()+600,g:'a'.repeat(32)});await rejects('revoked browser key cannot submit',()=>qr.ingestAttestation(env,signer,{v:1,e:T()+600,g:'a'.repeat(32)},x.input));
 x=await setup();db.prepare("UPDATE privacy_subjects SET state='retiring' WHERE subject_id=?").run(signer);await rejects('signer retirement invalidates key',()=>qr.ingestAttestation(env,signer,{v:1,e:T()+600,g:'a'.repeat(32)},x.input));
 x=await setup();db.prepare("UPDATE privacy_subjects SET generation=? WHERE subject_id=?").run('c'.repeat(32),requester);await rejects('requester generation change rolls back whole proof',()=>qr.ingestAttestation(env,signer,{v:1,e:T()+600,g:'a'.repeat(32)},x.input));check('rollback leaves code unused',db.prepare('SELECT used_at FROM verification_requests').get().used_at===null);
 x=await setup();db.prepare('UPDATE site_users SET session_version=2 WHERE discord_id=?').run(signer);await rejects('signer session version consumed in batch',()=>qr.ingestAttestation(env,signer,{v:1,e:T()+600,g:'a'.repeat(32)},x.input));
 x=await setup();db.prepare('UPDATE councillor_challenges SET expires_at=?').run(T()-1);await rejects('expired challenge rejected',()=>qr.ingestAttestation(env,signer,{v:1,e:T()+600,g:'a'.repeat(32)},x.input));
 reset();db.prepare("UPDATE roster_members SET rank='Officer',rank_index=1 WHERE guid=?").run(sg);await rejects('actual beta Officer index1 is never High Council',()=>qr.enrollKey(env,signer,sg,'A'.repeat(43),{v:1,e:T()+600,g:'a'.repeat(32)}), 'high_council');
 reset();db.prepare("UPDATE roster_members SET rank='Officer',rank_index=2 WHERE guid=?").run(sg);await rejects('future Officer index2 also excluded',()=>qr.enrollKey(env,signer,sg,'A'.repeat(43),{v:1,e:T()+600,g:'a'.repeat(32)}));
 x=await setup();db.prepare('UPDATE roster_snapshots SET exported_at=?').run(T()-7200);const proof=await qr.ingestAttestation(env,signer,{v:1,e:T()+600,g:'a'.repeat(32)},x.input);check('unrenewed lease allows fresh councillor observation with owner watcher offline',proof.state==='proved');
 const ops=await role.queueProofRoles(env,proof.proofId);let s=await role.settleRoleIntent(env,ops[0]);check('durable central writer settles member role',s.state==='settled'&&members[requester].includes(memberRole));check('actual request cap and no automatic retry',fetches.filter(f=>f.includes('/roles/')).length===1&&fetches.length<=12);
 x=await setup();const pp=await qr.ingestAttestation(env,signer,{v:1,e:T()+600,g:'a'.repeat(32)},x.input),ids=await role.queueProofRoles(env,pp.proofId);failWrite=true;s=await role.settleRoleIntent(env,ids[0]);check('lost PUT response remains unknown',s.state==='unknown');let writes=fetches.filter(f=>f.startsWith('PUT')).length;await role.settleRoleIntent(env,ids[0]);check('unknown intent never repeats PUT',fetches.filter(f=>f.startsWith('PUT')).length===writes);failWrite=false;members[requester]=[memberRole];s=await role.settleRoleIntent(env,ids[0],true);check('fresh GET explicitly reconciles landed outcome',s.state==='settled');
 const five=ranks.parseNativeRoleMap(JSON.stringify({profile:'beta-five',roles:Array.from({length:5},(_,i)=>String(500000000000000000n+BigInt(i)))}));check('beta Officer1 maps to Officer role, not HC',ranks.mappedNativeRole('Officer',1,five)===five.roles[1]);await rejects('contradictory profile name/index refused',async()=>ranks.mappedNativeRole('High Council',1,five));
 x=await setup();const cp=await qr.ingestAttestation(env,signer,{v:1,e:T()+600,g:'a'.repeat(32)},x.input);env.QR_RANK_MAPPING_ENABLED='true';env.QR_NATIVE_ROLE_MAP=JSON.stringify(five);await rejects('ten-rank proof cannot use beta-five ordinal map',()=>role.queueProofRoles(env,cp.proofId));
 check('default OFF produces no network or generation bootstrap',(()=>{const z={...env,QR_PHASE1_ENABLED:undefined};try{qr.requireQr(z);return false;}catch{return true;}})());
 reset();await rejects('expired original cookie cannot enroll',()=>qr.enrollKey(env,signer,sg,'A'.repeat(43),{v:1,e:T()-1,g:'a'.repeat(32)}));check('expired enrollment writes no key',db.prepare('SELECT COUNT(*) AS n FROM councillor_keys').get().n===0);
 reset();await rejects('old cookie generation never repairs itself from current row',()=>qr.enrollKey(env,signer,sg,'A'.repeat(43),{v:1,e:T()+600,g:'c'.repeat(32)}));
 reset();afterLookup=()=>db.prepare('UPDATE site_users SET session_version=2 WHERE discord_id=?').run(signer);await rejects('session rotated during enrollment lookup is consumed by SQL',()=>qr.enrollKey(env,signer,sg,'A'.repeat(43),{v:1,e:T()+600,g:'a'.repeat(32)}));
 x=await setup();let q=await qr.ingestAttestation(env,signer,{v:1,e:T()+600,g:'a'.repeat(32)},x.input),op=await role.queueProofRoles(env,q.proofId);afterWrite=()=>db.prepare("UPDATE privacy_subjects SET state='retiring' WHERE subject_id=?").run(requester);let start=fetches.length;s=await role.settleRoleIntent(env,op[0]);check('landed PUT losing generation gets separate durable one-use removal',s.state==='held'&&!members[requester].includes(memberRole)&&db.prepare("SELECT COUNT(*) AS n FROM role_settlements WHERE purpose='grant_compensation' AND state='settled'").get().n===1);check('compensation is fully reserved inside8 actual requests',fetches.length-start===8);
 reset();env.QR_PHASE1_ENABLED='false';env.QR_RANK_MAPPING_ENABLED='true';env.QR_NATIVE_ROLE_MAP=JSON.stringify(five);db.prepare("UPDATE roster_members SET rank='Officer',rank_index=1 WHERE guid=?").run(sg);db.prepare("UPDATE roster_members SET rank_index=3 WHERE guid=?").run(rg);const nativeOps=await role.queueRosterRankRoles(env,signer,1,'a'.repeat(32));check('actual beta five creates exact named cosmetic intents',nativeOps.length===5);const actor={id:signer,v:1,e:T()+600,g:'a'.repeat(32)};for(let j=0;j<nativeOps.length;j+=2){const settled=await role.settleOwnedRoleBatch(env,nativeOps.slice(j,j+2),actor);check('bounded automatic native batch '+j,settled.outcomes.every(s=>s.state==='settled')&&settled.attempts<=16);}check('native beta Officer receives Officer label only',members[signer].includes(five.roles[1])&&!members[signer].includes(five.roles[0]));
 reset();env.QR_PRIVILEGED_RANK_MAPPING_ENABLED='true';db.prepare("UPDATE roster_members SET rank='Officer',rank_index=1 WHERE guid=?").run(sg);db.prepare("UPDATE roster_members SET rank_index=3 WHERE guid=?").run(rg);let staffOps=await role.queueRosterRankRoles(env,signer,1,'a'.repeat(32));check('separate beta map derives actual Officer target from exact name/index',staffOps.length===1&&db.prepare('SELECT role_id FROM role_settlements WHERE id=?').get(staffOps[0]).role_id===officer);check('enabled exact staff map actually dispatches Officer grant',(await role.settleOwnedRoleBatch(env,staffOps,actor)).outcomes[0].state==='settled'&&members[signer].includes(officer));
 db.prepare("UPDATE roster_members SET rank='Veteran',rank_index=2 WHERE guid=?").run(sg);db.prepare('INSERT INTO roster_snapshots SELECT 2,exported_at,received_at,source,member_count,content_hash,trusted,complete,first_received_at FROM roster_snapshots WHERE id=1').run();db.prepare('INSERT INTO roster_members SELECT 2,name_key,name,rank,rank_index,level,class,public_note,officer_note,guid,last_online FROM roster_members WHERE snapshot_id=1').run();staffOps=await role.queueRosterRankRoles(env,signer,2,'a'.repeat(32));check('demotion creates only previous bot-managed staff removal',staffOps.length===1&&db.prepare('SELECT desired FROM role_settlements WHERE id=?').get(staffOps[0]).desired===0);check('demotion removes prior managed Officer before any replacement',(await role.settleOwnedRoleBatch(env,staffOps,actor)).outcomes[0].state==='settled'&&!members[signer].includes(officer));
 reset();env.QR_PRIVILEGED_RANK_MAPPING_ENABLED='true';members[signer]=[officer];check('unrelated manually assigned staff role is not stripped',(await role.queueRosterRankRoles(env,signer,1,'a'.repeat(32))).length===0);const pm=ranks.privilegedNativeMap('ten-rank',env);check('HC and Officer Alt never infer privileged appointments',pm.wanted('High Council',1)===null&&pm.wanted('Officer Alt',3)===null&&pm.wanted('Raid Leader',4)===raidLeader);await rejects('privileged map refuses contradictory beta High Council ordinal',async()=>ranks.privilegedNativeMap('beta-five',env).wanted('High Council',1));
 reset();env.QR_PRIVILEGED_RANK_MAPPING_ENABLED='true';db.prepare("UPDATE roster_members SET rank='Guild Master',rank_index=0 WHERE guid=?").run(sg);db.prepare("UPDATE roster_members SET rank='Member',rank_index=3 WHERE guid=?").run(rg);staffOps=await role.queueRosterRankRoles(env,signer,1,'a'.repeat(32));check('Guild Leader above bot holds without a PUT',(await role.settleOwnedRoleBatch(env,staffOps,actor)).outcomes[0].state==='held'&&!fetches.some(x=>x.startsWith('PUT')));await rejects('native dispatch never recaptures rotated privacy generation',()=>role.queueRosterRankRoles(env,signer,1,'c'.repeat(32)));
 reset();const ep={purpose:'account_erasure',subject:requester,subjectGeneration:'b'.repeat(32),operationId:'d'.repeat(32),requestDigest:'e'.repeat(64)};const eraseJob=()=>{db.prepare("UPDATE privacy_subjects SET state='retiring' WHERE subject_id=?").run(requester);db.prepare("INSERT INTO privacy_serving_jobs(operation_id,subject_id,subject_generation,request_digest,original_session_version,original_session_expires,state,created_at,retain_until) VALUES(?,?,?,?,1,?,'waiting_role',?,?)").run(ep.operationId,requester,ep.subjectGeneration,ep.requestDigest,T()+600,T(),T()+31622400);};eraseJob();members[requester]=[memberRole];const er=await role.settleErasure(env,ep);check('erasure consumes real durable retiring job and confirms fresh absence',er.state==='removed'&&db.prepare(`SELECT (${role.ACCOUNT_ERASURE_ROLE_SETTLED_SQL}) AS ok`).get(ep.operationId,requester,ep.subjectGeneration,ep.requestDigest).ok===1);
 reset();eraseJob();members[requester]=[memberRole];failWrite=true;const eu=await role.settleErasure(env,ep);writes=fetches.filter(f=>f.startsWith('DELETE')).length;await role.settleErasure(env,ep);check('unknown erasure never repeats DELETE',eu.state==='unknown'&&fetches.filter(f=>f.startsWith('DELETE')).length===writes);failWrite=false;members[requester]=[];check('unknown erasure reconciles through current fresh GET only',(await role.settleErasure(env,ep)).state==='absent');
 reset();members[requester]=[memberRole];check('missing erasure job cannot mint removal authority',(await role.settleErasure(env,ep)).state==='held'&&fetches.length===0);
 const data=load('qr-phase1-data');reset();const empty=await env.DB.batch(data.qrErasureStatements(env,requester));check('explicit five-family eraser succeeds in same native batch',empty.length===6);
 reset();db.prepare('UPDATE members SET banned=1 WHERE discord_id=?').run(requester);members[requester]=[memberRole];db.prepare('DELETE FROM site_users WHERE discord_id=?').run(requester);const rem=await role.settleVerifiedRemoval(env,requester,'ban');check('source-qualified accountless ban removal has durable receipt',rem.state==='settled'&&!members[requester].includes(memberRole));
 reset();members[requester]=[memberRole];check('caller removal purpose never invents a ban',(await role.settleVerifiedRemoval(env,requester,'ban')).state==='held'&&!fetches.some(f=>f.startsWith('DELETE')));
 reset();const blocker='500000000000000003';env.BLOCKING_ROLE_IDS=blocker;members[requester]=[memberRole,blocker];check('blocking removal rereads current server restriction',(await role.settleVerifiedRemoval(env,requester,'blocking_role')).state==='settled');
 reset();env.COOKIE_SECRET='synthetic-cookie-key';const core=load('site-core'),http=load('qr-phase1-route');
 const cookie=async id=>(await core.sessionCookie(env,id,1)).split(';')[0],call=async(id,p,b)=>http.handleQrApi(new Request('https://olympus.example/api/qr/'+p,{method:b===undefined?'GET':'POST',headers:{Cookie:await cookie(id),Origin:'https://olympus.example','X-Olympus':'2','Content-Type':'application/json'},body:b===undefined?undefined:JSON.stringify(b)}),env);
 const hp=await crypto.subtle.generateKey('Ed25519',false,['sign','verify']);let response=await call(signer,'enroll',{guid:sg,publicKey:qr.base64url(new Uint8Array(await crypto.subtle.exportKey('raw',hp.publicKey)))});check('actual HTTP route enrolls only signed current-generation session',response.status===200);const hk=await response.json();response=await call(signer,'challenge',{keyId:hk.id});const hc=await response.json(),hr=await(await call(requester,'request',{})).json();const hw=['OLG1',hc.nonce,hr.code,rg,sg,T(),'70205','16001','Other Member','OLYMPUS','Classic Beta PvP 2','7','1','Member'].join('|');const hs=qr.base64url(new Uint8Array(await crypto.subtle.sign('Ed25519',hp.privateKey,qr.attestationBytes(hk.id,requester,signer,hw))));response=await call(signer,'proof',{keyId:hk.id,signature:hs,wire:hw});const auto=await response.json();check('real HTTP proof automatically settles admitted member effect',response.status===202&&auto.outcomes[0].state==='settled'&&members[requester].includes(memberRole)&&auto.remaining.length===0);
 response=await http.handleQrApi(new Request('https://olympus.example/api/qr/request',{method:'POST',headers:{Cookie:await cookie(requester),Origin:'https://evil.example','X-Olympus':'2'},body:'{}'}),env);check('cross-origin request does not mint code',response.status===403);
 response=await http.handleQrApi(new Request('https://olympus.example/api/qr/request',{method:'POST',body:'{}'}),env);check('unsigned request cannot use browser enrollment',response.status===401);
 env.QR_PHASE1_ENABLED=undefined;response=await http.handleQrApi(new Request('https://olympus.example/api/qr/profile'),env);check('default OFF HTTP path refuses before authority query',response.status===409);
 reset();env.DISCORD_APP_ID='400000000000000007';const dk=await crypto.subtle.generateKey('Ed25519',false,['sign','verify']);env.DISCORD_PUBLIC_KEY=Buffer.from(await crypto.subtle.exportKey('raw',dk.publicKey)).toString('hex');db.prepare('DELETE FROM privacy_subjects WHERE subject_id=?').run(requester);db.prepare('DELETE FROM site_users WHERE discord_id=?').run(requester);
 const signedInteraction=async(app=env.DISCORD_APP_ID)=>{const raw=JSON.stringify({type:2,application_id:app,guild_id:guild,data:{name:'olympus-qr'},member:{user:{id:requester}}}),timestamp=String(T()),signature=Buffer.from(await crypto.subtle.sign('Ed25519',dk.privateKey,new TextEncoder().encode(timestamp+raw))).toString('hex');return {raw,request:new Request('https://bot.example/interactions',{method:'POST',headers:{'X-Signature-Ed25519':signature,'X-Signature-Timestamp':timestamp},body:raw})};};let interaction=await signedInteraction();const av=await qr.createInteractionRequest(env,interaction.request,interaction.raw);check('real signed Discord interaction admits accountless code with captured absence',/^[a-f0-9]{32}$/.test(av.code)&&db.prepare('SELECT subject_generation FROM verification_requests WHERE code=?').get(av.code).subject_generation===null&&!db.prepare('SELECT 1 FROM site_users WHERE discord_id=?').get(requester));interaction=await signedInteraction('400000000000000008');await rejects('valid signature for another application has no QR authority',()=>qr.createInteractionRequest(env,interaction.request,interaction.raw));
 x=await setup();let lease=await qr.issueChallenge(env,signer,x.k.id,1,T()+600,'automatic');const autoInput=async(code=x.v.code)=>{const wire=x.wire.replace(x.c.nonce,lease.nonce).replace(x.v.code,code);return {keyId:x.k.id,wire,signature:qr.base64url(new Uint8Array(await crypto.subtle.sign('Ed25519',x.pair.privateKey,qr.attestationBytes(x.k.id,requester,signer,wire))))};};
 check('opt-in lease is server bounded to original five minutes and ten observations',lease.mode==='automatic'&&lease.maxProofs===10&&lease.expiresAt===db.prepare('SELECT MIN(created_at+300,session_expires) AS deadline FROM councillor_challenges WHERE nonce=?').get(lease.nonce).deadline);let input=await autoInput();const same=await Promise.allSettled([qr.ingestAttestation(env,signer,{v:1,e:T()+600,g:'a'.repeat(32)},input),qr.ingestAttestation(env,signer,{v:1,e:T()+600,g:'a'.repeat(32)},input)]);check('concurrent duplicate scan consumes exactly one code/lease slot',same.filter(x=>x.status==='fulfilled').length===1&&db.prepare('SELECT proofs_used FROM councillor_challenges WHERE nonce=?').get(lease.nonce).proofs_used===1);
 for(let j=1;j<9;j++){const v=await qr.createWebsiteRequest(env,requester,{v:1,e:T()+600,g:'b'.repeat(32)});await qr.ingestAttestation(env,signer,{v:1,e:T()+600,g:'a'.repeat(32)},await autoInput(v.code));}let v1=await qr.createWebsiteRequest(env,requester,{v:1,e:T()+600,g:'b'.repeat(32)}),v2=await qr.createWebsiteRequest(env,requester,{v:1,e:T()+600,g:'b'.repeat(32)});const race=await Promise.allSettled([qr.ingestAttestation(env,signer,{v:1,e:T()+600,g:'a'.repeat(32)},await autoInput(v1.code)),qr.ingestAttestation(env,signer,{v:1,e:T()+600,g:'a'.repeat(32)},await autoInput(v2.code))]);check('tenth-slot race cannot exceed ten proofs or reuse challenge',race.filter(x=>x.status==='fulfilled').length===1&&db.prepare('SELECT proofs_used,used_at FROM councillor_challenges WHERE nonce=?').get(lease.nonce).proofs_used===10&&db.prepare('SELECT used_at FROM councillor_challenges WHERE nonce=?').get(lease.nonce).used_at>0);
 x=await setup();lease=await qr.issueChallenge(env,signer,x.k.id,1,T()+600,'automatic');input=await autoInput();await qr.cancelChallenge(env,signer,lease.nonce,{v:1,e:T()+600,g:'a'.repeat(32)});await rejects('explicit stop cancels further automatic attestations',()=>qr.ingestAttestation(env,signer,{v:1,e:T()+600,g:'a'.repeat(32)},input));
 x=await setup();lease=await qr.issueChallenge(env,signer,x.k.id,1,T()+600,'automatic');input=await autoInput();db.prepare('UPDATE councillor_challenges SET expires_at=? WHERE nonce=?').run(T()-1,lease.nonce);await rejects('expired automatic lease cannot renew itself',()=>qr.ingestAttestation(env,signer,{v:1,e:T()+600,g:'a'.repeat(32)},input));
 x=await setup();q=await qr.ingestAttestation(env,signer,{v:1,e:T()+600,g:'a'.repeat(32)},x.input);op=await role.queueProofRoles(env,q.proofId);env.DISCORD_APP_ID='400000000000000099';check('wrong bot identity holds before any role effect',(await role.settleRoleIntent(env,op[0])).state==='held'&&!fetches.some(x=>x.startsWith('PUT')||x.startsWith('DELETE')));
 x=await setup();q=await qr.ingestAttestation(env,signer,{v:1,e:T()+600,g:'a'.repeat(32)},x.input);op=await role.queueProofRoles(env,q.proofId);afterWrite=()=>{db.prepare("UPDATE privacy_subjects SET state='retiring' WHERE subject_id=?").run(requester);failWrite=true;};s=await role.settleRoleIntent(env,op[0]);check('lost compensating removal preserves both unknown receipts',s.state==='unknown'&&db.prepare("SELECT COUNT(*) AS n FROM role_settlements WHERE state='unknown'").get().n===2);await rejects('unknown role receipt holds whole erasure batch',()=>env.DB.batch(data.qrErasureStatements(env,requester)));check('held erasure preserves proof and no-repeat custody',db.prepare('SELECT COUNT(*) AS n FROM verification_proofs').get().n===1&&db.prepare('SELECT COUNT(*) AS n FROM role_settlements').get().n===2);writes=fetches.filter(x=>x.startsWith('DELETE')).length;failWrite=false;members[requester]=[];s=await role.settleRoleIntent(env,op[0],true);check('explicit compensation reconciliation confirms absence without repeating DELETE',s.state==='held'&&s.reason==='removed_after_admission_changed'&&fetches.filter(x=>x.startsWith('DELETE')).length===writes&&db.prepare("SELECT state FROM role_settlements WHERE purpose='grant_compensation'").get().state==='settled');
 reset();db.prepare('UPDATE members SET banned=1 WHERE discord_id=?').run(requester);members[requester]=[memberRole];failWrite=true;s=await role.settleVerifiedRemoval(env,requester,'ban');check('lost source-qualified removal outcome is durably unknown',s.state==='unknown');db.prepare('UPDATE members SET banned=0 WHERE discord_id=?').run(requester);failWrite=false;members[requester]=[];writes=fetches.filter(x=>x.startsWith('DELETE')).length;s=await role.settleVerifiedRemoval(env,requester,'ban');check('withdrawn cause permits outcome GET only, never repeat DELETE',s.state==='settled'&&fetches.filter(x=>x.startsWith('DELETE')).length===writes);
 x=await setup();afterLookup=()=>db.prepare("INSERT INTO characters(name_key,name,discord_id,status,bound_at,guid)VALUES('stolen','Stolen',?,'member',?,?)").run('400000000000000090',T(),rg);await rejects('cross-subject GUID collision after server await is consumed atomically',()=>qr.ingestAttestation(env,signer,{v:1,e:T()+600,g:'a'.repeat(32)},x.input));check('cross-subject race leaves request unused',db.prepare('SELECT used_at FROM verification_requests').get().used_at===null);
 reset();db.prepare("INSERT INTO characters(name_key,name,discord_id,status,bound_at,guid)VALUES('other member','Other Member',?,'left',?,?)").run(requester,T(),rg);db.prepare('DELETE FROM roster_members WHERE guid=?').run(rg);db.prepare('UPDATE roster_snapshots SET member_count=1').run();members[requester]=[memberRole];s=await role.settleGuildDepartureRole(env,requester,{subjectGeneration:'b'.repeat(32)});check('source-qualified last-character guild departure consumes original generation',s.state==='settled'&&!members[requester].includes(memberRole)&&db.prepare("SELECT subject_generation FROM role_settlements WHERE purpose='guild_departure'").get().subject_generation==='b'.repeat(32));
 reset();members[requester]=[memberRole];check('caller cannot invent guild departure while current roster includes GUID',(await role.settleGuildDepartureRole(env,requester,{subjectGeneration:'b'.repeat(32)})).state==='held'&&!fetches.some(x=>x.startsWith('DELETE')));
 x=await setup();members[requester]=undefined;await rejects('departed requester cannot be linked by a stale website code',()=>qr.ingestAttestation(env,signer,{v:1,e:T()+600,g:'a'.repeat(32)},x.input));
 x=await setup();q=await qr.ingestAttestation(env,signer,{v:1,e:T()+600,g:'a'.repeat(32)},x.input);op=await role.queueProofRoles(env,q.proofId);failWrite=true;await role.settleRoleIntent(env,op[0]);failWrite=false;db.prepare('UPDATE verification_proofs SET expires_at=?').run(T()-1);db.prepare("UPDATE privacy_subjects SET state='retiring' WHERE subject_id=?").run(requester);writes=fetches.filter(x=>x.startsWith('PUT')||x.startsWith('DELETE')).length;s=await role.settleRoleIntent(env,op[0],true);check('past expired grant attempt can close fresh absence without new authority/effect',s.reason==='past_effect_absent'&&fetches.filter(x=>x.startsWith('PUT')||x.startsWith('DELETE')).length===writes);
 // Production privacy may be enabled while QR remains disabled; the original generation must still fence grants.
 reset();env.QR_PHASE1_ENABLED=undefined;env.PRIVACY_ERASURE_ENABLED='true';const servingRoles=load('roles');check('privacy-only activation cannot fall back to legacy grant without original capture',(await servingRoles.grantMemberRole(env,signer,'test','test'))==='held'&&!fetches.some(x=>x.startsWith('PUT')));check('privacy-only activation uses real original-generation central roster grant',(await servingRoles.grantMemberRole(env,signer,'test','test',undefined,undefined,{subjectGeneration:'a'.repeat(32)}))==='granted'&&members[signer].includes(memberRole));
 for(const purpose of ['ban','rename_hold','blocking_role']){reset();members[requester]=[memberRole];if(purpose==='ban')db.prepare('UPDATE members SET banned=1 WHERE discord_id=?').run(requester);if(purpose==='rename_hold')db.prepare("INSERT INTO rename_holds(discord_id,old_name,new_name,char_key,nonce,state,decided_by,decided_at) VALUES(?,'Old','New','other member','fixture','reapply',?,?)").run(requester,signer,T());if(purpose==='blocking_role'){env.BLOCKING_ROLE_IDS='500000000000000003';members[requester].push(env.BLOCKING_ROLE_IDS);}afterLookup=()=>db.prepare('UPDATE privacy_subjects SET generation=? WHERE subject_id=?').run('c'.repeat(32),requester);check(purpose+' removal cannot cross a generation change during provider lookup',(await role.settleVerifiedRemoval(env,requester,purpose)).state==='held'&&!fetches.some(x=>x.startsWith('DELETE')));}
 // Discard the real committed HTTP response, then recover through a fresh read without replaying the proof.
 x=await setup();env.COOKIE_SECRET='synthetic-cookie-key';env.QR_RANK_MAPPING_ENABLED='true';env.QR_NATIVE_ROLE_MAP=JSON.stringify({profile:'ten-rank',roles:roles.slice(6).map(r=>r.id)});const lc=await(await call(signer,'challenge',{keyId:x.k.id})).json(),lv=await(await call(requester,'request',{})).json(),lw=x.wire.replace(x.c.nonce,lc.nonce).replace(x.v.code,lv.code),li={keyId:x.k.id,wire:lw,signature:qr.base64url(new Uint8Array(await crypto.subtle.sign('Ed25519',x.pair.privateKey,qr.attestationBytes(x.k.id,requester,signer,lw))))};const discarded=await call(signer,'proof',li);check('real HTTP lost-response fixture committed proof and left bounded pending intents',discarded.status===202&&db.prepare("SELECT COUNT(*) AS n FROM role_settlements WHERE state='pending'").get().n>0);
 writes=fetches.filter(x=>x.startsWith('PUT')||x.startsWith('DELETE')).length;const recovered=await(await call(signer,'receipts')).json();check('fresh own receipt read recovers all durable IDs with zero provider effects',recovered.receipts.length===1&&recovered.receipts[0].operations.length===11&&fetches.filter(x=>x.startsWith('PUT')||x.startsWith('DELETE')).length===writes);const own=await(await call(requester,'receipts')).json();check('requester can recover same accepted receipt in original generation',own.receipts[0].proofId===recovered.receipts[0].proofId);
 const wanted=db.prepare("SELECT id FROM role_settlements WHERE purpose='verified_native_rank' AND desired=1").get().id;check('caller cannot skip unsettled old rank removals to grant replacement',(await role.settleRoleIntent(env,wanted)).state==='held'&&!members[requester].includes(roles[13].id));
 response=await call(signer,'resume-proof',{proofId:recovered.receipts[0].proofId});check('deliberate resume uses original persisted proof instead of replay',response.status===202&&db.prepare('SELECT COUNT(*) AS n FROM verification_proofs').get().n===1&&db.prepare('SELECT COUNT(*) AS n FROM role_settlements').get().n===11);
 db.prepare('UPDATE privacy_subjects SET generation=? WHERE subject_id=?').run('c'.repeat(32),requester);check('replacement requester generation cannot inherit prior receipt authority',(await(await call(requester,'receipts')).json()).receipts.length===0);
 x=await setup();env.QR_RANK_MAPPING_ENABLED='true';env.QR_PRIVILEGED_RANK_MAPPING_ENABLED='true';env.QR_NATIVE_ROLE_MAP=JSON.stringify({profile:'ten-rank',roles:roles.slice(6).map(r=>r.id)});q=await qr.ingestAttestation(env,signer,{v:1,e:T()+600,g:'a'.repeat(32)},x.input);let beforeSql=sqlCalls;op=await role.queueProofRoles(env,q.proofId);const queueSql=sqlCalls-beforeSql;check('ten-rank plus privileged queue has fixed five D1 statements',queueSql===5&&op.length===11);
 const grantIds=db.prepare('SELECT id FROM role_settlements WHERE proof_id=? AND desired=1 ORDER BY id').all(q.proofId).map(r=>r.id);for(const id of grantIds)db.prepare("UPDATE role_settlements SET state='unknown',attempts=1,expires_at=? WHERE id=?").run(T()-1,id);db.prepare('UPDATE verification_proofs SET expires_at=?').run(T()-1);eraseJob();env.QR_PHASE1_ENABLED=undefined;env.PRIVACY_ERASURE_ENABLED='true';beforeSql=sqlCalls;writes=fetches.filter(x=>x.startsWith('PUT')||x.startsWith('DELETE')).length;const debt=await role.reconcileAccountErasureRoleDebt(env,ep),debtSql=sqlCalls-beforeSql;check('current erasure job drains at most two expired debts with GET only',debt.outcomes.length===2&&debt.attempts===8&&debtSql<=16&&fetches.filter(x=>x.startsWith('PUT')||x.startsWith('DELETE')).length===writes&&db.prepare("SELECT COUNT(*) AS n FROM role_settlements WHERE attempts=1 AND state='unknown'").get().n===0);console.log(JSON.stringify({observedD1:{tenRankQueue:queueSql,twoExpiredDebts:debtSql},observedDiscord:{twoExpiredDebts:debt.attempts},coldQrDDL:ddl.length,newCronJobs:0}));
 // Independent frozen-source counterexamples: signer identity is globally unique in a snapshot, and rank authority
 // is the latest committed observation, not two independently current conflicting proof queues.
 x=await setup();db.prepare('INSERT INTO roster_snapshots SELECT 2,exported_at,received_at,source,member_count+1,content_hash,trusted,complete,first_received_at FROM roster_snapshots WHERE id=1').run();db.prepare('INSERT INTO roster_members SELECT 2,name_key,name,rank,rank_index,level,class,public_note,officer_note,guid,last_online FROM roster_members WHERE snapshot_id=1').run();db.prepare("INSERT INTO roster_members(snapshot_id,name_key,name,rank,rank_index,guid)VALUES(2,'duplicate signer','Duplicate Signer','Officer',2,?)").run(sg);
 await rejects('newer complete roster with HC plus another row for signer GUID invalidates lease',()=>qr.ingestAttestation(env,signer,{v:1,e:T()+600,g:'a'.repeat(32)},x.input));check('duplicate-signer rejection leaves genuine code unused',db.prepare('SELECT used_at FROM verification_requests').get().used_at===null);
 async function rankProof(x,name,index){const c=await qr.issueChallenge(env,signer,x.k.id,1,T()+600),v=await qr.createWebsiteRequest(env,requester,{v:1,e:T()+600,g:'b'.repeat(32)}),wire=x.wire.replace(x.c.nonce,c.nonce).replace(x.v.code,v.code).replace('|7|1|Member',`|${index}|1|${name}`);const input={keyId:x.k.id,wire,signature:qr.base64url(new Uint8Array(await crypto.subtle.sign('Ed25519',x.pair.privateKey,qr.attestationBytes(x.k.id,requester,signer,wire))))};return qr.ingestAttestation(env,signer,{v:1,e:T()+600,g:'a'.repeat(32)},input);}
 for(const changed of ['duplicate requester GUID','changed requester name','cross-account requester GUID']){
  x=await setup();env.QR_PRIVILEGED_RANK_MAPPING_ENABLED='true';const proof=await rankProof(x,'Officer',2);await role.queueProofRoles(env,proof.proofId);
  const staffIntent=db.prepare("SELECT id FROM role_settlements WHERE proof_id=? AND purpose='verified_privileged_rank'").get(proof.proofId).id;
  db.prepare('INSERT INTO roster_snapshots SELECT 2,exported_at,received_at,source,member_count,content_hash,trusted,complete,first_received_at FROM roster_snapshots WHERE id=1').run();
  db.prepare('INSERT INTO roster_members SELECT 2,name_key,name,rank,rank_index,level,class,public_note,officer_note,guid,last_online FROM roster_members WHERE snapshot_id=1').run();
  db.prepare("UPDATE roster_members SET rank='Officer',rank_index=2 WHERE snapshot_id=2 AND guid=?").run(rg);
  if(changed==='duplicate requester GUID'){db.prepare('UPDATE roster_snapshots SET member_count=3 WHERE id=2').run();db.prepare("INSERT INTO roster_members(snapshot_id,name_key,name,rank,rank_index,guid)VALUES(2,'other requester','Other Requester','Raid Leader',4,?)").run(rg);}
  if(changed==='changed requester name')db.prepare("UPDATE roster_members SET name='Renamed Requester' WHERE snapshot_id=2 AND guid=?").run(rg);
  if(changed==='cross-account requester GUID'){db.prepare('INSERT INTO members(discord_id)VALUES(?)').run('400000000000000090');db.prepare("INSERT INTO characters(name_key,name,discord_id,status,bound_at,guid)VALUES('conflicting owner','Conflicting Owner',?,'member',?,?)").run('400000000000000090',T(),rg);}
  check(changed+' invalidates a queued genuine staff proof before PUT',(await role.settleRoleIntent(env,staffIntent)).state==='held'&&!fetches.some(f=>f.startsWith('PUT')));
 }
 x=await setup();env.QR_PRIVILEGED_RANK_MAPPING_ENABLED='true';let first=await rankProof(x,'Officer',2);await role.queueProofRoles(env,first.proofId);let second=await rankProof(x,'Raid Leader',4);await role.queueProofRoles(env,second.proofId);let firstStaff=db.prepare("SELECT id FROM role_settlements WHERE proof_id=? AND purpose='verified_privileged_rank'").get(first.proofId).id,secondStaff=db.prepare("SELECT id FROM role_settlements WHERE proof_id=? AND purpose='verified_privileged_rank'").get(second.proofId).id;
 check('older conflicting genuine proof cannot dispatch a privileged grant',(await role.settleRoleIntent(env,firstStaff)).state==='held'&&!fetches.some(f=>f.startsWith('PUT')));check('latest committed genuine proof settles only its selected staff role',(await role.settleRoleIntent(env,secondStaff)).state==='settled'&&members[requester].includes(raidLeader)&&!members[requester].includes(officer));
 x=await setup();env.QR_PRIVILEGED_RANK_MAPPING_ENABLED='true';first=await rankProof(x,'Officer',2);await role.queueProofRoles(env,first.proofId);firstStaff=db.prepare("SELECT id FROM role_settlements WHERE proof_id=? AND purpose='verified_privileged_rank'").get(first.proofId).id;let overlappingHeld=false;
 afterWrite=async()=>{second=await rankProof(x,'Raid Leader',4);try{await role.queueProofRoles(env,second.proofId);}catch{overlappingHeld=true;}};
 check('new rank observation during older PUT holds queue and compensates retained old access',(await role.settleRoleIntent(env,firstStaff)).state==='held'&&overlappingHeld&&!members[requester].includes(officer)&&!members[requester].includes(raidLeader));await role.queueProofRoles(env,second.proofId);secondStaff=db.prepare("SELECT id FROM role_settlements WHERE proof_id=? AND purpose='verified_privileged_rank'").get(second.proofId).id;check('new selected proof can continue after old dispatch and compensation settle',(await role.settleRoleIntent(env,secondStaff)).state==='settled'&&members[requester].includes(raidLeader)&&!members[requester].includes(officer));
 x=await setup();env.QR_PRIVILEGED_RANK_MAPPING_ENABLED='true';first=await rankProof(x,'Officer',2);await role.queueProofRoles(env,first.proofId);firstStaff=db.prepare("SELECT id FROM role_settlements WHERE proof_id=? AND purpose='verified_privileged_rank'").get(first.proofId).id;const originalFetch=globalThis.fetch;globalThis.fetch=async(url,init)=>{const response=await originalFetch(url,init);if(init?.method==='PUT')throw Error('response lost after landed staff PUT');return response;};s=await role.settleRoleIntent(env,firstStaff);globalThis.fetch=originalFetch;second=await rankProof(x,'Raid Leader',4);await rejects('unknown prior privileged dispatch blocks later proof intent admission',()=>role.queueProofRoles(env,second.proofId));writes=fetches.filter(f=>f.startsWith('PUT')||f.startsWith('DELETE')).length;check('unknown present prior staff effect remains held by GET without another write',(await role.settleRoleIntent(env,firstStaff,true)).state==='unknown'&&members[requester].includes(officer)&&fetches.filter(f=>f.startsWith('PUT')||f.startsWith('DELETE')).length===writes);members[requester]=[];check('fresh absence closes old unknown custody without replay',(await role.settleRoleIntent(env,firstStaff,true)).reason==='past_effect_absent'&&fetches.filter(f=>f.startsWith('PUT')||f.startsWith('DELETE')).length===writes);await role.queueProofRoles(env,second.proofId);secondStaff=db.prepare("SELECT id FROM role_settlements WHERE proof_id=? AND purpose='verified_privileged_rank'").get(second.proofId).id;check('only latest staff grant can follow resolved absence',(await role.settleRoleIntent(env,secondStaff)).state==='settled'&&members[requester].includes(raidLeader)&&!members[requester].includes(officer));
 x=await setup();env.QR_PRIVILEGED_RANK_MAPPING_ENABLED='true';first=await rankProof(x,'Officer',2);await role.queueProofRoles(env,first.proofId);firstStaff=db.prepare("SELECT id FROM role_settlements WHERE proof_id=? AND purpose='verified_privileged_rank'").get(first.proofId).id;await role.settleRoleIntent(env,firstStaff);second=await rankProof(x,'Raid Leader',4);await role.queueProofRoles(env,second.proofId);secondStaff=db.prepare("SELECT id FROM role_settlements WHERE proof_id=? AND purpose='verified_privileged_rank' AND desired=1").get(second.proofId).id;check('latest proof cannot grant ahead of earlier settled bot staff removal',(await role.settleRoleIntent(env,secondStaff)).state==='held'&&!members[requester].includes(raidLeader));const oldRemoval=db.prepare("SELECT id FROM role_settlements WHERE proof_id=? AND purpose='verified_privileged_rank' AND desired=0").get(second.proofId).id;await role.settleRoleIntent(env,oldRemoval);check('cross-proof managed removal precedes the new exclusive staff role',(await role.settleRoleIntent(env,secondStaff)).state==='settled'&&members[requester].includes(raidLeader)&&!members[requester].includes(officer));
 console.log(JSON.stringify({externalPrivacyABI:Object.values(cache).map(m=>m.sourcePin).filter(p=>peer&&p.path.startsWith(peer))}));
 console.log(`${n}/${n} QR/role checks passed`);
})().catch(e=>{console.error(e);process.exitCode=1;});
