// Actual source and SQLite; only Discord is simulated. The database clock is controlled to exercise a 30-minute gap.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),ts=require('typescript');
const {DatabaseSync}=require('node:sqlite');globalThis.crypto=require('node:crypto').webcrypto;
const root=path.join(__dirname,'..'),peer=process.env.OLYMPUS_PRIVACY_SOURCE,cache={};
function load(name){name=name.replace(/^\.\//,'');if(cache[name])return cache[name].exports;let file=path.join(root,'src',name+'.ts');if(peer&&(name==='site-core'||!fs.existsSync(file)))file=path.join(peer,name+'.ts');const m={exports:{}};cache[name]=m;const source=fs.readFileSync(file);m.sourcePin={path:file,bytes:source.length,sha256:require('node:crypto').createHash('sha256').update(source).digest('hex')};new Function('module','exports','require',ts.transpileModule(source.toString('utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(m,m.exports,p=>load(p));return m.exports;}
const service=load('role-rank-continuation'),rolesWriter=load('role-settlements'),ddl=load('qr-phase1-schema').QR_PHASE1_DDL,privacy=load('privacy-serving-schema').PRIVACY_SERVING_SCHEMA;
const subject='400000000000000002',bot='400000000000000003',guild='400000000000000004',memberRole='400000000000000005',botRole='400000000000000006',generation='b'.repeat(32),guid='Player-1234-00000002';
const leader='600000000000000001',officer='600000000000000002',raidLeader='600000000000000003',blocker='600000000000000004';
const labels=Array.from({length:10},(_,i)=>String(500000000000000000n+BigInt(i))),names=['Guild Master','High Council','Officer','Officer Alt','Raid Leader','Veteran','Raider','Member','Alt','Initiate'];
const inventory=[{id:guild,position:0,permissions:'0',managed:false},{id:memberRole,position:1,permissions:'0',managed:false},{id:botRole,position:30,permissions:'268435456',managed:false},{id:leader,position:18,permissions:'1024',managed:false},{id:officer,position:16,permissions:'1024',managed:false},{id:raidLeader,position:15,permissions:'1024',managed:false},{id:blocker,position:0,permissions:'0',managed:false},...labels.map((id,i)=>({id,position:2+i,permissions:'0',managed:false}))];
let db,env,members,requests,clock,sqlCalls,lookupHook,effectHook,lostWrite=false,maxSql=0,maxHttp=0;
const realNow=Date.now;Date.now=()=>clock*1000;
function d1(){function prepare(sql){let args=[];const q={bind(...values){args=values;return q;},async first(){sqlCalls++;return db.prepare(sql).get(...args)||null;},async all(){sqlCalls++;return {results:db.prepare(sql).all(...args)};},async run(){return q.exec();},exec(){sqlCalls++;const stmt=db.prepare(sql);if(/^\s*(SELECT|WITH)/.test(sql)||/RETURNING/.test(sql))return {results:stmt.all(...args),meta:{changes:0}};const r=stmt.run(...args);return {results:[],meta:{changes:Number(r.changes)}};}};return q;}return {prepare,batch:async rows=>{db.exec('BEGIN');try{const out=rows.map(x=>x.exec());db.exec('COMMIT');return out;}catch(e){db.exec('ROLLBACK');throw e;}}};}
function budget(limit=40){return {limit,attempts:0,calls:0,retries:0,exhausted:false,audited:false,inventoryFailed:false};}
function snapshot(id,rank=7){db.prepare("INSERT INTO roster_snapshots(id,exported_at,received_at,source,member_count,content_hash,complete,trusted) VALUES(?,?,?,'test',10,'test',1,1)").run(id,clock,clock);for(let i=0;i<10;i++)db.prepare('INSERT INTO roster_members(snapshot_id,name_key,name,rank,rank_index,guid) VALUES(?,?,?,?,?,?)').run(id,'character'+i,'Character '+i,names[i],i,i===rank?guid:'Player-1234-'+String(i+20).padStart(8,'0'));}
function reset(rank=7){clock=Math.floor(realNow()/1000);db=new DatabaseSync(':memory:');db.function('strftime',(format,value)=>{if(format!=='%s'||value!=='now')throw Error('unsupported synthetic clock');return String(clock);});db.exec(fs.readFileSync(path.join(root,'schema.sql'),'utf8'));for(const sql of [...privacy,...ddl])db.exec(sql);env={DB:d1(),GUILD_ID:guild,SITE_GUILD_ID:guild,ROLE_GUILD_MEMBER:memberRole,ROLE_GUILD_LEADER:leader,ROLE_OFFICER:officer,ROLE_RAID_LEADER:raidLeader,DISCORD_APP_ID:bot,DISCORD_BOT_TOKEN:'fixture-only',QR_RANK_MAPPING_ENABLED:'true',QR_PRIVILEGED_RANK_MAPPING_ENABLED:'true',QR_NATIVE_ROLE_MAP:JSON.stringify({profile:'ten-rank',roles:labels})};db.prepare('INSERT INTO members(discord_id)VALUES(?)').run(subject);db.prepare("INSERT INTO privacy_subjects(subject_id,generation,state,revision,created_at,updated_at) VALUES(?,?,'active',1,?,?)").run(subject,generation,clock,clock);db.prepare("INSERT INTO characters(name_key,name,discord_id,status,bound_at,guid) VALUES('actual member','Actual Member',?,'member',?,?)").run(subject,clock,guid);snapshot(1,rank);members={[subject]:[],[bot]:[botRole]};requests=[];lookupHook=null;effectHook=null;lostWrite=false;sqlCalls=0;}
function priorStaff(role){db.prepare("INSERT INTO role_settlements(id,subject,purpose,guild_id,role_id,desired,state,reason,attempts,created_at,expires_at) VALUES(?,?,'roster_privileged_rank',?,?,1,'settled','effect_and_current_server_confirmed',1,?,?)").run(crypto.randomUUID().replaceAll('-',''),subject,guild,role,clock-10,clock+290);}
globalThis.fetch=async(input,init={})=>{const pathname=new URL(String(input)).pathname,method=init.method||'GET';requests.push(method+' '+pathname);let value;if(pathname.endsWith('/users/@me'))value={id:bot};else if(pathname.endsWith('/roles')&&method==='GET')value=inventory;else{const m=pathname.match(/\/members\/(\d+)(?:\/roles\/(\d+))?$/);if(!m)throw Error('unexpected provider path');if(m[2]){members[m[1]]=method==='PUT'?[...new Set([...members[m[1]],m[2]])]:members[m[1]].filter(x=>x!==m[2]);if(effectHook)await effectHook(method,m[2]);if(lostWrite)throw Error('synthetic lost provider response');return new Response(null,{status:204});}if(lookupHook){const f=lookupHook;lookupHook=null;await f(m[1]);}if(!members[m[1]])return new Response('{}',{status:404});value={user:{id:m[1]},roles:members[m[1]]};}return new Response(JSON.stringify(value),{headers:{'Content-Type':'application/json'}});};
let n=0;function check(title,condition){assert.ok(condition,title);console.log('PASS '+title);n++;}
async function run(snapshotId=1,parent=budget(),capture={subjectGeneration:generation}){const start=sqlCalls,http=requests.length,result=await service.continueRosterRanks(env,subject,snapshotId,capture,parent),delta=sqlCalls-start,calls=requests.length-http;maxSql=Math.max(maxSql,delta);maxHttp=Math.max(maxHttp,calls);check('finite source SQL and actual request accounting '+n,delta<=35&&calls<=20&&result.attempts===calls&&parent.attempts<=parent.limit&&parent.calls===parent.attempts&&parent.retries===0);return {result,parent,sql:delta,http:calls};}
(async()=>{
 reset(4);members[subject]=[labels[5],officer];priorStaff(officer);let first=await run();check('first automatic invocation removes old cosmetic and bot-granted staff before grants',first.result.state==='pending'&&first.result.visited===2&&members[subject].length===0&&requests.filter(r=>r.startsWith('DELETE')).length===2&&!requests.some(r=>r.startsWith('PUT')));const oldIds=db.prepare("SELECT id FROM role_settlements WHERE roster_id=1 AND state='pending'").all().map(r=>r.id);
 clock+=1800;let stale=await run();check('same expired snapshot is held without renewal or a late effect',stale.result.state==='held'&&!requests.slice(first.http).some(r=>r.startsWith('PUT')||r.startsWith('DELETE'))&&db.prepare("SELECT COUNT(*) AS n FROM role_settlements WHERE roster_id=1 AND expires_at>?").get(clock).n===0);
 snapshot(2,4);let second=await run(2);check('fresh next snapshot finishes wanted cosmetic and staff in one bounded invocation',second.result.state==='done'&&members[subject].includes(labels[4])&&members[subject].includes(raidLeader)&&!members[subject].includes(officer)&&second.http===16);check('fresh authority creates new unspent IDs rather than renewing expired original writes',oldIds.every(id=>db.prepare('SELECT attempts,expires_at FROM role_settlements WHERE id=?').get(id).attempts===0)&&db.prepare("SELECT COUNT(*) AS n FROM role_settlements WHERE roster_id=2 AND desired=1 AND attempts=1 AND state='settled'").get().n===2);
 reset();let wrong=await run(1,budget(),{subjectGeneration:'c'.repeat(32)});check('wrong original generation never makes a provider request or mints intents',wrong.result.state==='held'&&requests.length===0&&db.prepare('SELECT COUNT(*) AS n FROM role_settlements').get().n===0);
 reset();db.prepare('DELETE FROM privacy_subjects WHERE subject_id=?').run(subject);let accountless=await run(1,budget(),{subjectGeneration:null});check('captured genuine accountless absence can settle source-native labels without a website account',accountless.result.state==='done'&&members[subject].includes(labels[7])&&!db.prepare('SELECT 1 FROM site_users WHERE discord_id=?').get(subject)&&!db.prepare('SELECT 1 FROM privacy_subjects WHERE subject_id=?').get(subject));
 reset();let missing=await run(1,budget(),{});check('missing original generation cannot become a recaptured live identity',missing.result.reason==='original_generation_required'&&sqlCalls===0&&requests.length===0);
 reset();await rolesWriter.queueRosterRankRoles(env,subject,1,generation);snapshot(2,7);let newer=await run(1);check('a newer whole snapshot fences all old pending effects',newer.result.state==='held'&&requests.length===0);
 reset();const ids=await rolesWriter.queueRosterRankRoles(env,subject,1,generation),wanted=db.prepare("SELECT id FROM role_settlements WHERE desired=1").get().id;await rolesWriter.settleRosterRankAbsences(env,subject,1,generation,budget());lostWrite=true;await rolesWriter.settleRoleIntent(env,wanted);lostWrite=false;const effects=requests.filter(r=>r.startsWith('PUT')||r.startsWith('DELETE')).length;let unknown=await run();check('unknown landed grant is reconciled by GET and never repeated',unknown.result.state==='held'&&unknown.result.reason==='current_source_held'&&unknown.result.pending===0&&unknown.result.unknown===0&&unknown.result.held===0&&requests.filter(r=>r.startsWith('PUT')||r.startsWith('DELETE')).length===effects&&db.prepare('SELECT state FROM role_settlements WHERE id=?').get(wanted).state==='settled');
 reset(4);members[subject]=[officer];const manually=await run();check('manual staff role is preserved while source-selected roles settle',manually.result.state==='done'&&members[subject].includes(officer)&&members[subject].includes(raidLeader)&&!requests.some(r=>r.startsWith('DELETE')&&r.endsWith('/'+officer)));
 reset();let exhausted=await run(1,budget(19));check('whole-account20-call reserve refuses before SQL or any HTTP',exhausted.result.state==='budget'&&sqlCalls===0&&requests.length===0&&exhausted.parent.exhausted);
 reset();env.QR_RANK_MAPPING_ENABLED=undefined;env.QR_PRIVILEGED_RANK_MAPPING_ENABLED=undefined;let off=await run();check('default OFF has no authority read or effect',off.result.reason==='rank_mapping_disabled'&&sqlCalls===0&&requests.length===0);
 reset(4);const shared=budget();lookupHook=()=>{shared.attempts=shared.limit;shared.calls=shared.limit;};let parallel=await run(1,shared);check('child observes concurrent parent use without overdraw',parallel.result.state==='budget'&&shared.attempts===40&&requests.length===3);
 reset(4);env.BLOCKING_ROLE_IDS=blocker;effectHook=(method)=>{if(method==='PUT')members[subject].push(blocker);else members[subject]=members[subject].filter(r=>r!==blocker);};let compensated=await run();check('two compensated grants stay within reserved20 calls and retain neither rank',compensated.http===20&&compensated.result.state==='held'&&members[subject].length===0&&db.prepare("SELECT COUNT(*) AS n FROM role_settlements WHERE purpose='grant_compensation' AND state='settled'").get().n===2);
 reset();lookupHook=()=>db.prepare('UPDATE privacy_subjects SET generation=? WHERE subject_id=?').run('c'.repeat(32),subject);let rotated=await run();check('generation change during absence qualification cannot certify absence or dispatch a grant',rotated.result.state==='held'&&!requests.some(r=>r.startsWith('PUT')||r.startsWith('DELETE'))&&db.prepare("SELECT COUNT(*) AS n FROM role_settlements WHERE state='settled'").get().n===0);
 reset();lookupHook=()=>snapshot(2,7);let changedRoster=await run();check('newer roster committed during inventory look cannot certify old absence or dispatch',changedRoster.result.state==='held'&&!requests.some(r=>r.startsWith('PUT')||r.startsWith('DELETE'))&&db.prepare("SELECT COUNT(*) AS n FROM role_settlements WHERE state='settled'").get().n===0);
 reset();env.DB.prepare=()=>({bind(){return this;},async first(){sqlCalls++;throw Error('synthetic unavailable D1');},async all(){sqlCalls++;throw Error('synthetic unavailable D1');}});let unreadable=await run();check('unreadable durable state rotates held with unknown counts rather than claiming done',unreadable.result.state==='held'&&unreadable.result.reason==='source_or_receipt_unavailable'&&unreadable.result.pending===null&&unreadable.result.unknown===null&&unreadable.result.rotate&&requests.length===0);
 reset();members[subject]=[labels[5]];inventory.find(r=>r.id===labels[5]).position=31;let held=await run();inventory.find(r=>r.id===labels[5]).position=7;check('held target returns rotation without granting ahead of a removal',held.result.state==='held'&&held.result.rotate&&members[subject].includes(labels[5])&&!members[subject].includes(labels[7]));
 console.log(JSON.stringify({observedMax:{sql:maxSql,http:maxHttp},sourceReserve:{sql:35,http:20},effectLimit:2,newCronJobs:0,externalPrivacyABI:Object.values(cache).map(m=>m.sourcePin).filter(p=>peer&&p.path.startsWith(peer))}));console.log(`${n}/${n} role-rank continuation checks passed`);
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>{Date.now=realNow;});
