// Actual restore -> rank continuation -> central role writer and native SQLite. Only Discord and time are synthetic.
// This owned fixture is addition-only; no production source, provider, or real account effects.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),ts=require('typescript'),cryptoNode=require('node:crypto');
const {DatabaseSync}=require('node:sqlite');globalThis.crypto=cryptoNode.webcrypto;
const root=process.env.OLYMPUS_RANK_SWEEP_SOURCE||path.join(__dirname,'..'),cache={},sourcePins=new Map();
function read(file){const b=fs.readFileSync(file);sourcePins.set(file,{bytes:b.length,sha256:cryptoNode.createHash('sha256').update(b).digest('hex')});return b;}
function load(name){name=name.replace(/^\.\//,'');if(cache[name])return cache[name].exports;const file=path.join(root,'src',name+'.ts'),m={exports:{}};cache[name]=m;new Function('module','exports','require',ts.transpileModule(read(file).toString('utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(m,m.exports,p=>load(p));return m.exports;}
const restore=load('restore'),service=load('role-rank-continuation'),roles=load('roles'),writer=load('role-settlements'),budgetSource=load('scheduled-budget');
const schema=read(path.join(root,'schema.sql')).toString('utf8'),qrDdl=load('qr-phase1-schema').QR_PHASE1_DDL;
const subject='400000000000000002',second='400000000000000007',bot='400000000000000003',guild='400000000000000004',memberRole='400000000000000005',botRole='400000000000000006',generation='b'.repeat(32),guid='Player-1234-00000002';
const leader='600000000000000001',officer='600000000000000002',raidLeader='600000000000000003',blocker='600000000000000004';
const labels=Array.from({length:10},(_,i)=>String(500000000000000000n+BigInt(i))),names=['Guild Master','High Council','Officer','Officer Alt','Raid Leader','Veteran','Raider','Member','Alt','Initiate'];
const makeInventory=()=>[{id:guild,position:0,permissions:'0',managed:false},{id:memberRole,position:1,permissions:'0',managed:false},{id:botRole,position:30,permissions:'268435456',managed:false},{id:leader,position:18,permissions:'1024',managed:false},{id:officer,position:16,permissions:'1024',managed:false},{id:raidLeader,position:15,permissions:'1024',managed:false},{id:blocker,position:0,permissions:'0',managed:false},...labels.map((id,i)=>({id,position:2+i,permissions:'0',managed:false}))];
let db,env,members,requests,clock,sqlCalls,inventory,firstMemberHook,effectHook,sqlHook,rankStarts,realNow=Date.now,checks=0,passes=0,maxD1=0,maxHTTP=0,observations=[];
Date.now=()=>clock*1000;
function d1(){function prepare(sql){let args=[];const q={bind(...values){args=values;return q;},async first(){sqlCalls++;if(sqlHook)await sqlHook(sql,args);return db.prepare(sql).get(...args)||null;},async all(){sqlCalls++;if(sql.startsWith('SELECT DISTINCT rank,rank_index FROM roster_members'))rankStarts.push(requests.length);if(sqlHook)await sqlHook(sql,args);return {results:db.prepare(sql).all(...args)};},async run(){return q.exec();},exec(){sqlCalls++;const stmt=db.prepare(sql);if(/^\s*(SELECT|WITH)/.test(sql)||/RETURNING/.test(sql))return {results:stmt.all(...args),meta:{changes:0}};const r=stmt.run(...args);return {results:[],meta:{changes:Number(r.changes)}};}};return q;}return{prepare,batch:async rows=>{db.exec('BEGIN');try{const out=rows.map(x=>x.exec());db.exec('COMMIT');return out;}catch(e){db.exec('ROLLBACK');throw e;}}};}
function snapshot(id,rank=7,secondRank=null){db.prepare("INSERT INTO roster_snapshots(id,exported_at,received_at,source,member_count,content_hash,complete,trusted)VALUES(?,?,?,'fixture',10,'fixture',1,1)").run(id,clock,clock);for(let i=0;i<10;i++)db.prepare('INSERT INTO roster_members(snapshot_id,name_key,name,rank,rank_index,guid)VALUES(?,?,?,?,?,?)').run(id,'character'+i,'Character '+i,names[i],i,i===rank?guid:i===secondRank?'Player-1234-00000007':'Player-1234-'+String(i+20).padStart(8,'0'));}
function reset(rank=7){if(db)db.close();clock=Math.floor(realNow()/1000);db=new DatabaseSync(':memory:');db.function('strftime',(format,value)=>{if(format!=='%s'||value!=='now')throw Error('unexpected synthetic clock');return String(clock);});db.exec('PRAGMA foreign_keys=ON');db.exec(schema);for(const sql of qrDdl)db.exec(sql);env={DB:d1(),GUILD_ID:guild,SITE_GUILD_ID:guild,ROLE_GUILD_MEMBER:memberRole,ROLE_GUILD_LEADER:leader,ROLE_OFFICER:officer,ROLE_RAID_LEADER:raidLeader,DISCORD_APP_ID:bot,DISCORD_BOT_TOKEN:'fixture-only',QR_PHASE1_ENABLED:'true',PRIVACY_ERASURE_ENABLED:'true',QR_RANK_MAPPING_ENABLED:'true',QR_PRIVILEGED_RANK_MAPPING_ENABLED:'true',QR_NATIVE_ROLE_MAP:JSON.stringify({profile:'ten-rank',roles:labels})};db.prepare('INSERT INTO members(discord_id)VALUES(?)').run(subject);db.prepare("INSERT INTO privacy_subjects(subject_id,generation,state,revision,created_at,updated_at)VALUES(?,?,'active',1,?,?)").run(subject,generation,clock,clock);db.prepare("INSERT INTO characters(name_key,name,discord_id,status,bound_at,guid)VALUES('actual member','Actual Member',?,'member',?,?)").run(subject,clock,guid);snapshot(1,rank);members={[subject]:[memberRole],[bot]:[botRole]};requests=[];sqlCalls=0;inventory=makeInventory();firstMemberHook=null;effectHook=null;sqlHook=null;rankStarts=[];restore.forgetLocalThrottle();roles.forgetRolesCheck();}
const effectRequests=()=>requests.filter(r=>/^(PUT|DELETE) /.test(r));
globalThis.fetch=async(input,init={})=>{const url=new URL(String(input));if(url.hostname!=='discord.com'||!url.pathname.startsWith('/api/v10/'))throw Error('unexpected network target');const pathname=url.pathname,method=init.method||'GET';requests.push(method+' '+pathname);let value;if(pathname.endsWith('/users/@me'))value={id:bot};else if(pathname.endsWith('/roles')&&method==='GET')value=inventory;else{const m=pathname.match(/\/members\/(\d+)(?:\/roles\/(\d+))?$/);if(!m)throw Error('unexpected provider path');if(m[2]){members[m[1]]=method==='PUT'?[...new Set([...members[m[1]],m[2]])]:members[m[1]].filter(x=>x!==m[2]);if(effectHook)await effectHook(method,m[2]);return new Response(null,{status:204});}if(m[1]===subject&&firstMemberHook){const f=firstMemberHook;firstMemberHook=null;await f();}if(!members[m[1]])return new Response('{}',{status:404});value={user:{id:m[1]},roles:members[m[1]]};}return new Response(JSON.stringify(value),{headers:{'Content-Type':'application/json'}});};
function check(title,condition,detail){checks++;if(condition)passes++;console.log((condition?'PASS ':'FAIL ')+title+(condition||detail===undefined?'':' '+JSON.stringify(detail)));}
function lastSweep(){const r=db.prepare("SELECT details FROM audit WHERE action='role.sweep' ORDER BY id DESC LIMIT1".replace('LIMIT1','LIMIT 1')).get();return r?JSON.parse(r.details):null;}
async function run(title){const before=sqlCalls,http=requests.length,rankBefore=rankStarts.length,r=await restore.sweepMemberRoles(env,'cron'),d1=sqlCalls-before,actual=requests.length-http;maxD1=Math.max(maxD1,d1);maxHTTP=Math.max(maxHTTP,actual);const child=rankStarts.length>rankBefore?requests.length-rankStarts[rankBefore]:0;observations.push({title,result:r,d1,http:actual,rankChildHTTP:child});check(title+' actual rank child20-request debit',child<=20,{child});check(title+' actual shared accounting',!!r&&r.attempts===actual&&r.calls+r.retries===r.attempts&&r.attempts<=Math.min(50,Number(env.ROLE_CALL_BUDGET||40)),{r,actual,d1});return r;}
(async()=>{
 reset(4);let r=await run('default40 existing Guild Member');check('automatic rank continues for existing Guild Member under default40 reserve',r?.checked===1&&members[subject].includes(labels[4])&&members[subject].includes(raidLeader)&&!r?.budgetExhausted,{r,requests});check('rank effects never regrant Guild Member already held',!effectRequests().some(x=>x.endsWith('/'+memberRole))&&db.prepare("SELECT COUNT(*) AS n FROM role_settlements WHERE purpose='roster_membership'").get().n===0);check('two actual rank effects are limited and debit parent result',effectRequests().length===2&&r?.attempts===21&&db.prepare("SELECT COUNT(*) AS n FROM role_settlements WHERE purpose IN('roster_native_rank','roster_privileged_rank')AND desired=1 AND state='settled'").get().n===2,{r,effects:effectRequests()});
 reset(4);firstMemberHook=()=>db.prepare('UPDATE privacy_subjects SET generation=? WHERE subject_id=?').run('c'.repeat(32),subject);r=await run('changed original generation');check('generation captured before first Discord await cannot be substituted',r?.checked===1&&requests.length<=5&&effectRequests().length===0&&db.prepare('SELECT COUNT(*) AS n FROM role_settlements').get().n===0,{r,requests});
 reset(4);db.prepare('DELETE FROM privacy_subjects WHERE subject_id=?').run(subject);firstMemberHook=()=>db.prepare("INSERT INTO privacy_subjects(subject_id,generation,state,revision,created_at,updated_at)VALUES(?,?,'active',1,?,?)").run(subject,'c'.repeat(32),clock,clock);r=await run('captured accountless absence');check('original null generation does not adopt newly created authority',r?.checked===1&&requests.length<=5&&effectRequests().length===0&&db.prepare('SELECT COUNT(*) AS n FROM role_settlements').get().n===0,{r,requests});
 reset(4);firstMemberHook=()=>snapshot(2,4);r=await run('changed original snapshot');check('selected original snapshot is held instead of refreshing to latest after Discord await',r?.checked===1&&requests.length<=5&&effectRequests().length===0&&!db.prepare('SELECT 1 FROM role_settlements WHERE attempts=1').get()&&!db.prepare('SELECT 1 FROM role_settlements WHERE roster_id=2').get(),{r,requests});
 reset(7);db.prepare('INSERT INTO members(discord_id)VALUES(?)').run(second);db.prepare("INSERT INTO privacy_subjects(subject_id,generation,state,revision,created_at,updated_at)VALUES(?,?,'active',1,?,?)").run(second,generation,clock,clock);db.prepare("INSERT INTO characters(name_key,name,discord_id,status,bound_at,guid)VALUES('second member','Second Member',?,'member',?,'Player-1234-00000007')").run(second,clock);db.prepare("UPDATE roster_members SET guid='Player-1234-00000007' WHERE snapshot_id=1 AND rank_index=8").run();members[second]=[memberRole];inventory.find(x=>x.id===labels[5]).position=31;members[subject].push(labels[5]);r=await run('rank held first rotation');const heldCursor=lastSweep()?.c;check('observed rank hierarchy hold rotates existing member worklist',r?.checked===1&&heldCursor===subject&&!members[subject].includes(labels[7])&&members[subject].includes(labels[5]),{r,heldCursor});inventory.find(x=>x.id===labels[5]).position=7;const started=requests.length;r=await run('next member after held rank');check('next admitted sweep progresses past rank-held account to second member',r?.checked===1&&members[second].includes(labels[8])&&requests.slice(started).some(x=>x.endsWith('/members/'+second))&&!requests.slice(started).some(x=>x.endsWith('/members/'+subject)),{r,requests:requests.slice(started)});
 reset(4);env.ROLE_CALL_BUDGET='29';r=await run('insufficient whole account');check('insufficient legacy retry plus20 actual central reserve refuses before HTTP',r?.budgetExhausted&&r.checked===0&&requests.length===0&&!db.prepare('SELECT1 FROM role_settlements'.replace('SELECT1','SELECT 1')).get(),r);
 reset(4);env.ROLE_CALL_BUDGET='30';r=await run('exact cold whole account reserve');check('exact10 legacy-retry plus20 actual-request reservation admits one account',r?.checked===1&&members[subject].includes(labels[4])&&members[subject].includes(raidLeader)&&r.attempts<=30,r);
 reset(4);env.BLOCKING_ROLE_IDS=blocker;effectHook=method=>{if(method==='PUT')members[subject].push(blocker);else members[subject]=members[subject].filter(x=>x!==blocker);};r=await run('two compensated rank effects');check('two compensation paths debit20 child HTTP plus5 membership/restriction lookups',r?.checked===1&&r.attempts===25&&observations.at(-1).rankChildHTTP===20&&effectRequests().length===4&&!members[subject].includes(labels[4])&&!members[subject].includes(raidLeader),{r,effects:effectRequests()});
 reset(4);firstMemberHook=()=>db.prepare("UPDATE privacy_subjects SET state='retiring',revision=revision+1 WHERE subject_id=?").run(subject);r=await run('retired selection during await');check('retiring captured subject never mints rank intents/effects',r?.checked===1&&requests.length<=5&&effectRequests().length===0&&!db.prepare('SELECT 1 FROM role_settlements').get());
 reset(4);let lost=true;effectHook=method=>{if(method==='PUT'&&lost){lost=false;throw Error('synthetic lost dispatched response');}};r=await run('unknown rank dispatch');const priorEffects=effectRequests().length;check('lost rank response retains spent unknown custody',r?.checked===1&&db.prepare("SELECT 1 FROM role_settlements WHERE attempts=1 AND state='unknown'").get()&&priorEffects===1);effectHook=null;r=await run('unknown rank rotation wrap');check('normal worklist wraps cursor before revisiting without blind retry',r?.checked===0&&requests.length===14&&effectRequests().length===priorEffects);r=await run('unknown rank subsequent sweep');check('later sweep reconciles lost rank outcome without dispatching same role twice',r?.checked===1&&!db.prepare("SELECT 1 FROM role_settlements WHERE attempts=1 AND state='unknown'").get()&&effectRequests().length<=priorEffects+1&&new Set(effectRequests()).size===effectRequests().length);
 reset(4);const parent=roles.callBudget(env);firstMemberHook=()=>{parent.attempts=parent.limit;parent.calls=parent.limit;};const direct=await service.continueRosterRanks(env,subject,1,{subjectGeneration:generation},parent);check('rank child sees shared-parent debit during await and cannot overdraw',direct.state==='budget'&&parent.attempts===40&&direct.attempts===requests.length&&requests.length===4&&effectRequests().length===0&&parent.exhausted,{direct,parent,requests}); check('production role sweep cap is one account, bounded rank child20HTTP/35SQL',budgetSource.SCHEDULED_CAPS.roleSweepAccounts===1&&service.RANK_CONTINUATION_HTTP_RESERVE===20&&service.RANK_CONTINUATION_SQL_RESERVE===35&&service.RANK_CONTINUATION_EFFECT_LIMIT===2);
 check('actual busiest integrated role sweep fits source scheduled descriptor',maxD1<=budgetSource.SCHEDULED_BUDGET.find(x=>x.job==='sweepMemberRoles').worst,{maxD1,declared:budgetSource.SCHEDULED_BUDGET.find(x=>x.job==='sweepMemberRoles').worst});
 check('all actual loaded source/schema bytes unchanged during fixture',Array.from(sourcePins).every(([file,pin])=>{const b=fs.readFileSync(file);return b.length===pin.bytes&&cryptoNode.createHash('sha256').update(b).digest('hex')===pin.sha256;}));
 console.log(JSON.stringify({observations,maxD1,maxHTTP,sourcePins:Array.from(sourcePins,([file,pin])=>({file,...pin})),realProviderActions:0,productionWrites:0}));console.log(`${passes}/${checks} real role sweep/rank integration checks passed`);if(passes!==checks)process.exitCode=1;
})().catch(e=>{console.error('actual rank sweep fixture stopped:',e.stack);process.exitCode=1;}).finally(()=>{Date.now=realNow;if(db)db.close();});