/**
 * Verification codes — the ONE spec shared by the Worker, the watcher (Python) and the addon (Lua).
 *
 *   message = asciiLower(strip(character)) + "|" + dayBucketUTC     e.g. "thrall|2026-09-17"
 *   digest  = HMAC-SHA256(VERIFY_SECRET, message)
 *   code    = first 30 bits of digest, 6 symbols, alphabet "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"
 *             (no I, O, 0, 1 — nothing to misread in a whisper)
 *
 * A code is accepted for the UTC day it was issued on and the following day (boundary tolerance).
 * The addon has no Discord ID and no network, so the code is bound to the character name only;
 * the Worker maps character -> pending Discord ID when the in-game event arrives.
 *
 * Request codes ("tickets", 27 Sep 2026): the same alphabet, 7 symbols, bound to the Discord request instead of a
 * character, so nobody has to type a character name and the whisper's sender (which the server vouches for) decides
 * which character is linked.
 *
 *   nonce   = 3 random symbols, chosen by the Worker (unique among open requests)
 *   mac     = first 4 symbols of digestToCode(HMAC-SHA256(VERIFY_SECRET, "ticket|" + nonce + "|" + dayBucketUTC))
 *   ticket  = nonce + mac                                                   e.g. "K7Q" + "M2XD"
 *
 * The addon and the watcher check the mac offline (a guess passes with odds of about 1 in 500,000); the Worker then
 * maps the nonce to the open request. Same two-day acceptance as a character code. A 6-symbol code is always a
 * character code and a 7-symbol code always a ticket, so the two never need telling apart any other way.
 * Test vectors: ../../watcher/tests/vectors.json (generated by the Python implementation).
 */

export const CODE_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
export const CODE_LENGTH = 6;
export const TICKET_LENGTH = 7;
export const TICKET_NONCE_LENGTH = 3;

/** ASCII-only lowercase, whitespace collapsed, realm suffix ("-Realm") removed. Identical in Python and Lua. */
export function normalizeCharacter(name: string): string {
  let s = name.trim().replace(/\s+/g, " ");
  const dash = s.indexOf("-");
  if (dash > 0) s = s.slice(0, dash);
  let out = "";
  for (const ch of s) {
    const c = ch.charCodeAt(0);
    out += c >= 65 && c <= 90 ? String.fromCharCode(c + 32) : ch;
  }
  return out;
}

export function dayBucket(date: Date): string {
  return date.toISOString().slice(0, 10);
}

async function hmacSha256(secret: string, message: string): Promise<Uint8Array> {
  if (!secret) throw new Error("VERIFY_SECRET is not set — run: npx wrangler secret put VERIFY_SECRET");
  const key = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"],
  );
  const sig = await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(message));
  return new Uint8Array(sig);
}

export function digestToCode(digest: Uint8Array): string {
  // 30 bits = 6 x 5-bit symbols, taken big-endian from the first 4 bytes.
  const bits = ((digest[0] << 24) >>> 0) + (digest[1] << 16) + (digest[2] << 8) + digest[3];
  let code = "";
  for (let i = 0; i < CODE_LENGTH; i++) {
    const shift = 32 - 5 * (i + 1); // 27, 22, 17, 12, 7, 2
    const idx = (bits >>> shift) & 31;
    code += CODE_ALPHABET[idx];
  }
  return code;
}

export async function codeFor(secret: string, character: string, day: string): Promise<string> {
  const digest = await hmacSha256(secret, `${normalizeCharacter(character)}|${day}`);
  return digestToCode(digest);
}

/** Codes valid right now for a character: today's and yesterday's (UTC). */
export async function validCodes(secret: string, character: string, now = new Date()): Promise<string[]> {
  const today = dayBucket(now);
  const yesterday = dayBucket(new Date(now.getTime() - 86_400_000));
  return [await codeFor(secret, character, today), await codeFor(secret, character, yesterday)];
}

export function normalizeCodeInput(input: string): string {
  return input.trim().toUpperCase().replace(/[^A-Z2-9]/g, "");
}

export async function isValidCode(secret: string, character: string, input: string, now = new Date()): Promise<boolean> {
  const c = normalizeCodeInput(input);
  if (c.length !== CODE_LENGTH) return false;
  return (await validCodes(secret, character, now)).includes(c);
}

// ---------- request codes (tickets) ----------

/** Three symbols of the code alphabet, from the platform's CSPRNG. */
export function randomNonce(): string {
  const bytes = new Uint8Array(TICKET_NONCE_LENGTH);
  crypto.getRandomValues(bytes);
  let out = "";
  for (const b of bytes) out += CODE_ALPHABET[b & 31]; // 256 is a multiple of 32, so this is unbiased
  return out;
}

export async function ticketFor(secret: string, nonce: string, day: string): Promise<string> {
  const n = normalizeCodeInput(nonce).slice(0, TICKET_NONCE_LENGTH);
  const mac = digestToCode(await hmacSha256(secret, `ticket|${n}|${day}`)).slice(0, TICKET_LENGTH - TICKET_NONCE_LENGTH);
  return n + mac;
}

/** The nonce of a well-formed ticket, or null. Says nothing about whether the mac is right. */
export function ticketNonce(input: string): string | null {
  const c = normalizeCodeInput(input);
  return c.length === TICKET_LENGTH ? c.slice(0, TICKET_NONCE_LENGTH) : null;
}

export async function isValidTicket(secret: string, input: string, now = new Date()): Promise<boolean> {
  const c = normalizeCodeInput(input);
  if (c.length !== TICKET_LENGTH) return false;
  const nonce = c.slice(0, TICKET_NONCE_LENGTH);
  const today = dayBucket(now);
  const yesterday = dayBucket(new Date(now.getTime() - 86_400_000));
  return c === (await ticketFor(secret, nonce, today)) || c === (await ticketFor(secret, nonce, yesterday));
}
