/** Browser-signed councillor attestation, NOT Blizzard-certified game origin. Phase1 only, disabled by default. */
import type { Env } from './env';
import { randomGeneration, sha256 } from './account-generation-contracts';
import { readPrivacySubject, privacyGenerationFenceSql, PRIVACY_DB_NOW as DB_NOW } from './privacy-serving-authority';
import { currentRulesetProfile } from './ruleset-profile';
import { guildMember, verifyInteraction } from './discord';
export type QrEnv=Env&{QR_PHASE1_ENABLED?:string;QR_RANK_MAPPING_ENABLED?:string;QR_NATIVE_ROLE_MAP?:string;QR_PRIVILEGED_RANK_MAPPING_ENABLED?:string};
export const QR_LIMITS={requestSeconds:600,challengeSeconds:300,keyLeaseSeconds:86400,proofSeconds:300,wireBytes:512,qrBytes:192,bodyBytes:2048} as const;
export const QR_PROFILE={revision:currentRulesetProfile().revision,guild:'OLYMPUS',realm:'Classic Beta PvP 2',build:70205,interface:16001} as const;
export const NATIVE_RANKS=['Guild Master','High Council','Officer','Officer Alt','Raid Leader','Veteran','Raider','Member','Alt','Initiate'] as const;
export const BETA_RANKS=['Guild Master','Officer','Veteran','Member','Initiate'] as const;
const ID=/^\d{17,20}$/,HEX=/^[0-9a-f]{32}$/,GUID=/^Player-\d{1,8}-[0-9A-Fa-f]{8}$/;
export class QrHeld extends Error{constructor(public code:string){super(code);}}
export const requireQr=(env:QrEnv)=>{if(env.QR_PHASE1_ENABLED!=='true')throw new QrHeld('phase1_disabled');};
export const base64url=(b:Uint8Array)=>btoa(String.fromCharCode(...b)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
export function bytesFromBase64(v:unknown,len:number){if(typeof v!=='string'||!/^[A-Za-z0-9_-]+$/.test(v)||v.length>256)throw new QrHeld('invalid_encoding');let b:Uint8Array;try{b=Uint8Array.from(atob(v.replace(/-/g,'+').replace(/_/g,'/')),x=>x.charCodeAt(0));}catch{throw new QrHeld('invalid_encoding');}if(b.length!==len||base64url(b)!==v)throw new QrHeld('invalid_encoding');return b;}
export type KeyRow={id:string;signer:string;signer_guid:string;subject_generation:string;public_key:string;roster_id:number;expires_at:number};
export type QrSession={v:number;e:number;g:string|null};
async function active(env:Env,id:string,session:QrSession){if(!ID.test(id))throw new QrHeld('invalid_subject');const s=await readPrivacySubject(env,id);if(!s||s.state!=='active'||s.subjectGeneration!==session.g)throw new QrHeld('current_serving_generation_required');return s;}
export async function rosterIdentity(env:Env,guid:string,signer=false){
 const r=await env.DB.prepare(`SELECT r.snapshot_id,r.name,r.rank,r.rank_index FROM roster_members r JOIN roster_snapshots s ON s.id=r.snapshot_id WHERE s.id=(SELECT MAX(id) FROM roster_snapshots)
 AND s.complete=1 AND s.trusted=1 AND s.member_count=(SELECT COUNT(*) FROM roster_members WHERE snapshot_id=s.id) AND s.exported_at<=${DB_NOW} AND s.exported_at>${DB_NOW}-600 AND s.exported_at>=?2 AND r.guid=?1
 AND (SELECT COUNT(*) FROM roster_members WHERE snapshot_id=s.id AND guid=?1)=1`).bind(guid,Number(env.LINKS_NOT_BEFORE||0)).first<{snapshot_id:number;name:string;rank:string;rank_index:number}>();
 if(!GUID.test(guid)||!r)throw new QrHeld('fresh_complete_roster_required');if(signer&&(r.rank!=='High Council'||r.rank_index!==1))throw new QrHeld('no_qualified_high_council');return r;
}
async function serverSigner(env:Env,id:string,guid:string){const linked=await env.DB.prepare(`SELECT 1 FROM characters c JOIN members m ON m.discord_id=c.discord_id WHERE c.discord_id=?1 AND c.guid=?2 AND c.status='member' AND m.banned=0
 AND NOT EXISTS(SELECT 1 FROM rename_holds WHERE discord_id=?1 AND state='reapply')`).bind(id,guid).first();if(!linked)throw new QrHeld('verified_councillor_guid_required');const m=await guildMember(env,id);if(!m)throw new QrHeld('signer_not_in_server');if((env.BLOCKING_ROLE_IDS||'').split(',').some(x=>x.trim()&&m.roles.includes(x.trim())))throw new QrHeld('signer_server_restriction');}
/** Enrollment is fresh server roster authority; the fixed24h lease subsequently trusts fresh signed game observation.
 * Any newer incomplete/untrusted or contradictory roster closes the lease. The original expiry is never renewed.
 */
export const SIGNER_CURRENT=`EXISTS(SELECT 1 FROM councillor_keys k JOIN privacy_subjects s ON s.subject_id=k.signer JOIN characters c ON c.discord_id=k.signer AND c.guid=k.signer_guid JOIN members m ON m.discord_id=k.signer
 WHERE k.id=?1 AND k.signer=?2 AND k.revoked_at IS NULL AND k.expires_at>${DB_NOW} AND s.generation=k.subject_generation AND s.state='active' AND c.status='member' AND m.banned=0
 AND NOT EXISTS(SELECT 1 FROM rename_holds WHERE discord_id=k.signer AND state='reapply') AND NOT EXISTS(SELECT 1 FROM roster_snapshots x WHERE x.id>k.roster_id AND x.id=(SELECT MAX(id) FROM roster_snapshots)
 AND (x.complete IS NOT 1 OR x.trusted IS NOT 1 OR x.exported_at>${DB_NOW} OR x.member_count<>(SELECT COUNT(*) FROM roster_members WHERE snapshot_id=x.id)
 OR (SELECT COUNT(*) FROM roster_members WHERE snapshot_id=x.id AND guid=k.signer_guid AND rank='High Council' AND rank_index=1)<>1)))`;
export async function enrollKey(env:QrEnv,id:string,guid:string,publicKey:unknown,session:QrSession){requireQr(env);bytesFromBase64(publicKey,32);const s=await active(env,id,session);await serverSigner(env,id,guid);const r=await rosterIdentity(env,guid,true),key=randomGeneration();
 const out=await env.DB.prepare(`INSERT INTO councillor_keys(id,signer,signer_guid,public_key,subject_generation,roster_id,created_at,expires_at) SELECT ?3,?1,?4,?5,?2,?6,${DB_NOW},${DB_NOW}+86400 WHERE ${privacyGenerationFenceSql(1,2)}
 AND NOT EXISTS(SELECT 1 FROM councillor_keys WHERE signer=?1 AND revoked_at IS NULL AND expires_at>${DB_NOW})
 AND EXISTS(SELECT 1 FROM roster_snapshots x JOIN roster_members r ON r.snapshot_id=x.id WHERE x.id=?6 AND x.id=(SELECT MAX(id) FROM roster_snapshots) AND x.complete=1 AND x.trusted=1 AND x.exported_at<=${DB_NOW} AND x.exported_at>${DB_NOW}-600 AND x.exported_at>=?7
 AND x.member_count=(SELECT COUNT(*) FROM roster_members WHERE snapshot_id=x.id) AND r.guid=?4 AND r.rank='High Council' AND r.rank_index=1)
 AND EXISTS(SELECT 1 FROM characters c JOIN members m ON m.discord_id=c.discord_id WHERE c.discord_id=?1 AND c.guid=?4 AND c.status='member' AND m.banned=0)
 AND NOT EXISTS(SELECT 1 FROM rename_holds WHERE discord_id=?1 AND state='reapply')
 AND ?9>${DB_NOW} AND EXISTS(SELECT 1 FROM site_users WHERE discord_id=?1 AND session_version=?8 AND in_server=1)
 RETURNING id`).bind(id,s.subjectGeneration,key,guid,publicKey,r.snapshot_id,Number(env.LINKS_NOT_BEFORE||0),session.v,session.e).first<{id:string}>();if(!out)throw new QrHeld('enrollment_currentness_changed');return {id:key,leaseSeconds:86400};}
export async function revokeKey(env:QrEnv,id:string,key:string,session:QrSession){requireQr(env);const s=await active(env,id,session);const r=await env.DB.prepare(`UPDATE councillor_keys SET revoked_at=${DB_NOW} WHERE id=?3 AND signer=?1 AND subject_generation=?2 AND revoked_at IS NULL AND ${privacyGenerationFenceSql(1,2)}
 AND ?5>${DB_NOW} AND EXISTS(SELECT 1 FROM site_users WHERE discord_id=?1 AND session_version=?4 AND in_server=1) RETURNING id`).bind(id,s.subjectGeneration,key,session.v,session.e).first();if(!r)throw new QrHeld('key_not_current');}
export async function issueChallenge(env:QrEnv,id:string,key:string,v:number,e:number,mode:'single'|'automatic'='single'){requireQr(env);if(!HEX.test(key)||!Number.isSafeInteger(v)||v<1||!Number.isSafeInteger(e)||!['single','automatic'].includes(mode))throw new QrHeld('invalid_session');const k=await env.DB.prepare(`SELECT * FROM councillor_keys WHERE id=?1 AND signer=?2 AND ${SIGNER_CURRENT}`).bind(key,id).first<KeyRow>();if(!k)throw new QrHeld('key_expired_revoked_or_councillor_changed');await serverSigner(env,id,k.signer_guid);const nonce=randomGeneration();
 const r=await env.DB.prepare(`INSERT INTO councillor_challenges(nonce,key_id,signer,session_version,session_expires,created_at,expires_at,mode,max_proofs,proofs_used) SELECT ?3,?1,?2,?4,?5,${DB_NOW},MIN(${DB_NOW}+300,?5),?6,?7,0 WHERE ${SIGNER_CURRENT} AND ?5>${DB_NOW}
 AND EXISTS(SELECT 1 FROM site_users WHERE discord_id=?2 AND session_version=?4 AND in_server=1) AND (SELECT COUNT(*) FROM councillor_challenges WHERE signer=?2 AND used_at IS NULL AND expires_at>${DB_NOW})<3 RETURNING nonce,expires_at`).bind(key,id,nonce,v,e,mode,mode==='automatic'?10:1).first<{nonce:string;expires_at:number}>();if(!r)throw new QrHeld('challenge_held');return {nonce,expiresAt:r.expires_at,expiresIn:Math.min(300,e-Math.floor(Date.now()/1000)),mode,maxProofs:mode==='automatic'?10:1,signerGuid:k.signer_guid,profile:QR_PROFILE};}
export async function cancelChallenge(env:QrEnv,id:string,nonce:string,session:QrSession){requireQr(env);if(!HEX.test(nonce))throw new QrHeld('invalid_challenge');
 const r=await env.DB.prepare(`UPDATE councillor_challenges SET used_at=${DB_NOW} WHERE nonce=?3 AND signer=?1 AND session_version=?4 AND session_expires=?5 AND used_at IS NULL
 AND ${privacyGenerationFenceSql(1,2)} AND ?5>${DB_NOW} AND EXISTS(SELECT 1 FROM site_users WHERE discord_id=?1 AND session_version=?4 AND in_server=1) RETURNING nonce`).bind(id,session.g,nonce,session.v,session.e).first();if(!r)throw new QrHeld('challenge_not_current');}
async function requestCode(env:QrEnv,id:string,session:QrSession|null){requireQr(env);if(!ID.test(id))throw new QrHeld('invalid_subject');const s=await readPrivacySubject(env,id);if(s&&s.state!=='active'||session&&(!s||s.subjectGeneration!==session.g))throw new QrHeld('current_serving_generation_required');if(!await guildMember(env,id))throw new QrHeld('requester_not_in_server');const code=randomGeneration();
 const r=await env.DB.prepare(`INSERT INTO verification_requests(code,requester,subject_generation,created_at,expires_at,session_version,session_expires) SELECT ?3,?1,?2,${DB_NOW},MIN(${DB_NOW}+600,COALESCE(?5,${DB_NOW}+600)),?4,?5 WHERE ${privacyGenerationFenceSql(1,2)}
 AND (?4 IS NULL OR (?5>${DB_NOW} AND EXISTS(SELECT 1 FROM site_users WHERE discord_id=?1 AND session_version=?4 AND in_server=1))) AND NOT EXISTS(SELECT 1 FROM members WHERE discord_id=?1 AND banned=1)
 AND NOT EXISTS(SELECT 1 FROM rename_holds WHERE discord_id=?1 AND state='reapply') AND (SELECT COUNT(*) FROM verification_requests WHERE requester=?1 AND used_at IS NULL AND expires_at>${DB_NOW})<3 RETURNING code`).bind(id,s?.subjectGeneration??null,code,session?.v??null,session?.e??null).first();if(!r)throw new QrHeld('request_held');return {code,expiresIn:600};}
export const createWebsiteRequest=(env:QrEnv,id:string,session:QrSession)=>requestCode(env,id,session);
/** This wrapper validates the signed interaction itself; a shaped actor string cannot enter accountless admission. */
export async function createInteractionRequest(env:QrEnv,request:Request,raw:string){if(raw.length>8192||!await verifyInteraction(env,request,raw))throw new QrHeld('invalid_interaction');const x=JSON.parse(raw),id=x?.member?.user?.id;if(!env.DISCORD_APP_ID||x.application_id!==env.DISCORD_APP_ID||x.type!==2||x.guild_id!==env.GUILD_ID||x.data?.name!=='olympus-qr'||typeof id!=='string')throw new QrHeld('invalid_interaction');return requestCode(env,id,null);}
export type GameObservation={challenge:string;code:string;requesterGuid:string;signerGuid:string;timestamp:number;requesterName:string;requesterRank:number};
export function parseGameObservation(wire:unknown):GameObservation {if(typeof wire!=='string'||new TextEncoder().encode(wire).length>512)throw new QrHeld('invalid_game_observation');const p=wire.split('|');if(p.length!==14||p[0]!=='OLG1'||!HEX.test(p[1])||!HEX.test(p[2])||!GUID.test(p[3])||!GUID.test(p[4])||!/^\d{10}$/.test(p[5])||p[6]!=='70205'||p[7]!=='16001'||!p[8]||p[8].length>60||/[\p{C}|]/u.test(p[8])||p[8]!==p[8].normalize('NFC')||p[9]!=='OLYMPUS'||p[10]!==QR_PROFILE.realm||!/^\d$/.test(p[11])||p[12]!=='1'||p[13]!==NATIVE_RANKS[Number(p[11])])throw new QrHeld('invalid_game_observation');return {challenge:p[1],code:p[2],requesterGuid:p[3],signerGuid:p[4],timestamp:Number(p[5]),requesterName:p[8],requesterRank:Number(p[11])};}
export const attestationBytes=(key:string,requester:string,signer:string,wire:string)=>new TextEncoder().encode(JSON.stringify(['OLY-P1',key,requester,signer,QR_PROFILE.revision,wire]));
export async function prepareAttestation(env:QrEnv,id:string,wire:string){requireQr(env);const o=parseGameObservation(wire),r=await env.DB.prepare(`SELECT v.requester,c.key_id,c.mode,c.max_proofs,c.proofs_used,c.expires_at,k.signer_guid FROM verification_requests v,councillor_challenges c JOIN councillor_keys k ON k.id=c.key_id WHERE v.code=?1 AND c.nonce=?2 AND c.signer=?3 AND v.requester<>?3 AND v.used_at IS NULL AND c.used_at IS NULL AND c.proofs_used<c.max_proofs AND v.expires_at>${DB_NOW} AND c.expires_at>${DB_NOW}`).bind(o.code,o.challenge,id).first<{requester:string;key_id:string;mode:string;max_proofs:number;proofs_used:number;expires_at:number;signer_guid:string}>();if(!r)throw new QrHeld('request_or_challenge_stale');return {requester:r.requester,signer:id,keyId:r.key_id,mode:r.mode,remaining:r.max_proofs-r.proofs_used,expiresAt:r.expires_at,signerGuid:r.signer_guid,profile:QR_PROFILE};}
export async function ingestAttestation(env:QrEnv,id:string,session:QrSession,input:unknown){requireQr(env);if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).sort().join(',')!=='keyId,signature,wire')throw new QrHeld('invalid_attestation');const {keyId,signature,wire}=input as {keyId:string;signature:string;wire:string};if(!HEX.test(keyId))throw new QrHeld('invalid_key');const sig=bytesFromBase64(signature,64),o=parseGameObservation(wire),p=await prepareAttestation(env,id,wire);if(p.keyId!==keyId)throw new QrHeld('challenge_key_mismatch');const k=await env.DB.prepare(`SELECT * FROM councillor_keys WHERE id=?1 AND signer=?2 AND ${SIGNER_CURRENT}`).bind(keyId,id).first<KeyRow>();if(!k||k.subject_generation!==session.g||k.signer_guid!==o.signerGuid||Math.abs(Math.floor(Date.now()/1000)-o.timestamp)>60)throw new QrHeld('key_or_game_observation_stale');const key=await crypto.subtle.importKey('raw',bytesFromBase64(k.public_key,32),{name:'Ed25519'},false,['verify']);if(!await crypto.subtle.verify('Ed25519',key,sig,attestationBytes(keyId,p.requester,id,wire)))throw new QrHeld('invalid_signature');await serverSigner(env,id,k.signer_guid);
 const requester=await guildMember(env,p.requester);if(!requester||(env.BLOCKING_ROLE_IDS||'').split(',').some(r=>r.trim()&&requester.roles.includes(r.trim())))throw new QrHeld('requester_server_restriction');
 const proof=randomGeneration(),digest=await sha256(JSON.stringify([keyId,signature,wire]));
 const guard=`${SIGNER_CURRENT} AND EXISTS(SELECT 1 FROM verification_requests v,councillor_challenges c WHERE v.code=?3 AND c.nonce=?4 AND c.key_id=?1 AND c.signer=?2 AND v.requester=?5 AND v.requester<>?2
 AND v.used_at IS NULL AND c.used_at IS NULL AND c.proofs_used<c.max_proofs AND v.expires_at>${DB_NOW} AND c.expires_at>${DB_NOW} AND c.session_version=?6 AND c.session_expires=?7 AND ?7>${DB_NOW}
 AND EXISTS(SELECT 1 FROM site_users WHERE discord_id=?2 AND session_version=?6 AND in_server=1)
 AND (CASE WHEN v.subject_generation IS NULL THEN NOT EXISTS(SELECT 1 FROM privacy_subjects WHERE subject_id=v.requester) ELSE EXISTS(SELECT 1 FROM privacy_subjects WHERE subject_id=v.requester AND generation=v.subject_generation AND state='active') END)
 AND (v.session_version IS NULL OR (v.session_expires>${DB_NOW} AND EXISTS(SELECT 1 FROM site_users WHERE discord_id=v.requester AND session_version=v.session_version AND in_server=1)))
 AND NOT EXISTS(SELECT 1 FROM members WHERE discord_id=v.requester AND banned=1) AND NOT EXISTS(SELECT 1 FROM rename_holds WHERE discord_id=v.requester AND state='reapply'))
 AND NOT EXISTS(SELECT 1 FROM characters WHERE (guid=?8 AND discord_id<>?5 AND status IN('member','left_pending')) OR (discord_id=?5 AND guid<>?8 AND status='member'))
 AND EXISTS(SELECT 1 FROM councillor_keys k JOIN roster_snapshots r ON r.id=k.roster_id WHERE k.id=?1 AND r.exported_at>=?10)
 AND (SELECT COUNT(*) FROM characters WHERE guid=?9 AND discord_id=?2 AND status='member')=1
 AND EXISTS(SELECT 1 FROM councillor_keys WHERE id=?1 AND subject_generation=?11)`;
 const b=[keyId,id,o.code,o.challenge,p.requester,session.v,session.e,o.requesterGuid,o.signerGuid,Number(env.LINKS_NOT_BEFORE||0),session.g];
 const batch=await env.DB.batch([
 env.DB.prepare(`SELECT CASE WHEN ${guard} THEN 1 ELSE json_extract('qr_admission_changed','$') END AS admitted`).bind(...b),
 env.DB.prepare(`INSERT INTO verification_proofs(id,code,challenge,signer,key_id,requester,requester_guid,requester_name,native_rank,rank_name,native_profile,signer_guid,snapshot_id,subject_generation,digest,created_at,expires_at) SELECT ?1,?2,?3,?4,?5,?6,?7,?8,?9,?12,'ten-rank',?10,k.roster_id,v.subject_generation,?11,${DB_NOW},${DB_NOW}+300 FROM councillor_keys k,verification_requests v WHERE k.id=?5 AND v.code=?2`).bind(proof,o.code,o.challenge,id,keyId,p.requester,o.requesterGuid,o.requesterName,o.requesterRank,o.signerGuid,digest,NATIVE_RANKS[o.requesterRank]),
 env.DB.prepare(`INSERT INTO members(discord_id) VALUES(?1) ON CONFLICT(discord_id) DO NOTHING`).bind(p.requester),
 env.DB.prepare(`INSERT INTO characters(name_key,name,discord_id,status,bound_at,verified_at,source,guid) VALUES(?1,?2,?3,'member',${DB_NOW},${DB_NOW},'councillor-browser',?4) ON CONFLICT(name_key) DO UPDATE SET discord_id=?3,status='member',verified_at=${DB_NOW},source='councillor-browser',guid=?4 WHERE characters.discord_id=?3 AND characters.guid=?4`).bind(o.requesterName.replace(/[A-Z]/g,c=>c.toLowerCase()),o.requesterName,p.requester,o.requesterGuid),
 env.DB.prepare(`SELECT CASE WHEN EXISTS(SELECT 1 FROM characters WHERE discord_id=?1 AND name=?2 AND guid=?3 AND status='member') THEN 1 ELSE json_extract('qr_link_conflict','$') END AS linked`).bind(p.requester,o.requesterName,o.requesterGuid),
 env.DB.prepare(`UPDATE verification_requests SET used_at=${DB_NOW},state='proved' WHERE code=?1 AND used_at IS NULL`).bind(o.code),
 env.DB.prepare(`UPDATE councillor_challenges SET proofs_used=proofs_used+1,used_at=CASE WHEN proofs_used+1>=max_proofs THEN ${DB_NOW} ELSE NULL END WHERE nonce=?1 AND used_at IS NULL AND proofs_used<max_proofs RETURNING max_proofs-proofs_used AS remaining`).bind(o.challenge),
 ]);return {proofId:proof,state:'proved' as const,leaseRemaining:(batch[6]!.results[0] as {remaining:number}).remaining};}
export async function requestStatus(env:QrEnv,id:string,code:string){requireQr(env);if(!HEX.test(code))throw new QrHeld('invalid_code');const r=await env.DB.prepare('SELECT state,expires_at FROM verification_requests WHERE code=?1 AND requester=?2').bind(code,id).first<{state:string;expires_at:number}>();if(!r)throw new QrHeld('request_not_owned');return {state:r.state==='pending'&&r.expires_at<=Math.floor(Date.now()/1000)?'expired':r.state};}
